"""Dependency-light Digitone reverse-engineering reference package."""

from .archive import ArchiveRecord, archive_sound, load_json, load_raw, save_json, save_raw
from .model import (
    A_RATIO_CALIBRATION,
    B_RATIO_CALIBRATION,
    C_RATIO_CALIBRATION,
    CanonicalDigitoneSound,
    DigitoneSound,
    PARAM_LOOK,
    Sound,
    decode,
    decode_sound,
)
from .sysex import (
    DIGITONE_SOUND_HEADER,
    ELEKTRON_HEADER,
    MidiTimeoutError,
    MidiUnavailableError,
    SoundMessage,
    SoundValidationError,
    SysExError,
    SysExFramingError,
    build_request,
    build_sound_request,
    capture_current_sound,
    capture_sound,
    iter_sysex_frames,
    list_midi_ports,
    parse,
    parse_sysex_stream,
    request_current_sound,
    resolve_midi_ports,
    validate,
    validate_sound_message,
)

__all__ = [
    "A_RATIO_CALIBRATION",
    "ArchiveRecord",
    "B_RATIO_CALIBRATION",
    "C_RATIO_CALIBRATION",
    "CanonicalDigitoneSound",
    "DIGITONE_SOUND_HEADER",
    "DigitoneSound",
    "ELEKTRON_HEADER",
    "MidiTimeoutError",
    "MidiUnavailableError",
    "PARAM_LOOK",
    "SoundMessage",
    "Sound",
    "SoundValidationError",
    "SysExError",
    "SysExFramingError",
    "archive_sound",
    "build_request",
    "build_sound_request",
    "capture_current_sound",
    "capture_sound",
    "decode",
    "decode_sound",
    "iter_sysex_frames",
    "list_midi_ports",
    "load_json",
    "load_raw",
    "parse_sysex_stream",
    "parse",
    "request_current_sound",
    "resolve_midi_ports",
    "save_json",
    "save_raw",
    "validate_sound_message",
    "validate",
]
