export const CLOUD_PRESET_SUMMARY_SELECT = [
  'id',
  'name',
  'author',
  'description',
  'created_at',
  'plays',
  'is_featured',
].join(',');

export const CLOUD_PRESET_DETAIL_SELECT = [
  ...CLOUD_PRESET_SUMMARY_SELECT.split(','),
  'data',
].join(',');

export const LEGACY_CLOUD_CARD_SELECT = [
  'id',
  'name',
  'author',
  'description',
  'created_at',
  'plays',
  'visibility',
].join(',');

export const PRESET_V2_CLOUD_CARD_SELECT = [
  'id',
  'name',
  'creator',
  'description',
  'visibility',
  'play_count',
  'created_at',
  'updated_at',
].join(',');

export const PRESET_V2_SUMMARY_SELECT = [
  'id',
  'owner_user_id',
  'type',
  'scope',
  'name',
  'author',
  'library',
  'creator',
  'description',
  'tags',
  'visibility',
  'family_name',
  'variant_name',
  'variant_rank',
  'latest_version_no',
  'latest_metadata_hash',
  'play_count',
  'rating',
  'deleted_at',
  'created_at',
  'updated_at',
].join(',');

export const PRESET_V2_ROW_SELECT = [
  'id',
  'owner_key',
  'owner_user_id',
  'type',
  'scope',
  'name',
  'author',
  'library',
  'creator',
  'description',
  'tags',
  'visibility',
  'family_name',
  'variant_name',
  'variant_rank',
  'forked_from',
  'latest_version_no',
  'latest_version_id',
  'latest_resolved_hash',
  'latest_metadata_hash',
  'play_count',
  'rating',
  'archived',
  'deleted_at',
  'deleted_by',
  'created_at',
  'updated_at',
].join(',');

export const PRESET_VERSION_SELECT = [
  'id',
  'preset_id',
  'version_no',
  'created_by',
  'parent_version_id',
  'storage_mode',
  'note',
  'override_hash',
  'metadata_hash',
  'patch_from_prev_hash',
  'resolved_hash',
  'is_checkpoint',
  'created_at',
].join(',');

export const PRESET_VERSION_REF_SELECT = [
  'version_id',
  'ref_slot',
  'target_preset_id',
  'target_version_no',
  'follow_latest',
  'override_hash',
  'created_at',
].join(',');

export const PRESET_PAYLOAD_SELECT = [
  'hash',
  'payload_kind',
  'payload',
  'payload_bytes',
  'created_at',
  'last_seen_at',
].join(',');

export const LEGACY_PRESET_ROW_SELECT = [
  'id',
  'user_id',
  'type',
  'scope',
  'name',
  'author',
  'library',
  'creator',
  'description',
  'tags',
  'visibility',
  'family_name',
  'variant_name',
  'variant_rank',
  'forked_from',
  'plays',
  'versions',
  'current_version',
  'created_at',
  'updated_at',
  'rating',
].join(',');

export const LEGACY_PRESET_SUMMARY_SELECT = [
  'id',
  'user_id',
  'type',
  'scope',
  'name',
  'author',
  'library',
  'creator',
  'description',
  'tags',
  'visibility',
  'family_name',
  'variant_name',
  'variant_rank',
  'plays',
  'current_version',
  'created_at',
  'updated_at',
  'rating',
].join(',');
