import type { SliderState } from '../state';

export interface DynamicsPresetDefinition {
  name: string;
  description: string;
  tags: string[];
  params: Record<string, unknown>;
}

export const EROSION_MOD_TARGETS = [
  { id: 'Wow', label: 'Wow' },
  { id: 'Flutter', label: 'Flutter' },
  { id: 'Lp', label: 'LP' },
  { id: 'Wet', label: 'Wet' },
  { id: 'Dropout', label: 'Dropout' },
  { id: 'Alias', label: 'Alias' },
] as const;

export const EROSION_MOD_SOURCES = [
  {
    id: 'Slow',
    label: 'Slow',
    keys: {
      Wow: 'erosionModSlowWow',
      Flutter: 'erosionModSlowFlutter',
      Lp: 'erosionModSlowLp',
      Wet: 'erosionModSlowWet',
      Dropout: 'erosionModSlowDropout',
      Alias: 'erosionModSlowAlias',
    },
  },
  {
    id: 'Flutter',
    label: 'Flutter',
    keys: {
      Wow: 'erosionModFlutterWow',
      Flutter: 'erosionModFlutterFlutter',
      Lp: 'erosionModFlutterLp',
      Wet: 'erosionModFlutterWet',
      Dropout: 'erosionModFlutterDropout',
      Alias: 'erosionModFlutterAlias',
    },
  },
  {
    id: 'Random',
    label: 'Random',
    keys: {
      Wow: 'erosionModRandomWow',
      Flutter: 'erosionModRandomFlutter',
      Lp: 'erosionModRandomLp',
      Wet: 'erosionModRandomWet',
      Dropout: 'erosionModRandomDropout',
      Alias: 'erosionModRandomAlias',
    },
  },
  {
    id: 'Env',
    label: 'Env',
    keys: {
      Wow: 'erosionModEnvWow',
      Flutter: 'erosionModEnvFlutter',
      Lp: 'erosionModEnvLp',
      Wet: 'erosionModEnvWet',
      Dropout: 'erosionModEnvDropout',
      Alias: 'erosionModEnvAlias',
    },
  },
  {
    id: 'Noise',
    label: 'Noise',
    keys: {
      Wow: 'erosionModNoiseWow',
      Flutter: 'erosionModNoiseFlutter',
      Lp: 'erosionModNoiseLp',
      Wet: 'erosionModNoiseWet',
      Dropout: 'erosionModNoiseDropout',
      Alias: 'erosionModNoiseAlias',
    },
  },
] as const satisfies readonly {
  id: string;
  label: string;
  keys: Record<(typeof EROSION_MOD_TARGETS)[number]['id'], keyof SliderState>;
}[];

export const EROSION_MOD_MATRIX_KEYS = EROSION_MOD_SOURCES.flatMap((source) =>
  EROSION_MOD_TARGETS.map((target) => source.keys[target.id]),
) as readonly (keyof SliderState)[];

const EROSION_MOD_NEUTRAL: Partial<Record<keyof SliderState, number>> = Object.fromEntries(
  EROSION_MOD_MATRIX_KEYS.map((key) => [key, 0]),
) as Partial<Record<keyof SliderState, number>>;

const EROSION_MOD_SUBTLE_TAPE: Partial<Record<keyof SliderState, number>> = {
  ...EROSION_MOD_NEUTRAL,
  erosionModSlowWow: 0.08,
  erosionModSlowLp: 0.04,
  erosionModFlutterFlutter: 0.025,
  erosionModRandomFlutter: 0.035,
  erosionModRandomDropout: 0.015,
  erosionModNoiseFlutter: 0.015,
};

const EROSION_MOD_GENERATION: Partial<Record<keyof SliderState, number>> = {
  ...EROSION_MOD_NEUTRAL,
  erosionModSlowWow: 0.18,
  erosionModSlowLp: 0.2,
  erosionModSlowWet: 0.025,
  erosionModRandomFlutter: 0.09,
  erosionModRandomLp: 0.2,
  erosionModRandomDropout: 0.055,
  erosionModEnvLp: 0.045,
  erosionModNoiseFlutter: 0.05,
  erosionModNoiseDropout: 0.04,
};

const EROSION_MOD_ZOIA_CORROSION: Partial<Record<keyof SliderState, number>> = {
  ...EROSION_MOD_NEUTRAL,
  erosionModSlowWow: 0.055,
  erosionModRandomWow: 0.04,
  erosionModRandomFlutter: 0.06,
  erosionModRandomAlias: 0.18,
  erosionModRandomDropout: 0.035,
  erosionModNoiseAlias: 0.22,
  erosionModNoiseFlutter: 0.055,
  erosionModFlutterAlias: 0.08,
};

const EROSION_MOD_VHS: Partial<Record<keyof SliderState, number>> = {
  ...EROSION_MOD_NEUTRAL,
  erosionModSlowWow: 0.28,
  erosionModSlowLp: 0.22,
  erosionModSlowDropout: 0.07,
  erosionModRandomWow: 0.16,
  erosionModRandomFlutter: 0.075,
  erosionModRandomLp: 0.18,
  erosionModRandomDropout: 0.09,
};

const EROSION_MOD_CASSETTE: Partial<Record<keyof SliderState, number>> = {
  ...EROSION_MOD_NEUTRAL,
  erosionModSlowWow: 0.09,
  erosionModSlowLp: 0.12,
  erosionModFlutterFlutter: 0.09,
  erosionModRandomFlutter: 0.24,
  erosionModRandomDropout: 0.08,
  erosionModNoiseFlutter: 0.14,
  erosionModNoiseDropout: 0.07,
  erosionModRandomLp: 0.16,
};

const EROSION_MOD_BROKEN: Partial<Record<keyof SliderState, number>> = {
  ...EROSION_MOD_NEUTRAL,
  erosionModSlowWow: 0.16,
  erosionModSlowLp: 0.16,
  erosionModFlutterFlutter: 0.12,
  erosionModRandomWow: 0.18,
  erosionModRandomFlutter: 0.42,
  erosionModRandomLp: 0.24,
  erosionModRandomWet: 0.08,
  erosionModRandomDropout: 0.2,
  erosionModRandomAlias: 0.08,
  erosionModNoiseFlutter: 0.28,
  erosionModNoiseDropout: 0.16,
  erosionModNoiseAlias: 0.08,
};

export const DYNAMICS_SIDECHAIN_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'sidechainKeyA',
  'sidechainKeyB',
  'sidechainKeyAWeight',
  'sidechainKeyBWeight',
  'sidechainAmount',
  'sidechainThreshold',
  'sidechainRatio',
  'sidechainKnee',
  'sidechainAttackMs',
  'sidechainHoldMs',
  'sidechainReleaseMs',
  'sidechainMakeup',
  'sidechainMix',
  'sidechainCurve',
  'sidechainDetectorHp',
  'sidechainDetectorLp',
];

export const DYNAMICS_EQ1_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'dynamicsEq1InputGain',
  'dynamicsEq1OutputGain',
  'dynamicsEq1Mix',
  'dynamicsEq1LowType',
  'dynamicsEq1LowFreq',
  'dynamicsEq1LowGain',
  'dynamicsEq1LowQ',
  'dynamicsEq1LowSlope',
  'dynamicsEq1MidFreq',
  'dynamicsEq1MidGain',
  'dynamicsEq1MidQ',
  'dynamicsEq1HighType',
  'dynamicsEq1HighFreq',
  'dynamicsEq1HighGain',
  'dynamicsEq1HighQ',
  'dynamicsEq1HighSlope',
];

export const DYNAMICS_EQ2_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'dynamicsEq2InputGain',
  'dynamicsEq2OutputGain',
  'dynamicsEq2Mix',
  'dynamicsEq2LowType',
  'dynamicsEq2LowFreq',
  'dynamicsEq2LowGain',
  'dynamicsEq2LowQ',
  'dynamicsEq2LowSlope',
  'dynamicsEq2MidFreq',
  'dynamicsEq2MidGain',
  'dynamicsEq2MidQ',
  'dynamicsEq2HighType',
  'dynamicsEq2HighFreq',
  'dynamicsEq2HighGain',
  'dynamicsEq2HighQ',
  'dynamicsEq2HighSlope',
];

export const DYNAMICS_BUS_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'dynamicsBusEnabled',
  'dynamicsEq1Enabled',
  'dynamicsEq2Enabled',
  'sidechainEnabled',
  ...DYNAMICS_EQ1_PRESET_KEYS,
  ...DYNAMICS_EQ2_PRESET_KEYS,
  ...DYNAMICS_SIDECHAIN_PRESET_KEYS,
];

const EQ1_FLAT_PARAMS: Record<string, unknown> = {
  dynamicsEq1InputGain: 0,
  dynamicsEq1OutputGain: 0,
  dynamicsEq1Mix: 1,
  dynamicsEq1LowType: 'shelf',
  dynamicsEq1LowFreq: 120,
  dynamicsEq1LowGain: 0,
  dynamicsEq1LowQ: 0.7,
  dynamicsEq1LowSlope: 1,
  dynamicsEq1MidFreq: 1000,
  dynamicsEq1MidGain: 0,
  dynamicsEq1MidQ: 0.9,
  dynamicsEq1HighType: 'shelf',
  dynamicsEq1HighFreq: 8000,
  dynamicsEq1HighGain: 0,
  dynamicsEq1HighQ: 0.7,
  dynamicsEq1HighSlope: 1,
};

const EQ2_FLAT_PARAMS: Record<string, unknown> = {
  dynamicsEq2InputGain: 0,
  dynamicsEq2OutputGain: 0,
  dynamicsEq2Mix: 1,
  dynamicsEq2LowType: 'shelf',
  dynamicsEq2LowFreq: 90,
  dynamicsEq2LowGain: 0,
  dynamicsEq2LowQ: 0.7,
  dynamicsEq2LowSlope: 1,
  dynamicsEq2MidFreq: 2200,
  dynamicsEq2MidGain: 0,
  dynamicsEq2MidQ: 0.9,
  dynamicsEq2HighType: 'shelf',
  dynamicsEq2HighFreq: 10000,
  dynamicsEq2HighGain: 0,
  dynamicsEq2HighQ: 0.7,
  dynamicsEq2HighSlope: 1,
};

export const DYNAMICS_EQ1_PRESETS: Record<string, DynamicsPresetDefinition> = {
  eq1Bypass: {
    name: 'EQ 1 Bypass',
    description: 'Leaves EQ 1 flat and bypassed.',
    tags: ['eq', 'bypass', 'dynamics-bus'],
    params: EQ1_FLAT_PARAMS,
  },
  warmShelf: {
    name: 'Warm Shelf',
    description: 'Adds broad low shelf weight and a small high shelf trim for darker bus shaping.',
    tags: ['eq', 'warm', 'shelf'],
    params: {
      ...EQ1_FLAT_PARAMS,
      dynamicsEq1LowType: 'shelf',
      dynamicsEq1LowFreq: 140,
      dynamicsEq1LowGain: 1.8,
      dynamicsEq1LowQ: 0.8,
      dynamicsEq1LowSlope: 0.8,
      dynamicsEq1HighType: 'shelf',
      dynamicsEq1HighFreq: 7200,
      dynamicsEq1HighGain: -1.2,
      dynamicsEq1HighSlope: 0.65,
    },
  },
  presenceBell: {
    name: 'Presence Bell',
    description: 'Uses a focused mid bell and gentle air shelf for light terminal presence.',
    tags: ['eq', 'presence', 'bell'],
    params: {
      ...EQ1_FLAT_PARAMS,
      dynamicsEq1MidFreq: 2600,
      dynamicsEq1MidGain: 1.5,
      dynamicsEq1MidQ: 1.2,
      dynamicsEq1HighType: 'shelf',
      dynamicsEq1HighFreq: 9800,
      dynamicsEq1HighGain: 0.9,
      dynamicsEq1HighSlope: 0.6,
    },
  },
};

export const DYNAMICS_EQ2_PRESETS: Record<string, DynamicsPresetDefinition> = {
  eq2Bypass: {
    name: 'EQ 2 Bypass',
    description: 'Leaves EQ 2 flat and bypassed.',
    tags: ['eq', 'bypass', 'dynamics-bus'],
    params: EQ2_FLAT_PARAMS,
  },
  lowControl: {
    name: 'Low Control',
    description: 'Tightens the terminal low band with a low bell cut and subtle high shelf lift.',
    tags: ['eq', 'low-control', 'bell'],
    params: {
      ...EQ2_FLAT_PARAMS,
      dynamicsEq2LowType: 'bell',
      dynamicsEq2LowFreq: 85,
      dynamicsEq2LowGain: -1.8,
      dynamicsEq2LowQ: 1.1,
      dynamicsEq2MidFreq: 360,
      dynamicsEq2MidGain: -0.8,
      dynamicsEq2MidQ: 0.9,
      dynamicsEq2HighType: 'shelf',
      dynamicsEq2HighFreq: 9600,
      dynamicsEq2HighGain: 0.6,
      dynamicsEq2HighSlope: 0.5,
    },
  },
  airPolish: {
    name: 'Air Polish',
    description: 'Adds a restrained high shelf and a wide low shelf trim for final gloss.',
    tags: ['eq', 'air', 'shelf'],
    params: {
      ...EQ2_FLAT_PARAMS,
      dynamicsEq2LowType: 'shelf',
      dynamicsEq2LowFreq: 110,
      dynamicsEq2LowGain: -0.7,
      dynamicsEq2LowSlope: 0.5,
      dynamicsEq2HighType: 'shelf',
      dynamicsEq2HighFreq: 11200,
      dynamicsEq2HighGain: 1.4,
      dynamicsEq2HighQ: 0.8,
      dynamicsEq2HighSlope: 0.55,
    },
  },
};

export const DYNAMICS_END_CHAIN_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'endCompMode',
  'endCompThreshold',
  'endCompKnee',
  'endCompRatio',
  'endCompAttackMs',
  'endCompReleaseMs',
  'endCompMakeup',
  'endCompMix',
  'endCompDetectorHp',
  'endCompDetectorTilt',
  'endCompAutoMakeup',
  'endCompProgramRelease',
  'endCompPeakBlend',
  'endCompClarity',
  'endCompTwoBandAmount',
  'endCompBandSplit',
];

export const DYNAMICS_DRIFT_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'driftMode',
  'driftQuality',
  'driftAntiComb',
  'driftDiffusion',
  'driftMix',
  'driftAge',
  'driftBias',
  'driftLpgAmount',
  'driftDepth',
  'driftRate',
  'driftDamp',
  'driftWetHp',
  'driftEnvFollow',
  'driftStereo',
  'driftResonance',
];

export const DYNAMICS_EROSION_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'erosionQuality',
  'erosionEventAmount',
  'erosionProfileAmount',
  'erosionDitherAmount',
  'erosionMix',
  'erosionAge',
  'erosionGeneration',
  'erosionAlias',
  'erosionWow',
  'erosionFlutter',
  'erosionDrift',
  'erosionWobbleSpeed',
  'erosionNoise',
  'erosionTone',
  'erosionSaturation',
  'erosionCorrosion',
  ...EROSION_MOD_MATRIX_KEYS,
];

export const DYNAMICS_DEGRADE_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'degradeEnabled',
  'degradeHp',
  'degradeLp',
  'driftEnabled',
  'erosionEnabled',
  ...DYNAMICS_DRIFT_PRESET_KEYS,
  ...DYNAMICS_EROSION_PRESET_KEYS,
];

export const DYNAMICS_SATURATION_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'dynamicsSaturationMode',
  'dynamicsSaturationQuality',
  'dynamicsSaturationDrive',
  'dynamicsSaturationTone',
  'dynamicsSaturationBias',
];

export const MASTER_SATURATION_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'masterSaturationMode',
  'masterSaturationQuality',
  'masterSaturationDrive',
  'masterSaturationTone',
  'masterSaturationBias',
];

export const DYNAMICS_MASTER_FX_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'masterSaturationEnabled',
  ...MASTER_SATURATION_PRESET_KEYS,
  'endCompEnabled',
  ...DYNAMICS_END_CHAIN_PRESET_KEYS,
];

export const DYNAMICS_SIDECHAIN_PRESETS: Record<string, DynamicsPresetDefinition> = {
  sidechainBypass: {
    name: 'Sidechain Bypass',
    description: 'Leaves the Dynamics sidechain ducking stage off for clean A/B testing.',
    tags: ['sidechain', 'bypass', 'clean'],
    params: {
      sidechainKeyA: 'off',
      sidechainKeyB: 'off',
      sidechainKeyAWeight: 1,
      sidechainKeyBWeight: 0,
      sidechainAmount: 0,
      sidechainThreshold: -24,
      sidechainRatio: 4,
      sidechainKnee: 6,
      sidechainAttackMs: 5,
      sidechainHoldMs: 20,
      sidechainReleaseMs: 180,
      sidechainMakeup: 1,
      sidechainMix: 1,
      sidechainCurve: 0.5,
      sidechainDetectorHp: 0,
      sidechainDetectorLp: 1,
    },
  },
  tightKickDuck: {
    name: 'Tight Kick Duck',
    description: 'Fast, controlled kick ducking for making pads, leads, and granular returns clear the transient.',
    tags: ['sidechain', 'kick', 'tight'],
    params: {
      sidechainKeyA: 'kick',
      sidechainKeyB: 'off',
      sidechainKeyAWeight: 1,
      sidechainKeyBWeight: 0,
      sidechainAmount: 0.68,
      sidechainThreshold: -28,
      sidechainRatio: 8,
      sidechainKnee: 2,
      sidechainAttackMs: 1.5,
      sidechainHoldMs: 14,
      sidechainReleaseMs: 110,
      sidechainMakeup: 1,
      sidechainMix: 1,
      sidechainCurve: 0.65,
      sidechainDetectorHp: 0.12,
      sidechainDetectorLp: 0.78,
    },
  },
  edmWavePump: {
    name: 'EDM Wave Pump',
    description: 'Longer, obvious pumping curve for four-on-the-floor movement and wave-like pad ducking.',
    tags: ['sidechain', 'edm', 'pump'],
    params: {
      sidechainKeyA: 'kick',
      sidechainKeyB: 'sub',
      sidechainKeyAWeight: 1,
      sidechainKeyBWeight: 0.45,
      sidechainAmount: 0.88,
      sidechainThreshold: -42,
      sidechainRatio: 12,
      sidechainKnee: 8,
      sidechainAttackMs: 3,
      sidechainHoldMs: 72,
      sidechainReleaseMs: 420,
      sidechainMakeup: 1,
      sidechainMix: 1,
      sidechainCurve: 0.84,
      sidechainDetectorHp: 0.04,
      sidechainDetectorLp: 0.7,
    },
  },
  breathingPads: {
    name: 'Breathing Pads',
    description: 'Slow release ducking that keeps ambient beds moving without sounding like a club pump.',
    tags: ['sidechain', 'ambient', 'pads'],
    params: {
      sidechainKeyA: 'kick',
      sidechainKeyB: 'membrane',
      sidechainKeyAWeight: 0.8,
      sidechainKeyBWeight: 0.55,
      sidechainAmount: 0.48,
      sidechainThreshold: -32,
      sidechainRatio: 4,
      sidechainKnee: 14,
      sidechainAttackMs: 8,
      sidechainHoldMs: 35,
      sidechainReleaseMs: 650,
      sidechainMakeup: 1,
      sidechainMix: 0.9,
      sidechainCurve: 0.48,
      sidechainDetectorHp: 0.1,
      sidechainDetectorLp: 0.82,
    },
  },
  granularPocket: {
    name: 'Granular Pocket',
    description: 'Ducks granular and delay returns harder than the dry voices so texture stays behind the groove.',
    tags: ['sidechain', 'granular', 'delay'],
    params: {
      sidechainKeyA: 'kick',
      sidechainKeyB: 'click',
      sidechainKeyAWeight: 0.9,
      sidechainKeyBWeight: 0.35,
      sidechainAmount: 0.62,
      sidechainThreshold: -30,
      sidechainRatio: 6,
      sidechainKnee: 6,
      sidechainAttackMs: 2.5,
      sidechainHoldMs: 24,
      sidechainReleaseMs: 260,
      sidechainMakeup: 1,
      sidechainMix: 1,
      sidechainCurve: 0.58,
      sidechainDetectorHp: 0.16,
      sidechainDetectorLp: 0.74,
    },
  },
};

export const DYNAMICS_BUS_PRESETS: Record<string, DynamicsPresetDefinition> = {
  busBypass: {
    name: 'Dynamics Bus Bypass',
    description: 'Leaves EQ 1, EQ 2, and Sidechain Compression bypassed.',
    tags: ['dynamics-bus', 'bypass', 'clean'],
    params: {
      dynamicsBusEnabled: false,
      dynamicsEq1Enabled: false,
      dynamicsEq2Enabled: false,
      sidechainEnabled: false,
      ...DYNAMICS_EQ1_PRESETS.eq1Bypass!.params,
      ...DYNAMICS_EQ2_PRESETS.eq2Bypass!.params,
      ...DYNAMICS_SIDECHAIN_PRESETS.sidechainBypass!.params,
    },
  },
  cleanBus: {
    name: 'Clean Dynamics Bus',
    description: 'Turns the Dynamics Bus on with flat EQs and no sidechain compression.',
    tags: ['dynamics-bus', 'clean', 'flat'],
    params: {
      dynamicsBusEnabled: true,
      dynamicsEq1Enabled: false,
      dynamicsEq2Enabled: false,
      sidechainEnabled: false,
      ...DYNAMICS_EQ1_PRESETS.eq1Bypass!.params,
      ...DYNAMICS_EQ2_PRESETS.eq2Bypass!.params,
      ...DYNAMICS_SIDECHAIN_PRESETS.sidechainBypass!.params,
    },
  },
  warmPocket: {
    name: 'Warm Pocket',
    description: 'Combines broad low warmth, subtle air polish, and pocketed kick sidechain targets.',
    tags: ['dynamics-bus', 'warm', 'sidechain'],
    params: {
      dynamicsBusEnabled: true,
      dynamicsEq1Enabled: true,
      dynamicsEq2Enabled: true,
      sidechainEnabled: true,
      ...DYNAMICS_EQ1_PRESETS.warmShelf!.params,
      ...DYNAMICS_EQ2_PRESETS.airPolish!.params,
      ...DYNAMICS_SIDECHAIN_PRESETS.tightKickDuck!.params,
    },
  },
  texturePocket: {
    name: 'Texture Pocket',
    description: 'Keeps dry voices steadier while ducking granular, delay, and reverb texture returns.',
    tags: ['dynamics-bus', 'texture', 'granular'],
    params: {
      dynamicsBusEnabled: true,
      dynamicsEq1Enabled: true,
      dynamicsEq2Enabled: true,
      sidechainEnabled: true,
      ...DYNAMICS_EQ1_PRESETS.presenceBell!.params,
      ...DYNAMICS_EQ2_PRESETS.lowControl!.params,
      ...DYNAMICS_SIDECHAIN_PRESETS.granularPocket!.params,
    },
  },
};

export const DYNAMICS_DRIFT_PRESETS: Record<string, DynamicsPresetDefinition> = {
  shallowWaterDrift: {
    name: 'Shallow Water Drift',
    description: 'Slow, dark shallow-water drift with restrained stereo and heavy damping.',
    tags: ['drift', 'warble', 'chorus'],
    params: {
      driftMode: 'shallowWater',
      driftMix: 0.54,
      driftAge: 0.34,
      driftBias: 0.22,
      driftLpgAmount: 0.46,
      driftDepth: 0.58,
      driftRate: 0.055,
      driftDamp: 0.82,
      driftWetHp: 0.04,
      driftEnvFollow: 0.08,
      driftStereo: 0.56,
      driftResonance: 0.18,
    },
  },
  abyssWaterLpg: {
    name: 'Abyss Water LPG',
    description: 'Dark, centered envelope lowpass bloom inspired by the ZOIA Abyss Water patch.',
    tags: ['drift', 'abyss', 'lpg'],
    params: {
      driftMode: 'abyssWater',
      driftMix: 1,
      driftAge: 0,
      driftBias: 0.18,
      driftLpgAmount: 0.94,
      driftDepth: 0.3333,
      driftRate: 0.4667,
      driftDamp: 0.3333,
      driftWetHp: 0.02,
      driftEnvFollow: 0.8333,
      driftStereo: 0.3333,
      driftResonance: 0.475,
    },
  },
  cleanMotion: {
    name: 'Clean Motion',
    description: 'Subtle movement and width without audible media damage.',
    tags: ['drift', 'clean', 'subtle'],
    params: {
      driftMode: 'clean',
      driftMix: 0.18,
      driftAge: 0.02,
      driftBias: 0.82,
      driftLpgAmount: 0.06,
      driftDepth: 0.08,
      driftRate: 0.12,
      driftDamp: 0.58,
      driftWetHp: 0,
      driftEnvFollow: 0.02,
      driftStereo: 0.24,
      driftResonance: 0.1,
    },
  },
  cleanWidth: {
    name: 'Clean Width',
    description: 'Clean-mode stereo widening and gentle motion without envelope bloom or watery filtering.',
    tags: ['drift', 'clean', 'width'],
    params: {
      driftMode: 'clean',
      driftMix: 0.36,
      driftAge: 0.04,
      driftBias: 0.88,
      driftLpgAmount: 0.08,
      driftDepth: 0.26,
      driftRate: 0.28,
      driftDamp: 0.42,
      driftWetHp: 0,
      driftEnvFollow: 0,
      driftStereo: 0.78,
      driftResonance: 0.08,
    },
  },
  cleanTapeHead: {
    name: 'Clean Tape Head',
    description: 'Clean-mode head motion with no envelope reaction, intended for pure wow/flutter testing.',
    tags: ['drift', 'clean', 'tape', 'test'],
    params: {
      driftMode: 'clean',
      driftMix: 0.88,
      driftAge: 0,
      driftBias: 0.9,
      driftLpgAmount: 0,
      driftDepth: 0.82,
      driftRate: 0.04,
      driftDamp: 0.72,
      driftWetHp: 0,
      driftEnvFollow: 0,
      driftStereo: 0.42,
      driftResonance: 0,
    },
  },
  envelopeRipple: {
    name: 'Envelope Ripple',
    description: 'A faster, brighter Abyss variant where transients ripple the lowpass path.',
    tags: ['drift', 'envelope', 'movement'],
    params: {
      driftMode: 'abyssWater',
      driftMix: 0.42,
      driftAge: 0.08,
      driftBias: 0.28,
      driftLpgAmount: 0.72,
      driftDepth: 0.28,
      driftRate: 0.34,
      driftDamp: 0.24,
      driftWetHp: 0.02,
      driftEnvFollow: 1,
      driftStereo: 0.5,
      driftResonance: 0.26,
    },
  },
  bucketBrigadeWide: {
    name: 'Bucket Brigade Wide',
    description: 'A high-depth shallow-water setting with wide phase color and animated pitch wander.',
    tags: ['drift', 'chorus', 'wide'],
    params: {
      driftMode: 'shallowWater',
      driftMix: 0.78,
      driftAge: 0.12,
      driftBias: 0.34,
      driftLpgAmount: 0.54,
      driftDepth: 0.96,
      driftRate: 0.24,
      driftDamp: 0.42,
      driftWetHp: 0.06,
      driftEnvFollow: 0.04,
      driftStereo: 1,
      driftResonance: 0.36,
    },
  },
  lpgBloom: {
    name: 'LPG Bloom',
    description: 'A wider, more resonant Abyss bloom for obvious lowpass-gate swelling.',
    tags: ['drift', 'lpg', 'bloom'],
    params: {
      driftMode: 'abyssWater',
      driftMix: 0.68,
      driftAge: 0.3,
      driftBias: 0.24,
      driftLpgAmount: 0.88,
      driftDepth: 0.66,
      driftRate: 0.09,
      driftDamp: 0.52,
      driftWetHp: 0.03,
      driftEnvFollow: 0.9,
      driftStereo: 0.58,
      driftResonance: 0.72,
    },
  },
};

export const DYNAMICS_EROSION_PRESETS: Record<string, DynamicsPresetDefinition> = {
  generationMemory: {
    name: 'Generation Memory',
    description: 'Balanced copied-media memory: tone loss, soft saturation, and copy noise without crushing the mix.',
    tags: ['degrade', 'tape', 'generation'],
    params: {
      erosionMix: 0.34,
      erosionAge: 0.44,
      erosionGeneration: 0.46,
      erosionAlias: 0.03,
      erosionWow: 0.24,
      erosionFlutter: 0.06,
      erosionDrift: 0.24,
      erosionWobbleSpeed: 0.34,
      erosionNoise: 0.08,
      erosionTone: 0.42,
      erosionSaturation: 0.16,
      erosionCorrosion: 0.07,
      ...EROSION_MOD_GENERATION,
      erosionModSlowLp: 0.1,
      erosionModRandomLp: 0.1,
      erosionModRandomDropout: 0.02,
    },
  },
  degenerateGain: {
    name: 'Degenerate Gain',
    description: 'Corrosive gain damage with noisy edge, saturation, and instability beyond simple bitcrush.',
    tags: ['degrade', 'alias', 'corrosion'],
    params: {
      erosionMix: 0.6,
      erosionAge: 0.48,
      erosionGeneration: 0.34,
      erosionAlias: 0.5,
      erosionWow: 0.12,
      erosionFlutter: 0.24,
      erosionDrift: 0.34,
      erosionWobbleSpeed: 0.54,
      erosionNoise: 0.18,
      erosionTone: 0.42,
      erosionSaturation: 0.54,
      erosionCorrosion: 0.78,
      ...EROSION_MOD_ZOIA_CORROSION,
      erosionModRandomDropout: 0.08,
      erosionModNoiseDropout: 0.08,
      erosionModNoiseAlias: 0.3,
    },
  },
  wornVhs: {
    name: 'Worn VHS',
    description: 'Soft, dark VHS wear with wide slow wobble, hiss, and gentle tape saturation.',
    tags: ['degrade', 'vhs', 'warble'],
    params: {
      erosionMix: 0.4,
      erosionAge: 0.66,
      erosionGeneration: 0.36,
      erosionAlias: 0.04,
      erosionWow: 0.62,
      erosionFlutter: 0.05,
      erosionDrift: 0.42,
      erosionWobbleSpeed: 0.32,
      erosionNoise: 0.13,
      erosionTone: 0.26,
      erosionSaturation: 0.2,
      erosionCorrosion: 0.09,
      ...EROSION_MOD_VHS,
      erosionModRandomFlutter: 0.035,
      erosionModRandomDropout: 0.04,
    },
  },
  wornCassette: {
    name: 'Worn Cassette',
    description: 'Cassette narrowing with hiss and uneven flutter, kept below the broken-media edge.',
    tags: ['degrade', 'cassette', 'tape'],
    params: {
      erosionMix: 0.44,
      erosionAge: 0.48,
      erosionGeneration: 0.32,
      erosionAlias: 0.08,
      erosionWow: 0.2,
      erosionFlutter: 0.34,
      erosionDrift: 0.18,
      erosionWobbleSpeed: 0.56,
      erosionNoise: 0.24,
      erosionTone: 0.38,
      erosionSaturation: 0.18,
      erosionCorrosion: 0.12,
      ...EROSION_MOD_CASSETTE,
      erosionModFlutterFlutter: 0.16,
      erosionModRandomFlutter: 0.3,
      erosionModNoiseFlutter: 0.2,
    },
  },
  brokenCassette: {
    name: 'Broken Cassette',
    description: 'Harder flutter, narrowed bandwidth, more noise, and stronger saturation for unstable cassette color.',
    tags: ['degrade', 'cassette', 'dirty'],
    params: {
      erosionMix: 0.66,
      erosionAge: 0.88,
      erosionGeneration: 0.78,
      erosionAlias: 0.3,
      erosionWow: 0.42,
      erosionFlutter: 0.54,
      erosionDrift: 0.62,
      erosionWobbleSpeed: 0.58,
      erosionNoise: 0.34,
      erosionTone: 0.12,
      erosionSaturation: 0.52,
      erosionCorrosion: 0.46,
      ...EROSION_MOD_BROKEN,
      erosionModRandomDropout: 0.28,
      erosionModNoiseDropout: 0.22,
      erosionModRandomWet: 0.12,
    },
  },
  clearTape: {
    name: 'Clear Tape',
    description: 'A light tape pass: small pitch instability, gentle drive, and minimal bandwidth loss.',
    tags: ['degrade', 'tape', 'subtle'],
    params: {
      erosionMix: 0.36,
      erosionAge: 0.08,
      erosionGeneration: 0.06,
      erosionAlias: 0,
      erosionWow: 0.32,
      erosionFlutter: 0.04,
      erosionDrift: 0.12,
      erosionWobbleSpeed: 0.32,
      erosionNoise: 0.02,
      erosionTone: 0.52,
      erosionSaturation: 0.02,
      erosionCorrosion: 0,
      ...EROSION_MOD_SUBTLE_TAPE,
    },
  },
  cleanWobbleTest: {
    name: 'Clean Wobble Test',
    description: 'Pure slow wow/flutter test path: no noise, damage, clipping, aliasing, generation, or corrosion.',
    tags: ['degrade', 'clean', 'wow', 'test'],
    params: {
      erosionMix: 1,
      erosionAge: 0,
      erosionGeneration: 0,
      erosionAlias: 0,
      erosionWow: 0.58,
      erosionFlutter: 0.06,
      erosionDrift: 0.18,
      erosionWobbleSpeed: 0.32,
      erosionNoise: 0,
      erosionTone: 0.5,
      erosionSaturation: 0,
      erosionCorrosion: 0,
      ...EROSION_MOD_NEUTRAL,
    },
  },
  secondGeneration: {
    name: 'Second Generation',
    description: 'Heavy copy loss with darker bandwidth, softer transients, and stronger generation smear.',
    tags: ['degrade', 'generation', 'tape'],
    params: {
      erosionMix: 0.52,
      erosionAge: 0.64,
      erosionGeneration: 0.88,
      erosionAlias: 0.04,
      erosionWow: 0.22,
      erosionFlutter: 0.08,
      erosionDrift: 0.3,
      erosionWobbleSpeed: 0.3,
      erosionNoise: 0.18,
      erosionTone: 0.16,
      erosionSaturation: 0.32,
      erosionCorrosion: 0.11,
      ...EROSION_MOD_GENERATION,
      erosionModSlowLp: 0.34,
      erosionModRandomLp: 0.32,
      erosionModEnvLp: 0.08,
    },
  },
  mkiiMemory: {
    name: 'MKII Memory',
    description: 'Cleaner looper-memory color: broad wow and drift, light copy age, gentle saturation, and little crush.',
    tags: ['degrade', 'generation', 'memory'],
    params: {
      erosionMix: 0.42,
      erosionAge: 0.32,
      erosionGeneration: 0.2,
      erosionAlias: 0.01,
      erosionWow: 0.64,
      erosionFlutter: 0.04,
      erosionDrift: 0.36,
      erosionWobbleSpeed: 0.28,
      erosionNoise: 0.035,
      erosionTone: 0.56,
      erosionSaturation: 0.14,
      erosionCorrosion: 0.02,
      ...EROSION_MOD_SUBTLE_TAPE,
      erosionModSlowWow: 0.3,
      erosionModSlowLp: 0.03,
      erosionModRandomWow: 0.12,
      erosionModRandomFlutter: 0.015,
    },
  },
  aliasedZoia: {
    name: 'Aliased ZOIA',
    description: 'Stepped sample-rate damage and high-mid grit with less analog wear than Degenerate Gain.',
    tags: ['degrade', 'alias', 'zoia'],
    params: {
      erosionMix: 0.44,
      erosionAge: 0.12,
      erosionGeneration: 0.08,
      erosionAlias: 0.9,
      erosionWow: 0.04,
      erosionFlutter: 0.08,
      erosionDrift: 0.08,
      erosionWobbleSpeed: 0.46,
      erosionNoise: 0.08,
      erosionTone: 0.72,
      erosionSaturation: 0.2,
      erosionCorrosion: 0.7,
      ...EROSION_MOD_ZOIA_CORROSION,
      erosionModRandomAlias: 0.32,
      erosionModNoiseAlias: 0.4,
      erosionModRandomDropout: 0.01,
    },
  },
  vhsTracking: {
    name: 'VHS Tracking',
    description: 'Unstable tracking wear with stronger slow wobble, dark bandwidth loss, and intermittent dropout.',
    tags: ['degrade', 'vhs', 'tracking'],
    params: {
      erosionMix: 0.58,
      erosionAge: 0.82,
      erosionGeneration: 0.48,
      erosionAlias: 0.12,
      erosionWow: 0.78,
      erosionFlutter: 0.12,
      erosionDrift: 0.64,
      erosionWobbleSpeed: 0.34,
      erosionNoise: 0.22,
      erosionTone: 0.14,
      erosionSaturation: 0.24,
      erosionCorrosion: 0.22,
      ...EROSION_MOD_VHS,
      erosionModSlowWow: 0.38,
      erosionModSlowDropout: 0.14,
      erosionModRandomDropout: 0.16,
    },
  },
};

export const DYNAMICS_SATURATION_PRESETS: Record<string, DynamicsPresetDefinition> = {
  cleanBypass: {
    name: 'Clean Bypass',
    description: 'Leaves the Dynamics master saturation stage off.',
    tags: ['saturation', 'clean', 'bypass'],
    params: {
      dynamicsSaturationMode: 'clean',
      dynamicsSaturationDrive: 0,
      dynamicsSaturationTone: 0.5,
      dynamicsSaturationBias: 0.5,
    },
  },
  tapeGlow: {
    name: 'Tape Glow',
    description: 'Medium-bright tape color for warming Drift or Erosion while staying smooth and bus-safe.',
    tags: ['saturation', 'tape', 'warm'],
    params: {
      dynamicsSaturationMode: 'tape',
      dynamicsSaturationDrive: 0.28,
      dynamicsSaturationTone: 0.55,
      dynamicsSaturationBias: 0.6,
    },
  },
  tubeLift: {
    name: 'Tube Lift',
    description: 'Barely driven tube lift for gentle presence before the bus sounds saturated.',
    tags: ['saturation', 'tube', 'presence'],
    params: {
      dynamicsSaturationMode: 'tube',
      dynamicsSaturationDrive: 0.1,
      dynamicsSaturationTone: 0.5,
      dynamicsSaturationBias: 0.52,
    },
  },
  wornTapeBus: {
    name: 'Worn Tape Bus',
    description: 'Darker medium tape saturation for old-media buses without adding Erosion noise or aliasing.',
    tags: ['saturation', 'tape', 'dark'],
    params: {
      dynamicsSaturationMode: 'tape',
      dynamicsSaturationDrive: 0.42,
      dynamicsSaturationTone: 0.24,
      dynamicsSaturationBias: 0.42,
    },
  },
  pushedTube: {
    name: 'Pushed Tube',
    description: 'High-drive tube color that leans on auto gain and 4x oversampling for controlled grit.',
    tags: ['saturation', 'tube', 'drive'],
    params: {
      dynamicsSaturationMode: 'tube',
      dynamicsSaturationDrive: 0.7,
      dynamicsSaturationTone: 0.54,
      dynamicsSaturationBias: 0.66,
    },
  },
  linenWarmth: {
    name: 'Linen Warmth',
    description: 'Very soft darker tape saturation for smoothing bright generative layers without sounding driven.',
    tags: ['saturation', 'tape', 'subtle', 'warm'],
    params: {
      dynamicsSaturationMode: 'tape',
      dynamicsSaturationDrive: 0.04,
      dynamicsSaturationTone: 0.34,
      dynamicsSaturationBias: 0.48,
    },
  },
  cassetteBloom: {
    name: 'Cassette Bloom',
    description: 'High-drive tape bloom with darker tone, stronger bias, and the 4x oversampled saturation path.',
    tags: ['saturation', 'tape', 'cassette', 'dark'],
    params: {
      dynamicsSaturationMode: 'tape',
      dynamicsSaturationDrive: 0.68,
      dynamicsSaturationTone: 0.31,
      dynamicsSaturationBias: 0.64,
    },
  },
  amberValve: {
    name: 'Amber Valve',
    description: 'Smooth mid-drive tube color with stronger bias for even-harmonic glow.',
    tags: ['saturation', 'tube', 'warm', 'bus'],
    params: {
      dynamicsSaturationMode: 'tube',
      dynamicsSaturationDrive: 0.34,
      dynamicsSaturationTone: 0.48,
      dynamicsSaturationBias: 0.78,
    },
  },
  glassTube: {
    name: 'Glass Tube',
    description: 'Brighter tube saturation for upper detail, with moderate drive and low asymmetry.',
    tags: ['saturation', 'tube', 'bright', 'presence'],
    params: {
      dynamicsSaturationMode: 'tube',
      dynamicsSaturationDrive: 0.28,
      dynamicsSaturationTone: 0.86,
      dynamicsSaturationBias: 0.52,
    },
  },
  diodePinch: {
    name: 'Diode Pinch',
    description: 'Asymmetric diode clipping for focused edge and transient bite without a huge level jump.',
    tags: ['saturation', 'diode', 'edge', 'transient'],
    params: {
      dynamicsSaturationMode: 'diode',
      dynamicsSaturationDrive: 0.3,
      dynamicsSaturationTone: 0.66,
      dynamicsSaturationBias: 0.84,
    },
  },
  emberDiode: {
    name: 'Ember Diode',
    description: 'High-drive dark diode saturation with pronounced asymmetry and 4x oversampling.',
    tags: ['saturation', 'diode', 'dark', 'grit'],
    params: {
      dynamicsSaturationMode: 'diode',
      dynamicsSaturationDrive: 0.72,
      dynamicsSaturationTone: 0.32,
      dynamicsSaturationBias: 0.92,
    },
  },
  foldHalo: {
    name: 'Fold Halo',
    description: 'Restrained, mostly symmetrical fold color for animated harmonics around pads, grains, and reverbs.',
    tags: ['saturation', 'fold', 'harmonics', 'motion'],
    params: {
      dynamicsSaturationMode: 'fold',
      dynamicsSaturationDrive: 0.22,
      dynamicsSaturationTone: 0.62,
      dynamicsSaturationBias: 0.5,
    },
  },
  prismaticFold: {
    name: 'Prismatic Fold',
    description: 'High-drive fold saturation for glassy harmonic pressure on the 4x oversampled path.',
    tags: ['saturation', 'fold', 'bright', 'color'],
    params: {
      dynamicsSaturationMode: 'fold',
      dynamicsSaturationDrive: 0.74,
      dynamicsSaturationTone: 0.78,
      dynamicsSaturationBias: 0.36,
    },
  },
  lowVelvet: {
    name: 'Low Velvet',
    description: 'Dark, symmetrical clean-curve saturation for softening the final bus and tucking sharp material back.',
    tags: ['saturation', 'dark', 'bus', 'smooth'],
    params: {
      dynamicsSaturationMode: 'clean',
      dynamicsSaturationDrive: 0.48,
      dynamicsSaturationTone: 0.2,
      dynamicsSaturationBias: 0.5,
    },
  },
};

export const DYNAMICS_END_CHAIN_PRESETS: Record<string, DynamicsPresetDefinition> = {
  endChainBypass: {
    name: 'End Chain Bypass',
    description: 'Leaves the final Dynamics compressor off for clean A/B testing.',
    tags: ['compressor', 'bypass', 'clean'],
    params: {
      endCompThreshold: -18,
      endCompKnee: 12,
      endCompRatio: 2,
      endCompAttackMs: 10,
      endCompReleaseMs: 180,
      endCompMakeup: 1,
      endCompMix: 1,
      endCompDetectorHp: 0.25,
      endCompDetectorTilt: 0.5,
      endCompAutoMakeup: 0,
      endCompProgramRelease: 0.5,
    },
  },
  glueBus: {
    name: 'Glue Bus',
    description: 'Balanced final bus glue with a gently filtered detector and program release that avoids chatter.',
    tags: ['compressor', 'glue', 'bus'],
    params: {
      endCompThreshold: -18,
      endCompKnee: 16,
      endCompRatio: 1.85,
      endCompAttackMs: 24,
      endCompReleaseMs: 220,
      endCompMakeup: 1,
      endCompMix: 0.72,
      endCompDetectorHp: 0.42,
      endCompDetectorTilt: 0.52,
      endCompAutoMakeup: 0.52,
      endCompProgramRelease: 0.72,
    },
  },
  clarityLift: {
    name: 'Clarity Lift',
    description: 'Bright-leaning detector compression with loudness help for a clearer, more polished output.',
    tags: ['compressor', 'clarity', 'polish'],
    params: {
      endCompThreshold: -24,
      endCompKnee: 20,
      endCompRatio: 1.45,
      endCompAttackMs: 32,
      endCompReleaseMs: 160,
      endCompMakeup: 1,
      endCompMix: 0.48,
      endCompDetectorHp: 0.62,
      endCompDetectorTilt: 0.82,
      endCompAutoMakeup: 0.78,
      endCompProgramRelease: 0.45,
    },
  },
  softCeiling: {
    name: 'Soft Ceiling',
    description: 'Fast soft-knee pre-limiter catch that tidies peaks without turning into a brickwall.',
    tags: ['compressor', 'peaks', 'control'],
    params: {
      endCompThreshold: -12,
      endCompKnee: 12,
      endCompRatio: 3.2,
      endCompAttackMs: 2.8,
      endCompReleaseMs: 120,
      endCompMakeup: 1,
      endCompMix: 0.6,
      endCompDetectorHp: 0.22,
      endCompDetectorTilt: 0.3,
      endCompAutoMakeup: 0.18,
      endCompProgramRelease: 0.32,
    },
  },
  openMaster: {
    name: 'Open Master',
    description: 'Very light leveling that keeps transients open and lets the limiter do only occasional safety work.',
    tags: ['compressor', 'open', 'light'],
    params: {
      endCompThreshold: -30,
      endCompKnee: 36,
      endCompRatio: 1.14,
      endCompAttackMs: 96,
      endCompReleaseMs: 360,
      endCompMakeup: 1,
      endCompMix: 0.22,
      endCompDetectorHp: 0.32,
      endCompDetectorTilt: 0.34,
      endCompAutoMakeup: 0.12,
      endCompProgramRelease: 0.5,
    },
  },
  subSafeGlue: {
    name: 'Sub-Safe Glue',
    description: 'Bus glue with a high detector focus so kick and sub weight do not drag the whole mix down.',
    tags: ['compressor', 'glue', 'sub-safe', 'detector'],
    params: {
      endCompThreshold: -20,
      endCompKnee: 16,
      endCompRatio: 1.8,
      endCompAttackMs: 26,
      endCompReleaseMs: 240,
      endCompMakeup: 1,
      endCompMix: 0.7,
      endCompDetectorHp: 0.82,
      endCompDetectorTilt: 0.9,
      endCompAutoMakeup: 0.45,
      endCompProgramRelease: 0.78,
    },
  },
  transientPass: {
    name: 'Transient Pass',
    description: 'Slow-attack compression that preserves clicks, plucks, and drum fronts while lightly leveling the tail.',
    tags: ['compressor', 'transient', 'punch', 'open'],
    params: {
      endCompThreshold: -21,
      endCompKnee: 12,
      endCompRatio: 1.8,
      endCompAttackMs: 64,
      endCompReleaseMs: 180,
      endCompMakeup: 1,
      endCompMix: 0.5,
      endCompDetectorHp: 0.52,
      endCompDetectorTilt: 0.58,
      endCompAutoMakeup: 0.35,
      endCompProgramRelease: 0.4,
    },
  },
  bloomControl: {
    name: 'Bloom Control',
    description: 'Slow ambient leveling for long reverbs, grains, and evolving pads that should breathe, not clamp.',
    tags: ['compressor', 'bloom', 'ambient', 'slow'],
    params: {
      endCompThreshold: -30,
      endCompKnee: 34,
      endCompRatio: 1.18,
      endCompAttackMs: 110,
      endCompReleaseMs: 680,
      endCompMakeup: 1,
      endCompMix: 0.52,
      endCompDetectorHp: 0.34,
      endCompDetectorTilt: 0.42,
      endCompAutoMakeup: 0.18,
      endCompProgramRelease: 1,
    },
  },
  motionTamer: {
    name: 'Motion Tamer',
    description: 'Program-dependent release for busy generative movement that needs control without nervous chatter.',
    tags: ['compressor', 'motion', 'program-release', 'smooth'],
    params: {
      endCompThreshold: -23,
      endCompKnee: 18,
      endCompRatio: 2.2,
      endCompAttackMs: 18,
      endCompReleaseMs: 320,
      endCompMakeup: 1,
      endCompMix: 0.62,
      endCompDetectorHp: 0.48,
      endCompDetectorTilt: 0.6,
      endCompAutoMakeup: 0.32,
      endCompProgramRelease: 1,
    },
  },
  rhythmicPump: {
    name: 'Rhythmic Pump',
    description: 'Obvious parallel bus compression where kick and low-end energy are allowed to drive the groove.',
    tags: ['compressor', 'pump', 'rhythm', 'parallel'],
    params: {
      endCompThreshold: -34,
      endCompKnee: 4,
      endCompRatio: 6.4,
      endCompAttackMs: 4,
      endCompReleaseMs: 96,
      endCompMakeup: 1,
      endCompMix: 0.42,
      endCompDetectorHp: 0.08,
      endCompDetectorTilt: 0.12,
      endCompAutoMakeup: 0.24,
      endCompProgramRelease: 0.08,
    },
  },
  silkCeiling: {
    name: 'Silk Ceiling',
    description: 'A soft pre-limiter catch for keeping peaks tidy without making the bus feel clamped.',
    tags: ['compressor', 'ceiling', 'peaks', 'soft'],
    params: {
      endCompThreshold: -14,
      endCompKnee: 22,
      endCompRatio: 2.7,
      endCompAttackMs: 3.5,
      endCompReleaseMs: 180,
      endCompMakeup: 1,
      endCompMix: 0.54,
      endCompDetectorHp: 0.34,
      endCompDetectorTilt: 0.48,
      endCompAutoMakeup: 0.16,
      endCompProgramRelease: 0.52,
    },
  },
  loudnessMatchGlue: {
    name: 'Loudness Match Glue',
    description: 'Moderate bus compression with stronger auto makeup for quick honest A/B against bypass.',
    tags: ['compressor', 'makeup', 'glue', 'match'],
    params: {
      endCompThreshold: -27,
      endCompKnee: 13,
      endCompRatio: 2.8,
      endCompAttackMs: 14,
      endCompReleaseMs: 150,
      endCompMakeup: 0.9,
      endCompMix: 0.6,
      endCompDetectorHp: 0.38,
      endCompDetectorTilt: 0.5,
      endCompAutoMakeup: 1,
      endCompProgramRelease: 0.55,
    },
  },
  wideWashGuard: {
    name: 'Wide Wash Guard',
    description: 'Gentle control for wide reverb and granular washes, with a filtered detector that ignores low-end sway.',
    tags: ['compressor', 'wide', 'wash', 'ambient'],
    params: {
      endCompThreshold: -25,
      endCompKnee: 26,
      endCompRatio: 1.45,
      endCompAttackMs: 42,
      endCompReleaseMs: 420,
      endCompMakeup: 1,
      endCompMix: 0.36,
      endCompDetectorHp: 0.78,
      endCompDetectorTilt: 0.92,
      endCompAutoMakeup: 0.42,
      endCompProgramRelease: 0.88,
    },
  },
};

export const DYNAMICS_MASTER_FX_PRESETS: Record<string, DynamicsPresetDefinition> = {
  cleanBypass: {
    name: 'Clean Master FX',
    description: 'Leaves the final color and compression stages bypassed.',
    tags: ['master-fx', 'bypass', 'clean'],
    params: {
      masterSaturationEnabled: false,
      masterSaturationMode: 'clean',
      masterSaturationQuality: 'smooth',
      masterSaturationDrive: 0,
      masterSaturationTone: 0.5,
      masterSaturationBias: 0.5,
      endCompEnabled: false,
      ...DYNAMICS_END_CHAIN_PRESETS.endChainBypass!.params,
    },
  },
  warmGlue: {
    name: 'Warm Glue',
    description: 'Tape warmth into gentle final bus glue for a finished but still open master stage.',
    tags: ['master-fx', 'tape', 'glue'],
    params: {
      masterSaturationEnabled: true,
      masterSaturationMode: 'tape',
      masterSaturationQuality: 'hq',
      masterSaturationDrive: 0.32,
      masterSaturationTone: 0.55,
      masterSaturationBias: 0.6,
      endCompEnabled: true,
      ...DYNAMICS_END_CHAIN_PRESETS.glueBus!.params,
    },
  },
  washGuard: {
    name: 'Wash Guard',
    description: 'Soft dark saturation with wide-wash compression that keeps reverb and granular returns controlled.',
    tags: ['master-fx', 'wash', 'ambient'],
    params: {
      masterSaturationEnabled: true,
      masterSaturationMode: 'tape',
      masterSaturationQuality: 'smooth',
      masterSaturationDrive: 0.18,
      masterSaturationTone: 0.32,
      masterSaturationBias: 0.45,
      endCompEnabled: true,
      ...DYNAMICS_END_CHAIN_PRESETS.wideWashGuard!.params,
    },
  },
};

const DEGRADE_PARENT_ON: Pick<SliderState, 'degradeEnabled' | 'degradeHp' | 'degradeLp' | 'driftEnabled' | 'erosionEnabled'> = {
  degradeEnabled: true,
  degradeHp: 0,
  degradeLp: 1,
  driftEnabled: true,
  erosionEnabled: true,
};

export const DYNAMICS_DEGRADE_PRESETS: Record<string, DynamicsPresetDefinition> = {
  cleanWobbleTest: {
    name: 'Clean Wobble Test',
    description: 'Degrade test preset for obvious slow tape wow/flutter with no added noise or bus compression.',
    tags: ['degrade', 'clean', 'wow', 'test'],
    params: {
      ...DEGRADE_PARENT_ON,
      ...DYNAMICS_DRIFT_PRESETS.cleanTapeHead!.params,
      ...DYNAMICS_EROSION_PRESETS.cleanWobbleTest!.params,
      degradeHp: 0,
      degradeLp: 1,
    },
  },
  ambientWaterDrift: {
    name: 'Ambient Water Drift',
    description: 'Abyss-style movement and clear tape wear for slow pads and wide washes.',
    tags: ['degrade', 'ambient', 'water', 'drift'],
    params: {
      ...DEGRADE_PARENT_ON,
      ...DYNAMICS_DRIFT_PRESETS.abyssWaterLpg!.params,
      ...DYNAMICS_EROSION_PRESETS.clearTape!.params,
      degradeHp: 0.02,
      degradeLp: 0.9,
    },
  },
  cleanMotion: {
    name: 'Clean Motion',
    description: 'Clean Drift motion with light Erosion color for movement that stays out of the way.',
    tags: ['degrade', 'clean', 'motion'],
    params: {
      ...DEGRADE_PARENT_ON,
      ...DYNAMICS_DRIFT_PRESETS.cleanMotion!.params,
      ...DYNAMICS_EROSION_PRESETS.clearTape!.params,
      degradeHp: 0.02,
      degradeLp: 0.9,
    },
  },
  degenerateTexture: {
    name: 'Degenerate Texture',
    description: 'Degenerate Gain-style corrosion through shallow water motion, without final bus compression.',
    tags: ['degrade', 'corrosion', 'texture'],
    params: {
      ...DEGRADE_PARENT_ON,
      ...DYNAMICS_DRIFT_PRESETS.shallowWaterDrift!.params,
      ...DYNAMICS_EROSION_PRESETS.degenerateGain!.params,
      degradeHp: 0.3,
      degradeLp: 0.36,
    },
  },
  generationLossWash: {
    name: 'Generation Loss Wash',
    description: 'Shallow-water motion into copied-media tape loss for a worn generational wash.',
    tags: ['degrade', 'generation', 'warble'],
    params: {
      ...DEGRADE_PARENT_ON,
      ...DYNAMICS_DRIFT_PRESETS.shallowWaterDrift!.params,
      ...DYNAMICS_EROSION_PRESETS.mkiiMemory!.params,
      degradeHp: 0.03,
      degradeLp: 0.82,
    },
  },
  vhsTracking: {
    name: 'VHS Tracking Bus',
    description: 'Abyss-style envelope color through VHS tracking wear and unstable copied-media motion.',
    tags: ['degrade', 'vhs', 'abyss'],
    params: {
      ...DEGRADE_PARENT_ON,
      ...DYNAMICS_DRIFT_PRESETS.abyssWaterLpg!.params,
      ...DYNAMICS_EROSION_PRESETS.vhsTracking!.params,
      degradeHp: 0.18,
      degradeLp: 0.26,
    },
  },
};
