import type { SliderState } from '../state';

export interface DynamicsPresetDefinition {
  name: string;
  description: string;
  tags: string[];
  params: Record<string, unknown>;
}

export const DYNAMICS_SIDECHAIN_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'sidechainEnabled',
  'sidechainKeyA',
  'sidechainKeyB',
  'sidechainKeyAWeight',
  'sidechainKeyBWeight',
  'sidechainAmount',
  'sidechainThreshold',
  'sidechainRatio',
  'sidechainKnee',
  'sidechainAttackMs',
  'sidechainHoldMs',
  'sidechainReleaseMs',
  'sidechainMakeup',
  'sidechainMix',
  'sidechainCurve',
  'sidechainDetectorHp',
  'sidechainDetectorLp',
  'sidechainPad1Target',
  'sidechainPad2Target',
  'sidechainLead1Target',
  'sidechainLead2Target',
  'sidechainPianoTarget',
  'sidechainGranularTarget',
  'sidechainDelayATarget',
  'sidechainDelayBTarget',
  'sidechainReverbTarget',
];

export const DYNAMICS_END_CHAIN_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'endCompEnabled',
  'endCompThreshold',
  'endCompKnee',
  'endCompRatio',
  'endCompAttackMs',
  'endCompReleaseMs',
  'endCompMakeup',
  'endCompMix',
];

export const DYNAMICS_CHARACTER_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'characterEnabled',
  'characterMode',
  'characterMix',
  'characterAge',
  'characterDepth',
  'characterRate',
  'characterDamp',
  'characterEnvFollow',
  'characterStereo',
  'characterResonance',
];

export const DYNAMICS_DEGRADE_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'degradeEnabled',
  'degradeMix',
  'degradeAge',
  'degradeGeneration',
  'degradeAlias',
  'degradeWow',
  'degradeFlutter',
  'degradeDrift',
  'degradeNoise',
  'degradeHp',
  'degradeLp',
  'degradeTone',
  'degradeSaturation',
  'degradeCorrosion',
];

export const DYNAMICS_SATURATION_PRESET_KEYS: readonly (keyof SliderState)[] = [
  'dynamicsSaturationEnabled',
  'dynamicsSaturationMode',
  'dynamicsSaturationDrive',
  'dynamicsSaturationTone',
];

export const DYNAMICS_SIDECHAIN_PRESETS: Record<string, DynamicsPresetDefinition> = {
  tightKickDuck: {
    name: 'Tight Kick Duck',
    description: 'Fast, controlled kick ducking for making pads, leads, and granular returns clear the transient.',
    tags: ['sidechain', 'kick', 'tight'],
    params: {
      sidechainEnabled: true,
      sidechainKeyA: 'kick',
      sidechainKeyB: 'off',
      sidechainKeyAWeight: 1,
      sidechainKeyBWeight: 0,
      sidechainAmount: 0.68,
      sidechainThreshold: -28,
      sidechainRatio: 8,
      sidechainKnee: 2,
      sidechainAttackMs: 1.5,
      sidechainHoldMs: 14,
      sidechainReleaseMs: 110,
      sidechainMakeup: 1,
      sidechainMix: 1,
      sidechainCurve: 0.65,
      sidechainDetectorHp: 0.12,
      sidechainDetectorLp: 0.78,
      sidechainPad1Target: 0.55,
      sidechainPad2Target: 0.55,
      sidechainLead1Target: 0.35,
      sidechainLead2Target: 0.35,
      sidechainPianoTarget: 0.3,
      sidechainGranularTarget: 0.55,
      sidechainDelayATarget: 0.35,
      sidechainDelayBTarget: 0.35,
      sidechainReverbTarget: 0.42,
    },
  },
  edmWavePump: {
    name: 'EDM Wave Pump',
    description: 'Longer, obvious pumping curve for four-on-the-floor movement and wave-like pad ducking.',
    tags: ['sidechain', 'edm', 'pump'],
    params: {
      sidechainEnabled: true,
      sidechainKeyA: 'kick',
      sidechainKeyB: 'sub',
      sidechainKeyAWeight: 1,
      sidechainKeyBWeight: 0.45,
      sidechainAmount: 0.88,
      sidechainThreshold: -42,
      sidechainRatio: 12,
      sidechainKnee: 8,
      sidechainAttackMs: 3,
      sidechainHoldMs: 72,
      sidechainReleaseMs: 420,
      sidechainMakeup: 1,
      sidechainMix: 1,
      sidechainCurve: 0.84,
      sidechainDetectorHp: 0.04,
      sidechainDetectorLp: 0.7,
      sidechainPad1Target: 0.9,
      sidechainPad2Target: 0.9,
      sidechainLead1Target: 0.65,
      sidechainLead2Target: 0.65,
      sidechainPianoTarget: 0.45,
      sidechainGranularTarget: 0.82,
      sidechainDelayATarget: 0.68,
      sidechainDelayBTarget: 0.68,
      sidechainReverbTarget: 0.72,
    },
  },
  breathingPads: {
    name: 'Breathing Pads',
    description: 'Slow release ducking that keeps ambient beds moving without sounding like a club pump.',
    tags: ['sidechain', 'ambient', 'pads'],
    params: {
      sidechainEnabled: true,
      sidechainKeyA: 'kick',
      sidechainKeyB: 'membrane',
      sidechainKeyAWeight: 0.8,
      sidechainKeyBWeight: 0.55,
      sidechainAmount: 0.48,
      sidechainThreshold: -32,
      sidechainRatio: 4,
      sidechainKnee: 14,
      sidechainAttackMs: 8,
      sidechainHoldMs: 35,
      sidechainReleaseMs: 650,
      sidechainMakeup: 1,
      sidechainMix: 0.9,
      sidechainCurve: 0.48,
      sidechainDetectorHp: 0.1,
      sidechainDetectorLp: 0.82,
      sidechainPad1Target: 0.72,
      sidechainPad2Target: 0.72,
      sidechainLead1Target: 0.28,
      sidechainLead2Target: 0.28,
      sidechainPianoTarget: 0.34,
      sidechainGranularTarget: 0.58,
      sidechainDelayATarget: 0.22,
      sidechainDelayBTarget: 0.22,
      sidechainReverbTarget: 0.45,
    },
  },
  granularPocket: {
    name: 'Granular Pocket',
    description: 'Ducks granular and delay returns harder than the dry voices so texture stays behind the groove.',
    tags: ['sidechain', 'granular', 'delay'],
    params: {
      sidechainEnabled: true,
      sidechainKeyA: 'kick',
      sidechainKeyB: 'click',
      sidechainKeyAWeight: 0.9,
      sidechainKeyBWeight: 0.35,
      sidechainAmount: 0.62,
      sidechainThreshold: -30,
      sidechainRatio: 6,
      sidechainKnee: 6,
      sidechainAttackMs: 2.5,
      sidechainHoldMs: 24,
      sidechainReleaseMs: 260,
      sidechainMakeup: 1,
      sidechainMix: 1,
      sidechainCurve: 0.58,
      sidechainDetectorHp: 0.16,
      sidechainDetectorLp: 0.74,
      sidechainPad1Target: 0.3,
      sidechainPad2Target: 0.3,
      sidechainLead1Target: 0.18,
      sidechainLead2Target: 0.18,
      sidechainPianoTarget: 0.24,
      sidechainGranularTarget: 0.78,
      sidechainDelayATarget: 0.68,
      sidechainDelayBTarget: 0.72,
      sidechainReverbTarget: 0.64,
    },
  },
};

export const DYNAMICS_CHARACTER_PRESETS: Record<string, DynamicsPresetDefinition> = {
  shallowWaterDrift: {
    name: 'Shallow Water Drift',
    description: 'A wider, slower chorus-vibrato movement inspired by shallow-water style pitch wander.',
    tags: ['character', 'warble', 'chorus'],
    params: {
      characterEnabled: true,
      characterMode: 'shallowWater',
      characterMix: 0.72,
      characterAge: 0.26,
      characterDepth: 0.86,
      characterRate: 0.11,
      characterDamp: 0.64,
      characterEnvFollow: 0.06,
      characterStereo: 0.88,
      characterResonance: 0.3,
    },
  },
  abyssWaterLpg: {
    name: 'Abyss Water LPG',
    description: 'Envelope-reactive lowpass movement with resonance, compression, and damping for watery ZOIA-style motion.',
    tags: ['character', 'abyss', 'lpg'],
    params: {
      characterEnabled: true,
      characterMode: 'abyssWater',
      characterMix: 0.66,
      characterAge: 0.3,
      characterDepth: 0.74,
      characterRate: 0.08,
      characterDamp: 0.92,
      characterEnvFollow: 0.86,
      characterStereo: 0.46,
      characterResonance: 0.84,
    },
  },
  cleanMotion: {
    name: 'Clean Motion',
    description: 'Subtle movement and width without audible media damage.',
    tags: ['character', 'clean', 'subtle'],
    params: {
      characterEnabled: true,
      characterMode: 'clean',
      characterMix: 0.32,
      characterAge: 0.06,
      characterDepth: 0.22,
      characterRate: 0.24,
      characterDamp: 0.55,
      characterEnvFollow: 0.04,
      characterStereo: 0.5,
      characterResonance: 0.2,
    },
  },
  envelopeRipple: {
    name: 'Envelope Ripple',
    description: 'A more animated envelope-following character for transients that open the tone and drift path.',
    tags: ['character', 'envelope', 'movement'],
    params: {
      characterEnabled: true,
      characterMode: 'abyssWater',
      characterMix: 0.58,
      characterAge: 0.16,
      characterDepth: 0.56,
      characterRate: 0.18,
      characterDamp: 0.72,
      characterEnvFollow: 0.96,
      characterStereo: 0.5,
      characterResonance: 0.62,
    },
  },
  bucketBrigadeWide: {
    name: 'Bucket Brigade Wide',
    description: 'A high-depth shallow-water setting with wide phase color and slow pitch wander.',
    tags: ['character', 'chorus', 'wide'],
    params: {
      characterEnabled: true,
      characterMode: 'shallowWater',
      characterMix: 0.78,
      characterAge: 0.18,
      characterDepth: 0.92,
      characterRate: 0.16,
      characterDamp: 0.52,
      characterEnvFollow: 0.04,
      characterStereo: 0.96,
      characterResonance: 0.24,
    },
  },
  lpgBloom: {
    name: 'LPG Bloom',
    description: 'Abyss-style envelope bloom with heavier resonance and compressed wet-path body.',
    tags: ['character', 'lpg', 'bloom'],
    params: {
      characterEnabled: true,
      characterMode: 'abyssWater',
      characterMix: 0.62,
      characterAge: 0.2,
      characterDepth: 0.68,
      characterRate: 0.1,
      characterDamp: 0.88,
      characterEnvFollow: 1,
      characterStereo: 0.38,
      characterResonance: 0.92,
    },
  },
};

export const DYNAMICS_DEGRADE_PRESETS: Record<string, DynamicsPresetDefinition> = {
  generationMemory: {
    name: 'Generation Memory',
    description: 'Tape age, tone loss, soft saturation, and copy noise in the Generation Loss territory without crushing the mix.',
    tags: ['degrade', 'tape', 'generation'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.38,
      degradeAge: 0.52,
      degradeGeneration: 0.56,
      degradeAlias: 0.06,
      degradeWow: 0.22,
      degradeFlutter: 0.14,
      degradeDrift: 0.46,
      degradeNoise: 0.11,
      degradeHp: 0.1,
      degradeLp: 0.5,
      degradeTone: 0.32,
      degradeSaturation: 0.22,
      degradeCorrosion: 0.12,
    },
  },
  degenerateGain: {
    name: 'Degenerate Gain',
    description: 'Aliased, resonant, noisy lo-fi damage inspired by the Degenerate Gain ZOIA patch notes.',
    tags: ['degrade', 'alias', 'corrosion'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.46,
      degradeAge: 0.36,
      degradeGeneration: 0.24,
      degradeAlias: 0.64,
      degradeWow: 0.28,
      degradeFlutter: 0.62,
      degradeDrift: 0.42,
      degradeNoise: 0.1,
      degradeHp: 0.24,
      degradeLp: 0.5,
      degradeTone: 0.46,
      degradeSaturation: 0.28,
      degradeCorrosion: 0.5,
    },
  },
  wornVhs: {
    name: 'Worn VHS',
    description: 'Wide, unstable drift with darker tone, hiss, and soft tape saturation.',
    tags: ['degrade', 'vhs', 'warble'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.42,
      degradeAge: 0.62,
      degradeGeneration: 0.52,
      degradeAlias: 0.08,
      degradeWow: 0.42,
      degradeFlutter: 0.22,
      degradeDrift: 0.64,
      degradeNoise: 0.14,
      degradeHp: 0.12,
      degradeLp: 0.4,
      degradeTone: 0.28,
      degradeSaturation: 0.24,
      degradeCorrosion: 0.16,
    },
  },
  brokenCassette: {
    name: 'Broken Cassette',
    description: 'Harder flutter, narrowed bandwidth, more noise, and stronger saturation for unstable cassette color.',
    tags: ['degrade', 'cassette', 'dirty'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.46,
      degradeAge: 0.72,
      degradeGeneration: 0.58,
      degradeAlias: 0.22,
      degradeWow: 0.34,
      degradeFlutter: 0.46,
      degradeDrift: 0.62,
      degradeNoise: 0.18,
      degradeHp: 0.2,
      degradeLp: 0.36,
      degradeTone: 0.22,
      degradeSaturation: 0.34,
      degradeCorrosion: 0.38,
    },
  },
  clearTape: {
    name: 'Clear Tape',
    description: 'A light tape pass: small pitch instability, gentle drive, and minimal bandwidth loss.',
    tags: ['degrade', 'tape', 'subtle'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.22,
      degradeAge: 0.2,
      degradeGeneration: 0.18,
      degradeAlias: 0.05,
      degradeWow: 0.12,
      degradeFlutter: 0.08,
      degradeDrift: 0.18,
      degradeNoise: 0.04,
      degradeHp: 0.02,
      degradeLp: 0.9,
      degradeTone: 0.52,
      degradeSaturation: 0.08,
      degradeCorrosion: 0.06,
    },
  },
  secondGeneration: {
    name: 'Second Generation',
    description: 'Copied-media loss with darker bandwidth, softer transients, and enough generation smear to read as old tape.',
    tags: ['degrade', 'generation', 'tape'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.42,
      degradeAge: 0.58,
      degradeGeneration: 0.66,
      degradeAlias: 0.05,
      degradeWow: 0.2,
      degradeFlutter: 0.12,
      degradeDrift: 0.5,
      degradeNoise: 0.13,
      degradeHp: 0.08,
      degradeLp: 0.44,
      degradeTone: 0.28,
      degradeSaturation: 0.24,
      degradeCorrosion: 0.13,
    },
  },
  mkiiMemory: {
    name: 'MKII Memory',
    description: 'Generation Loss MKII-style memory color: copy age, broad wow, gentle saturation, and less digital crush.',
    tags: ['degrade', 'generation', 'memory'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.4,
      degradeAge: 0.54,
      degradeGeneration: 0.6,
      degradeAlias: 0.04,
      degradeWow: 0.26,
      degradeFlutter: 0.13,
      degradeDrift: 0.46,
      degradeNoise: 0.09,
      degradeHp: 0.12,
      degradeLp: 0.5,
      degradeTone: 0.34,
      degradeSaturation: 0.25,
      degradeCorrosion: 0.1,
    },
  },
  aliasedZoia: {
    name: 'Aliased ZOIA',
    description: 'A more obvious Degenerate Gain lane with stepped sample-rate damage and corrosive high-mid grit.',
    tags: ['degrade', 'alias', 'zoia'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.46,
      degradeAge: 0.28,
      degradeGeneration: 0.16,
      degradeAlias: 0.72,
      degradeWow: 0.16,
      degradeFlutter: 0.76,
      degradeDrift: 0.28,
      degradeNoise: 0.1,
      degradeHp: 0.28,
      degradeLp: 0.42,
      degradeTone: 0.54,
      degradeSaturation: 0.34,
      degradeCorrosion: 0.56,
    },
  },
  vhsTracking: {
    name: 'VHS Tracking',
    description: 'Slow, unstable transport wear with a darker copy path and just enough alias to roughen the edges.',
    tags: ['degrade', 'vhs', 'tracking'],
    params: {
      degradeEnabled: true,
      degradeMix: 0.42,
      degradeAge: 0.72,
      degradeGeneration: 0.5,
      degradeAlias: 0.1,
      degradeWow: 0.5,
      degradeFlutter: 0.24,
      degradeDrift: 0.72,
      degradeNoise: 0.17,
      degradeHp: 0.16,
      degradeLp: 0.32,
      degradeTone: 0.22,
      degradeSaturation: 0.26,
      degradeCorrosion: 0.2,
    },
  },
};

export const DYNAMICS_SATURATION_PRESETS: Record<string, DynamicsPresetDefinition> = {
  cleanBypass: {
    name: 'Clean Bypass',
    description: 'Leaves the Dynamics master saturation stage off.',
    tags: ['saturation', 'clean', 'bypass'],
    params: {
      dynamicsSaturationEnabled: false,
      dynamicsSaturationMode: 'clean',
      dynamicsSaturationDrive: 0,
      dynamicsSaturationTone: 0.5,
    },
  },
  tapeGlow: {
    name: 'Tape Glow',
    description: 'Gentle tape-mode color for warming Character or Degrade without pushing the bus hard.',
    tags: ['saturation', 'tape', 'warm'],
    params: {
      dynamicsSaturationEnabled: true,
      dynamicsSaturationMode: 'tape',
      dynamicsSaturationDrive: 0.18,
      dynamicsSaturationTone: 0.46,
    },
  },
  tubeLift: {
    name: 'Tube Lift',
    description: 'A brighter tube-mode lift for presence and soft harmonic edge.',
    tags: ['saturation', 'tube', 'presence'],
    params: {
      dynamicsSaturationEnabled: true,
      dynamicsSaturationMode: 'tube',
      dynamicsSaturationDrive: 0.22,
      dynamicsSaturationTone: 0.58,
    },
  },
  wornTapeBus: {
    name: 'Worn Tape Bus',
    description: 'Darker tape saturation for old-media buses without adding Degrade noise or aliasing.',
    tags: ['saturation', 'tape', 'dark'],
    params: {
      dynamicsSaturationEnabled: true,
      dynamicsSaturationMode: 'tape',
      dynamicsSaturationDrive: 0.28,
      dynamicsSaturationTone: 0.34,
    },
  },
  pushedTube: {
    name: 'Pushed Tube',
    description: 'More obvious tube drive for controlled grit when the rest of Dynamics is clean.',
    tags: ['saturation', 'tube', 'drive'],
    params: {
      dynamicsSaturationEnabled: true,
      dynamicsSaturationMode: 'tube',
      dynamicsSaturationDrive: 0.38,
      dynamicsSaturationTone: 0.55,
    },
  },
};

export const DYNAMICS_END_CHAIN_PRESETS: Record<string, DynamicsPresetDefinition> = {
  glueBus: {
    name: 'Glue Bus',
    description: 'A balanced final compressor for holding the whole mix together without obvious pumping.',
    tags: ['compressor', 'glue', 'bus'],
    params: {
      endCompEnabled: true,
      endCompThreshold: -18,
      endCompKnee: 14,
      endCompRatio: 2,
      endCompAttackMs: 20,
      endCompReleaseMs: 180,
      endCompMakeup: 1.05,
      endCompMix: 0.76,
    },
  },
  clarityLift: {
    name: 'Clarity Lift',
    description: 'Gentle, slower compression with parallel mix and makeup for clear, polished output.',
    tags: ['compressor', 'clarity', 'polish'],
    params: {
      endCompEnabled: true,
      endCompThreshold: -24,
      endCompKnee: 18,
      endCompRatio: 1.6,
      endCompAttackMs: 34,
      endCompReleaseMs: 120,
      endCompMakeup: 1.12,
      endCompMix: 0.56,
    },
  },
  softCeiling: {
    name: 'Soft Ceiling',
    description: 'Faster bus control that catches peaks before the limiter while staying less hard than a brickwall.',
    tags: ['compressor', 'peaks', 'control'],
    params: {
      endCompEnabled: true,
      endCompThreshold: -12,
      endCompKnee: 10,
      endCompRatio: 3,
      endCompAttackMs: 5,
      endCompReleaseMs: 90,
      endCompMakeup: 1,
      endCompMix: 0.64,
    },
  },
  openMaster: {
    name: 'Open Master',
    description: 'Very light final-stage leveling for preserving transients and keeping the limiter relaxed.',
    tags: ['compressor', 'open', 'light'],
    params: {
      endCompEnabled: true,
      endCompThreshold: -30,
      endCompKnee: 24,
      endCompRatio: 1.25,
      endCompAttackMs: 50,
      endCompReleaseMs: 220,
      endCompMakeup: 1.08,
      endCompMix: 0.34,
    },
  },
};

export const DYNAMICS_SOURCE_PRESETS: Record<string, DynamicsPresetDefinition> = {
  ambientWaterGlue: {
    name: 'Ambient Water Glue',
    description: 'Abyss-style movement, clear tape wear, slow pad breathing, and gentle glue compression.',
    tags: ['dynamics', 'ambient', 'water', 'glue'],
    params: {
      dynamicsEnabled: true,
      ...DYNAMICS_SIDECHAIN_PRESETS.breathingPads!.params,
      ...DYNAMICS_CHARACTER_PRESETS.abyssWaterLpg!.params,
      ...DYNAMICS_DEGRADE_PRESETS.clearTape!.params,
      ...DYNAMICS_SATURATION_PRESETS.tapeGlow!.params,
      ...DYNAMICS_END_CHAIN_PRESETS.glueBus!.params,
    },
  },
  edmPumpAndPolish: {
    name: 'EDM Pump And Polish',
    description: 'Obvious kick wave ducking with clean motion and final clarity compression.',
    tags: ['dynamics', 'edm', 'pump', 'clarity'],
    params: {
      dynamicsEnabled: true,
      ...DYNAMICS_SIDECHAIN_PRESETS.edmWavePump!.params,
      ...DYNAMICS_CHARACTER_PRESETS.cleanMotion!.params,
      ...DYNAMICS_DEGRADE_PRESETS.clearTape!.params,
      ...DYNAMICS_SATURATION_PRESETS.cleanBypass!.params,
      ...DYNAMICS_END_CHAIN_PRESETS.clarityLift!.params,
    },
  },
  degenerateBus: {
    name: 'Degenerate Bus',
    description: 'Degenerate Gain-style corrosion feeding a peak-controlling final compressor.',
    tags: ['dynamics', 'degrade', 'corrosion'],
    params: {
      dynamicsEnabled: true,
      ...DYNAMICS_SIDECHAIN_PRESETS.granularPocket!.params,
      ...DYNAMICS_CHARACTER_PRESETS.shallowWaterDrift!.params,
      ...DYNAMICS_DEGRADE_PRESETS.degenerateGain!.params,
      ...DYNAMICS_SATURATION_PRESETS.pushedTube!.params,
      ...DYNAMICS_END_CHAIN_PRESETS.softCeiling!.params,
    },
  },
  generationLossWash: {
    name: 'Generation Loss Wash',
    description: 'Shallow-water motion into copied-media tape loss, with gentle ducking and glue at the end.',
    tags: ['dynamics', 'generation', 'warble', 'glue'],
    params: {
      dynamicsEnabled: true,
      ...DYNAMICS_SIDECHAIN_PRESETS.breathingPads!.params,
      ...DYNAMICS_CHARACTER_PRESETS.shallowWaterDrift!.params,
      ...DYNAMICS_DEGRADE_PRESETS.mkiiMemory!.params,
      ...DYNAMICS_SATURATION_PRESETS.tapeGlow!.params,
      ...DYNAMICS_END_CHAIN_PRESETS.glueBus!.params,
    },
  },
  vhsTrackingBus: {
    name: 'VHS Tracking Bus',
    description: 'Abyss-style envelope color through VHS tracking wear and a soft final ceiling.',
    tags: ['dynamics', 'vhs', 'abyss', 'control'],
    params: {
      dynamicsEnabled: true,
      ...DYNAMICS_SIDECHAIN_PRESETS.granularPocket!.params,
      ...DYNAMICS_CHARACTER_PRESETS.abyssWaterLpg!.params,
      ...DYNAMICS_DEGRADE_PRESETS.vhsTracking!.params,
      ...DYNAMICS_SATURATION_PRESETS.wornTapeBus!.params,
      ...DYNAMICS_END_CHAIN_PRESETS.softCeiling!.params,
    },
  },
};
