export const PRODUCT_VISUAL_TELEMETRY_HZ = 30;
export const PRODUCT_BACKGROUND_VISUAL_TELEMETRY_HZ = 5;
export const PRODUCT_DEBUG_PANEL_HZ = 10;
export const PRODUCT_RUNTIME_SLIDER_HZ = 30;

export function hzToIntervalMs(hz: number): number {
  return Math.max(1, Math.round(1000 / Math.max(1, hz)));
}

export const PRODUCT_VISUAL_TELEMETRY_INTERVAL_MS = hzToIntervalMs(PRODUCT_VISUAL_TELEMETRY_HZ);
export const PRODUCT_BACKGROUND_VISUAL_TELEMETRY_INTERVAL_MS = hzToIntervalMs(PRODUCT_BACKGROUND_VISUAL_TELEMETRY_HZ);
export const PRODUCT_DEBUG_PANEL_INTERVAL_MS = hzToIntervalMs(PRODUCT_DEBUG_PANEL_HZ);
export const PRODUCT_RUNTIME_SLIDER_INTERVAL_MS = hzToIntervalMs(PRODUCT_RUNTIME_SLIDER_HZ);
export const PRODUCT_RUNTIME_TELEMETRY_INTERVAL_MS = PRODUCT_DEBUG_PANEL_INTERVAL_MS;
export const PRODUCT_VISUAL_TELEMETRY_HIDDEN_INTERVAL_MS = PRODUCT_BACKGROUND_VISUAL_TELEMETRY_INTERVAL_MS;

export const PRODUCT_CPU_OVERLAY_REFRESH_MS = 2000;
export const PRODUCT_CORE_DEBUG_SUMMARY_REFRESH_MS = 500;
