#pragma once

#include <stdint.h>

#include "KesshoProductSchemaHash.h"

#define KESSHO_PRODUCT_ABI_VERSION 1
#define KESSHO_PRODUCT_SNAPSHOT_VERSION KESSHO_PRODUCT_GENERATED_SCHEMA_VERSION
#define KESSHO_PRODUCT_SNAPSHOT_SCHEMA_HASH KESSHO_PRODUCT_GENERATED_SCHEMA_HASH

typedef enum KesshoProductResult {
  KESSHO_PRODUCT_OK = 1,
  KESSHO_PRODUCT_ERROR_INVALID_ENGINE = -1,
  KESSHO_PRODUCT_ERROR_INVALID_SNAPSHOT = -2,
  KESSHO_PRODUCT_ERROR_UNSUPPORTED_SNAPSHOT_VERSION = -3,
  KESSHO_PRODUCT_ERROR_SCHEMA_HASH_MISMATCH = -4,
  KESSHO_PRODUCT_ERROR_SNAPSHOT_TOO_LARGE = -5,
  KESSHO_PRODUCT_ERROR_EVENT_QUEUE_FULL = -6,
  KESSHO_PRODUCT_ERROR_INVALID_EVENT = -7,
  KESSHO_PRODUCT_ERROR_INVALID_PARAM = -8,
  KESSHO_PRODUCT_ERROR_INVALID_SOURCE = -9,
  KESSHO_PRODUCT_ERROR_INVALID_SEQUENCER_LANE = -10,
  KESSHO_PRODUCT_ERROR_INVALID_ASSET_ID = -11,
  KESSHO_PRODUCT_ERROR_MISSING_ASSET = -12,
  KESSHO_PRODUCT_ERROR_ASSET_FORMAT_UNSUPPORTED = -13,
  KESSHO_PRODUCT_ERROR_RENDER_BLOCK_TOO_LARGE = -14,
  KESSHO_PRODUCT_ERROR_ALLOCATION_FAILURE = -15
} KesshoProductResult;

typedef enum KesshoProductSourceId {
  KESSHO_PRODUCT_SOURCE_PAD1 = 1,
  KESSHO_PRODUCT_SOURCE_PAD2 = 2,
  KESSHO_PRODUCT_SOURCE_LEAD1 = 3,
  KESSHO_PRODUCT_SOURCE_LEAD2 = 4,
  KESSHO_PRODUCT_SOURCE_DRUM = 5,
  KESSHO_PRODUCT_SOURCE_PIANO = 6,
  KESSHO_PRODUCT_SOURCE_SOUNDSCAPE = 7
} KesshoProductSourceId;

typedef enum KesshoProductStemId {
  KESSHO_PRODUCT_STEM_MASTER = 0,
  KESSHO_PRODUCT_STEM_PAD1 = 1,
  KESSHO_PRODUCT_STEM_PAD2 = 2,
  KESSHO_PRODUCT_STEM_LEAD1 = 3,
  KESSHO_PRODUCT_STEM_LEAD2 = 4,
  KESSHO_PRODUCT_STEM_DRUM = 5,
  KESSHO_PRODUCT_STEM_PIANO = 6,
  KESSHO_PRODUCT_STEM_SOUNDSCAPE = 7,
  KESSHO_PRODUCT_STEM_FX = 8
} KesshoProductStemId;

typedef enum KesshoProductTrigCondition {
  KESSHO_PRODUCT_TRIG_ALWAYS = 0,
  KESSHO_PRODUCT_TRIG_EVERY_2_BARS = 1,
  KESSHO_PRODUCT_TRIG_FIRST_BAR_OF_PHRASE = 2
} KesshoProductTrigCondition;

typedef enum KesshoProductAssetFlags {
  KESSHO_PRODUCT_ASSET_LOOP = 1u << 0,
  KESSHO_PRODUCT_ASSET_PIANO = 1u << 1,
  KESSHO_PRODUCT_ASSET_SOUNDSCAPE = 1u << 2
} KesshoProductAssetFlags;

typedef enum KesshoProductModulationRangeMode {
  KESSHO_PRODUCT_MODULATION_RANGE_OFF = 0,
  KESSHO_PRODUCT_MODULATION_RANGE_SAMPLE_HOLD = 1,
  KESSHO_PRODUCT_MODULATION_RANGE_RANDOM_WALK = 2
} KesshoProductModulationRangeMode;

typedef enum KesshoProductModulationRangeFlags {
  KESSHO_PRODUCT_MODULATION_RANGE_ACTIVE = 1u << 0
} KesshoProductModulationRangeFlags;

#define KESSHO_PRODUCT_DRUM_RANGE_TARGET_BASE 1000u
