#pragma once

#include <stdint.h>

#include "KesshoProductSchemaHash.h"

#define KESSHO_PRODUCT_ABI_VERSION 5
#define KESSHO_PRODUCT_SNAPSHOT_VERSION KESSHO_PRODUCT_GENERATED_SCHEMA_VERSION
#define KESSHO_PRODUCT_SNAPSHOT_SCHEMA_HASH KESSHO_PRODUCT_GENERATED_SCHEMA_HASH

typedef enum KesshoProductResult {
  KESSHO_PRODUCT_OK = 1,
  KESSHO_PRODUCT_ERROR_INVALID_ENGINE = -1,
  KESSHO_PRODUCT_ERROR_INVALID_SNAPSHOT = -2,
  KESSHO_PRODUCT_ERROR_UNSUPPORTED_SNAPSHOT_VERSION = -3,
  KESSHO_PRODUCT_ERROR_SCHEMA_HASH_MISMATCH = -4,
  KESSHO_PRODUCT_ERROR_SNAPSHOT_TOO_LARGE = -5,
  KESSHO_PRODUCT_ERROR_EVENT_QUEUE_FULL = -6,
  KESSHO_PRODUCT_ERROR_INVALID_EVENT = -7,
  KESSHO_PRODUCT_ERROR_INVALID_PARAM = -8,
  KESSHO_PRODUCT_ERROR_INVALID_SOURCE = -9,
  KESSHO_PRODUCT_ERROR_INVALID_SEQUENCER_LANE = -10,
  KESSHO_PRODUCT_ERROR_INVALID_ASSET_ID = -11,
  KESSHO_PRODUCT_ERROR_MISSING_ASSET = -12,
  KESSHO_PRODUCT_ERROR_ASSET_FORMAT_UNSUPPORTED = -13,
  KESSHO_PRODUCT_ERROR_RENDER_BLOCK_TOO_LARGE = -14,
  KESSHO_PRODUCT_ERROR_ALLOCATION_FAILURE = -15
} KesshoProductResult;

typedef enum KesshoProductSourceId {
  KESSHO_PRODUCT_SOURCE_PAD1 = 1,
  KESSHO_PRODUCT_SOURCE_PAD2 = 2,
  KESSHO_PRODUCT_SOURCE_LEAD1 = 3,
  KESSHO_PRODUCT_SOURCE_LEAD2 = 4,
  KESSHO_PRODUCT_SOURCE_DRUM = 5,
  KESSHO_PRODUCT_SOURCE_PIANO = 6,
  KESSHO_PRODUCT_SOURCE_SOUNDSCAPE = 7
} KesshoProductSourceId;

typedef enum KesshoProductStemId {
  KESSHO_PRODUCT_STEM_MASTER = 0,
  KESSHO_PRODUCT_STEM_PAD1 = 1,
  KESSHO_PRODUCT_STEM_PAD2 = 2,
  KESSHO_PRODUCT_STEM_LEAD1 = 3,
  KESSHO_PRODUCT_STEM_LEAD2 = 4,
  KESSHO_PRODUCT_STEM_DRUM = 5,
  KESSHO_PRODUCT_STEM_PIANO = 6,
  KESSHO_PRODUCT_STEM_SOUNDSCAPE = 7,
  KESSHO_PRODUCT_STEM_FX = 8
} KesshoProductStemId;

typedef enum KesshoProductGraphTapId {
  KESSHO_PRODUCT_GRAPH_TAP_REVERB_INPUT = 0,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_A_INPUT = 1,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_B_INPUT = 2,
  KESSHO_PRODUCT_GRAPH_TAP_GRANULAR_INPUT = 3,
  KESSHO_PRODUCT_GRAPH_TAP_DYNAMICS_INPUT = 4,
  KESSHO_PRODUCT_GRAPH_TAP_DYNAMICS_OUTPUT = 5,
  KESSHO_PRODUCT_GRAPH_TAP_MASTER_PRE_LIMITER = 6,
  KESSHO_PRODUCT_GRAPH_TAP_MASTER_POST_LIMITER = 7,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_A_OUTPUT = 8,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_A_REVERB_SEND = 9,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_A_TO_DELAY_B_SEND = 10,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_A_TO_GRANULAR_SEND = 11,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_B_OUTPUT = 12,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_B_REVERB_SEND = 13,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_B_TO_DELAY_A_SEND = 14,
  KESSHO_PRODUCT_GRAPH_TAP_DELAY_B_TO_GRANULAR_SEND = 15,
  KESSHO_PRODUCT_GRAPH_TAP_GRANULAR_OUTPUT = 16,
  KESSHO_PRODUCT_GRAPH_TAP_GRANULAR_REVERB_SEND = 17,
  KESSHO_PRODUCT_GRAPH_TAP_GRANULAR_TO_DELAY_A_SEND = 18,
  KESSHO_PRODUCT_GRAPH_TAP_GRANULAR_TO_DELAY_B_SEND = 19,
  KESSHO_PRODUCT_GRAPH_TAP_REVERB_PRECONDITIONER_OUTPUT = 20,
  KESSHO_PRODUCT_GRAPH_TAP_REVERB_OUTPUT = 21,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PAD1_INPUT = 22,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PAD1_OUTPUT = 23,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PAD1_GAIN_TRACE = 24,
  KESSHO_PRODUCT_GRAPH_TAP_SPECTRAL_FREEZE_INPUT = 25,
  KESSHO_PRODUCT_GRAPH_TAP_SPECTRAL_FREEZE_OUTPUT = 26,
  KESSHO_PRODUCT_GRAPH_TAP_DRUM_DRY = 27,
  KESSHO_PRODUCT_GRAPH_TAP_DRUM_REVERB_SEND = 28,
  KESSHO_PRODUCT_GRAPH_TAP_DRUM_DELAY_A_SEND = 29,
  KESSHO_PRODUCT_GRAPH_TAP_DRUM_DELAY_B_SEND = 30,
  KESSHO_PRODUCT_GRAPH_TAP_DRUM_GRANULAR_SEND = 31,
  KESSHO_PRODUCT_GRAPH_TAP_PAD1_DRY = 32,
  KESSHO_PRODUCT_GRAPH_TAP_PAD1_REVERB_SEND = 33,
  KESSHO_PRODUCT_GRAPH_TAP_PAD1_DELAY_A_SEND = 34,
  KESSHO_PRODUCT_GRAPH_TAP_PAD1_DELAY_B_SEND = 35,
  KESSHO_PRODUCT_GRAPH_TAP_PAD1_GRANULAR_SEND = 36,
  KESSHO_PRODUCT_GRAPH_TAP_PAD2_DRY = 37,
  KESSHO_PRODUCT_GRAPH_TAP_PAD2_REVERB_SEND = 38,
  KESSHO_PRODUCT_GRAPH_TAP_PAD2_DELAY_A_SEND = 39,
  KESSHO_PRODUCT_GRAPH_TAP_PAD2_DELAY_B_SEND = 40,
  KESSHO_PRODUCT_GRAPH_TAP_PAD2_GRANULAR_SEND = 41,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD1_DRY = 42,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD1_REVERB_SEND = 43,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD1_DELAY_A_SEND = 44,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD1_DELAY_B_SEND = 45,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD1_GRANULAR_SEND = 46,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD2_DRY = 47,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD2_REVERB_SEND = 48,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD2_DELAY_A_SEND = 49,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD2_DELAY_B_SEND = 50,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD2_GRANULAR_SEND = 51,
  KESSHO_PRODUCT_GRAPH_TAP_PIANO_DRY = 52,
  KESSHO_PRODUCT_GRAPH_TAP_PIANO_REVERB_SEND = 53,
  KESSHO_PRODUCT_GRAPH_TAP_PIANO_DELAY_A_SEND = 54,
  KESSHO_PRODUCT_GRAPH_TAP_PIANO_DELAY_B_SEND = 55,
  KESSHO_PRODUCT_GRAPH_TAP_PIANO_GRANULAR_SEND = 56,
  KESSHO_PRODUCT_GRAPH_TAP_DIFFUSE_INPUT = 57,
  KESSHO_PRODUCT_GRAPH_TAP_DIFFUSE_OUTPUT = 58,
  KESSHO_PRODUCT_GRAPH_TAP_DIFFUSE_REVERB_SEND = 59,
  KESSHO_PRODUCT_GRAPH_TAP_PAD1_DIFFUSE_SEND = 60,
  KESSHO_PRODUCT_GRAPH_TAP_PAD2_DIFFUSE_SEND = 61,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD1_DIFFUSE_SEND = 62,
  KESSHO_PRODUCT_GRAPH_TAP_LEAD2_DIFFUSE_SEND = 63,
  KESSHO_PRODUCT_GRAPH_TAP_PIANO_DIFFUSE_SEND = 64,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_OCEAN_DRY = 65,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_WATER_DRY = 66,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_INSECTS_DRY = 67,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_NATURE_DRY = 68,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_OCEAN_REVERB_SEND = 69,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_OCEAN_DELAY_A_SEND = 70,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_OCEAN_DELAY_B_SEND = 71,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_OCEAN_GRANULAR_SEND = 72,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_WATER_REVERB_SEND = 73,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_WATER_DELAY_A_SEND = 74,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_WATER_DELAY_B_SEND = 75,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_WATER_GRANULAR_SEND = 76,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_INSECTS_REVERB_SEND = 77,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_INSECTS_DELAY_A_SEND = 78,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_INSECTS_DELAY_B_SEND = 79,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_INSECTS_GRANULAR_SEND = 80,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_NATURE_REVERB_SEND = 81,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_NATURE_DELAY_A_SEND = 82,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_NATURE_DELAY_B_SEND = 83,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_NATURE_GRANULAR_SEND = 84,
  KESSHO_PRODUCT_GRAPH_TAP_SOUNDSCAPE_STEM = 85,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PAD2_INPUT = 86,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PAD2_OUTPUT = 87,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PAD2_GAIN_TRACE = 88,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_LEAD1_INPUT = 89,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_LEAD1_OUTPUT = 90,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_LEAD1_GAIN_TRACE = 91,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_LEAD2_INPUT = 92,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_LEAD2_OUTPUT = 93,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_LEAD2_GAIN_TRACE = 94,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PIANO_INPUT = 95,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PIANO_OUTPUT = 96,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_PIANO_GAIN_TRACE = 97,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_GRANULAR_INPUT = 98,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_GRANULAR_OUTPUT = 99,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_GRANULAR_GAIN_TRACE = 100,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_DELAY_A_INPUT = 101,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_DELAY_A_OUTPUT = 102,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_DELAY_A_GAIN_TRACE = 103,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_DELAY_B_INPUT = 104,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_DELAY_B_OUTPUT = 105,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_DELAY_B_GAIN_TRACE = 106,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_REVERB_INPUT = 107,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_REVERB_OUTPUT = 108,
  KESSHO_PRODUCT_GRAPH_TAP_SIDECHAIN_REVERB_GAIN_TRACE = 109,
  KESSHO_PRODUCT_GRAPH_TAP_COUNT = 110
} KesshoProductGraphTapId;

typedef enum KesshoProductTrigCondition {
  KESSHO_PRODUCT_TRIG_ALWAYS = 0,
  KESSHO_PRODUCT_TRIG_EVERY_2_BARS = 1,
  KESSHO_PRODUCT_TRIG_FIRST_BAR_OF_PHRASE = 2
} KesshoProductTrigCondition;

typedef enum KesshoProductAssetFlags {
  KESSHO_PRODUCT_ASSET_LOOP = 1u << 0,
  KESSHO_PRODUCT_ASSET_PIANO = 1u << 1,
  KESSHO_PRODUCT_ASSET_SOUNDSCAPE = 1u << 2
} KesshoProductAssetFlags;

typedef enum KesshoProductModulationRangeMode {
  KESSHO_PRODUCT_MODULATION_RANGE_OFF = 0,
  KESSHO_PRODUCT_MODULATION_RANGE_SAMPLE_HOLD = 1,
  KESSHO_PRODUCT_MODULATION_RANGE_RANDOM_WALK = 2
} KesshoProductModulationRangeMode;

typedef enum KesshoProductModulationRangeFlags {
  KESSHO_PRODUCT_MODULATION_RANGE_ACTIVE = 1u << 0,
  KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_DELAY_A = 1u << 8,
  KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_DELAY_B = 1u << 9,
  KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_GRANULAR = 1u << 10,
  KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_REVERB = 1u << 11,
  KESSHO_PRODUCT_MODULATION_RANGE_RANDOM_WALK_GLOBAL = 1u << 12,
  KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_MASK =
      KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_DELAY_A |
      KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_DELAY_B |
      KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_GRANULAR |
      KESSHO_PRODUCT_MODULATION_RANGE_TRIGGER_REVERB
} KesshoProductModulationRangeFlags;

#define KESSHO_PRODUCT_MODULATION_RANGE_RANDOM_WALK_SPEED_SHIFT 16u
#define KESSHO_PRODUCT_MODULATION_RANGE_RANDOM_WALK_SPEED_SCALE 1000u
#define KESSHO_PRODUCT_MODULATION_RANGE_RANDOM_WALK_SPEED_MASK (0xffffu << KESSHO_PRODUCT_MODULATION_RANGE_RANDOM_WALK_SPEED_SHIFT)

#define KESSHO_PRODUCT_DRUM_RANGE_TARGET_BASE 1000u
