#pragma once

#include <stdint.h>

#include "KesshoProductTypes.h"

#define KESSHO_PRODUCT_INTERACTION_VERSION 1u
#define KESSHO_PRODUCT_INTERACTION_SOURCE_COUNT 10u
#define KESSHO_PRODUCT_INTERACTION_SOURCE_MASK_ALL ((1u << KESSHO_PRODUCT_INTERACTION_SOURCE_COUNT) - 1u)
#define KESSHO_PRODUCT_INTERACTION_EVENT_CAPACITY 256u

typedef enum KesshoProductInteractionParentId {
  KESSHO_PRODUCT_INTERACTION_PARENT_NONE = 0,
  KESSHO_PRODUCT_INTERACTION_PARENT_MASTER = 1,
  KESSHO_PRODUCT_INTERACTION_PARENT_SYNTHS = 2,
  KESSHO_PRODUCT_INTERACTION_PARENT_DRUMS = 3,
  KESSHO_PRODUCT_INTERACTION_PARENT_SAMPLES = 4,
  KESSHO_PRODUCT_INTERACTION_PARENT_SOUNDSCAPE = 5,
  KESSHO_PRODUCT_INTERACTION_PARENT_FX = 6,
  KESSHO_PRODUCT_INTERACTION_PARENT_TRANSPORT = 7,
  KESSHO_PRODUCT_INTERACTION_PARENT_INTERACTION = 8
} KesshoProductInteractionParentId;

typedef enum KesshoProductInteractionChildId {
  KESSHO_PRODUCT_INTERACTION_CHILD_NONE = 0,
  KESSHO_PRODUCT_INTERACTION_CHILD_PAD1 = 1,
  KESSHO_PRODUCT_INTERACTION_CHILD_PAD2 = 2,
  KESSHO_PRODUCT_INTERACTION_CHILD_LEAD1 = 3,
  KESSHO_PRODUCT_INTERACTION_CHILD_LEAD2 = 4,
  KESSHO_PRODUCT_INTERACTION_CHILD_DRUM = 5,
  KESSHO_PRODUCT_INTERACTION_CHILD_SAMPLE1 = 6,
  KESSHO_PRODUCT_INTERACTION_CHILD_SOUNDSCAPE = 7,
  KESSHO_PRODUCT_INTERACTION_CHILD_SAMPLE2 = 8,
  KESSHO_PRODUCT_INTERACTION_CHILD_DELAY_A = 9,
  KESSHO_PRODUCT_INTERACTION_CHILD_DELAY_B = 10,
  KESSHO_PRODUCT_INTERACTION_CHILD_GRANULAR = 11,
  KESSHO_PRODUCT_INTERACTION_CHILD_REVERB = 12,
  KESSHO_PRODUCT_INTERACTION_CHILD_DEGRADE = 13
} KesshoProductInteractionChildId;

typedef enum KesshoProductInteractionTapId {
  KESSHO_PRODUCT_INTERACTION_TAP_NONE = 0,
  KESSHO_PRODUCT_INTERACTION_TAP_PRE_SOURCE = 1,
  KESSHO_PRODUCT_INTERACTION_TAP_POST_SOURCE = 2,
  KESSHO_PRODUCT_INTERACTION_TAP_POST_FX = 3,
  KESSHO_PRODUCT_INTERACTION_TAP_MASTER = 4
} KesshoProductInteractionTapId;

typedef enum KesshoProductInteractionOriginId {
  KESSHO_PRODUCT_INTERACTION_ORIGIN_UNKNOWN = 0,
  KESSHO_PRODUCT_INTERACTION_ORIGIN_SEQUENCER = 1,
  KESSHO_PRODUCT_INTERACTION_ORIGIN_RANDOM_TIMING = 2,
  KESSHO_PRODUCT_INTERACTION_ORIGIN_ARRANGEMENT = 3,
  KESSHO_PRODUCT_INTERACTION_ORIGIN_MANUAL = 4,
  KESSHO_PRODUCT_INTERACTION_ORIGIN_MIDI = 5,
  KESSHO_PRODUCT_INTERACTION_ORIGIN_INTERACTION = 6,
  KESSHO_PRODUCT_INTERACTION_ORIGIN_SYSTEM = 7
} KesshoProductInteractionOriginId;

typedef enum KesshoProductInteractionEventType {
  KESSHO_PRODUCT_INTERACTION_EVENT_NONE = 0,
  KESSHO_PRODUCT_INTERACTION_EVENT_TRANSPORT_STARTED = 1,
  KESSHO_PRODUCT_INTERACTION_EVENT_TRANSPORT_STOPPED = 2,
  KESSHO_PRODUCT_INTERACTION_EVENT_TRANSPORT_BEAT = 3,
  KESSHO_PRODUCT_INTERACTION_EVENT_TRANSPORT_BAR = 4,
  KESSHO_PRODUCT_INTERACTION_EVENT_TRANSPORT_PHRASE = 5,
  KESSHO_PRODUCT_INTERACTION_EVENT_VOICE_TRIGGERED = 6,
  KESSHO_PRODUCT_INTERACTION_EVENT_DRUM_TRIGGERED = 7,
  KESSHO_PRODUCT_INTERACTION_EVENT_SAMPLE_TRIGGERED = 8,
  KESSHO_PRODUCT_INTERACTION_EVENT_TEXTURE_STARTED = 9,
  KESSHO_PRODUCT_INTERACTION_EVENT_TEXTURE_ENDED = 10,
  KESSHO_PRODUCT_INTERACTION_EVENT_SAMPLE_HOLD_TRIGGERED = 11,
  KESSHO_PRODUCT_INTERACTION_EVENT_ANALYSIS_ONSET = 12,
  KESSHO_PRODUCT_INTERACTION_EVENT_EFFECT_STARTED = 13,
  KESSHO_PRODUCT_INTERACTION_EVENT_EFFECT_RELEASED = 14,
  KESSHO_PRODUCT_INTERACTION_EVENT_EFFECT_REJECTED = 15,
  KESSHO_PRODUCT_INTERACTION_EVENT_MORPH_STARTED = 16,
  KESSHO_PRODUCT_INTERACTION_EVENT_MORPH_COMPLETED = 17
} KesshoProductInteractionEventType;

typedef enum KesshoProductInteractionSignalType {
  KESSHO_PRODUCT_INTERACTION_SIGNAL_NONE = 0,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_ANALYSIS_ENVELOPE = 1,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_ANALYSIS_PEAK = 2,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_ANALYSIS_RMS = 3,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_ANALYSIS_ONSET_STRENGTH = 4,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_SYNTHESIS_ENVELOPE = 5,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_MODULATION_VALUE = 6,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_TRANSPORT_PHASE = 7,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_POINTER_X = 8,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_POINTER_Y = 9,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_POINTER_VELOCITY = 10,
  KESSHO_PRODUCT_INTERACTION_SIGNAL_DRAG_VELOCITY = 11
} KesshoProductInteractionSignalType;

typedef enum KesshoProductInteractionCommandType {
  KESSHO_PRODUCT_INTERACTION_COMMAND_NONE = 0,
  KESSHO_PRODUCT_INTERACTION_COMMAND_PERFORMANCE_RATCHET = 1,
  KESSHO_PRODUCT_INTERACTION_COMMAND_PERFORMANCE_REVERSE = 2,
  KESSHO_PRODUCT_INTERACTION_COMMAND_PERFORMANCE_FREEZE = 3,
  KESSHO_PRODUCT_INTERACTION_COMMAND_PERFORMANCE_FILTER = 4,
  KESSHO_PRODUCT_INTERACTION_COMMAND_PERFORMANCE_DELAY = 5,
  KESSHO_PRODUCT_INTERACTION_COMMAND_PERFORMANCE_GRANULAR = 6,
  KESSHO_PRODUCT_INTERACTION_COMMAND_PRESET_MORPH = 7,
  KESSHO_PRODUCT_INTERACTION_COMMAND_TRANSPORT_PLAY = 8,
  KESSHO_PRODUCT_INTERACTION_COMMAND_TRANSPORT_STOP = 9
} KesshoProductInteractionCommandType;

typedef enum KesshoProductInteractionDemand {
  KESSHO_PRODUCT_INTERACTION_DEMAND_EVENTS = 1u << 0u,
  KESSHO_PRODUCT_INTERACTION_DEMAND_ENVELOPE = 1u << 1u,
  KESSHO_PRODUCT_INTERACTION_DEMAND_PEAK = 1u << 2u,
  KESSHO_PRODUCT_INTERACTION_DEMAND_RMS = 1u << 3u,
  KESSHO_PRODUCT_INTERACTION_DEMAND_ONSET = 1u << 4u,
  KESSHO_PRODUCT_INTERACTION_DEMAND_TRANSPORT = 1u << 5u,
  KESSHO_PRODUCT_INTERACTION_DEMAND_MODULATION = 1u << 6u,
  KESSHO_PRODUCT_INTERACTION_DEMAND_ALL = (1u << 7u) - 1u
} KesshoProductInteractionDemand;

typedef struct KesshoProductInteractionEvent {
  uint32_t type, parent, child, origin, tap, flags;
  uint64_t sample_frame;
  float value, strength;
} KesshoProductInteractionEvent;

typedef struct KesshoProductInteractionSignal {
  uint32_t type, parent, child, tap, flags;
  uint64_t sample_frame;
  float value;
} KesshoProductInteractionSignal;

typedef struct KesshoProductInteractionCommand {
  uint32_t type, target_parent, target_child, origin, flags;
  uint64_t sample_frame;
  float value;
} KesshoProductInteractionCommand;

typedef struct KesshoProductInteractionSignalSnapshot {
  uint32_t version;
  uint32_t revision;
  uint32_t demand_mask;
  uint32_t source_mask;
  uint32_t valid_source_mask;
  uint64_t sample_frame;
  float envelope[KESSHO_PRODUCT_INTERACTION_SOURCE_COUNT];
  float peak[KESSHO_PRODUCT_INTERACTION_SOURCE_COUNT];
  float rms[KESSHO_PRODUCT_INTERACTION_SOURCE_COUNT];
  float onset_strength[KESSHO_PRODUCT_INTERACTION_SOURCE_COUNT];
} KesshoProductInteractionSignalSnapshot;

#ifdef __cplusplus
#include <type_traits>
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_PAD1) == uint32_t(KESSHO_PRODUCT_SOURCE_PAD1));
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_PAD2) == uint32_t(KESSHO_PRODUCT_SOURCE_PAD2));
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_LEAD1) == uint32_t(KESSHO_PRODUCT_SOURCE_LEAD1));
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_LEAD2) == uint32_t(KESSHO_PRODUCT_SOURCE_LEAD2));
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_DRUM) == uint32_t(KESSHO_PRODUCT_SOURCE_DRUM));
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_SAMPLE1) == uint32_t(KESSHO_PRODUCT_SOURCE_SAMPLE1));
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_SOUNDSCAPE) == uint32_t(KESSHO_PRODUCT_SOURCE_SOUNDSCAPE));
static_assert(uint32_t(KESSHO_PRODUCT_INTERACTION_CHILD_SAMPLE2) == uint32_t(KESSHO_PRODUCT_SOURCE_SAMPLE2));
static_assert(std::is_standard_layout_v<KesshoProductInteractionEvent>);
static_assert(std::is_trivially_copyable_v<KesshoProductInteractionEvent>);
static_assert(std::is_standard_layout_v<KesshoProductInteractionSignal>);
static_assert(std::is_trivially_copyable_v<KesshoProductInteractionSignal>);
static_assert(std::is_standard_layout_v<KesshoProductInteractionCommand>);
static_assert(std::is_trivially_copyable_v<KesshoProductInteractionCommand>);
static_assert(std::is_standard_layout_v<KesshoProductInteractionSignalSnapshot>);
static_assert(std::is_trivially_copyable_v<KesshoProductInteractionSignalSnapshot>);
#endif
