#pragma once

#include <stdint.h>

#include "KesshoCore/KesshoProductTypes.h"
#include "KesshoProductEventIds.h"

typedef enum KesshoProductEventKind {
  KESSHO_PRODUCT_EVENT_KIND_SET_PARAM = KESSHO_PRODUCT_EVENT_SET_PARAM_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_TRANSPORT = KESSHO_PRODUCT_EVENT_SET_TRANSPORT_ID,
  KESSHO_PRODUCT_EVENT_KIND_START = KESSHO_PRODUCT_EVENT_START_ID,
  KESSHO_PRODUCT_EVENT_KIND_STOP = KESSHO_PRODUCT_EVENT_STOP_ID,
  KESSHO_PRODUCT_EVENT_KIND_RESET_TRANSPORT = KESSHO_PRODUCT_EVENT_RESET_TRANSPORT_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_SEQUENCER_STEP = KESSHO_PRODUCT_EVENT_SET_SEQUENCER_STEP_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_SEQUENCER_LANE = KESSHO_PRODUCT_EVENT_SET_SEQUENCER_LANE_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_JOURNEY_STATE = KESSHO_PRODUCT_EVENT_SET_JOURNEY_STATE_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_SOURCE_ENABLED = KESSHO_PRODUCT_EVENT_SET_SOURCE_ENABLED_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_SOURCE_PRESET = KESSHO_PRODUCT_EVENT_SET_SOURCE_PRESET_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_SOURCE_OVERRIDE = KESSHO_PRODUCT_EVENT_SET_SOURCE_OVERRIDE_ID,
  KESSHO_PRODUCT_EVENT_KIND_MANUAL_NOTE_ON = KESSHO_PRODUCT_EVENT_MANUAL_NOTE_ON_ID,
  KESSHO_PRODUCT_EVENT_KIND_MANUAL_NOTE_OFF = KESSHO_PRODUCT_EVENT_MANUAL_NOTE_OFF_ID,
  KESSHO_PRODUCT_EVENT_KIND_MIDI_EVENT = KESSHO_PRODUCT_EVENT_MIDI_EVENT_ID,
  KESSHO_PRODUCT_EVENT_KIND_TRIGGER_DRUM_VOICE = KESSHO_PRODUCT_EVENT_TRIGGER_DRUM_VOICE_ID,
  KESSHO_PRODUCT_EVENT_KIND_REQUEST_TELEMETRY = KESSHO_PRODUCT_EVENT_REQUEST_TELEMETRY_ID,
  KESSHO_PRODUCT_EVENT_KIND_START_JOURNEY_MORPH_CLOCK = KESSHO_PRODUCT_EVENT_START_JOURNEY_MORPH_CLOCK_ID,
  KESSHO_PRODUCT_EVENT_KIND_STOP_JOURNEY_MORPH_CLOCK = KESSHO_PRODUCT_EVENT_STOP_JOURNEY_MORPH_CLOCK_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_HARMONY_ROOT = KESSHO_PRODUCT_EVENT_SET_HARMONY_ROOT_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_SCALE = KESSHO_PRODUCT_EVENT_SET_SCALE_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_SEED = KESSHO_PRODUCT_EVENT_SET_SEED_ID,
  KESSHO_PRODUCT_EVENT_KIND_RESET_RNG = KESSHO_PRODUCT_EVENT_RESET_RNG_ID,
  KESSHO_PRODUCT_EVENT_KIND_SET_MODULATION_RANGE = KESSHO_PRODUCT_EVENT_SET_MODULATION_RANGE_ID,
  KESSHO_PRODUCT_EVENT_KIND_RESET_SEQUENCER_LANE_HOME = KESSHO_PRODUCT_EVENT_RESET_SEQUENCER_LANE_HOME_ID,
  KESSHO_PRODUCT_EVENT_KIND_DICE_SEQUENCER_LANE = KESSHO_PRODUCT_EVENT_DICE_SEQUENCER_LANE_ID,
  KESSHO_PRODUCT_EVENT_KIND_ANCHOR_WALKER_PERFORMANCE = KESSHO_PRODUCT_EVENT_ANCHOR_WALKER_PERFORMANCE_ID,
  KESSHO_PRODUCT_EVENT_KIND_GENERATED_SEQUENCER_CAPTURE = KESSHO_PRODUCT_EVENT_GENERATED_SEQUENCER_CAPTURE_ID
} KesshoProductEventKind;

#define KESSHO_PRODUCT_SEQUENCER_SYNTH 1u
#define KESSHO_PRODUCT_SEQUENCER_DRUM 2u
#define KESSHO_PRODUCT_SOURCE_OVERRIDE_SET_SLOT (1u << 0)
#define KESSHO_PRODUCT_SOURCE_OVERRIDE_COMMIT (1u << 1)
#define KESSHO_PRODUCT_SOURCE_OVERRIDE_MORPH_ANCHORED (1u << 2)
#define KESSHO_PRODUCT_STEP_TOGGLE_ACTIVE (1u << 0)
#define KESSHO_PRODUCT_STEP_TOGGLE_CLEAR_LANE (1u << 1)
#define KESSHO_PRODUCT_STEP_TOGGLE_CLEAR_FIELD (1u << 2)
#define KESSHO_PRODUCT_STEP_TOGGLE_RANGE_VALUE (1u << 3)
#define KESSHO_PRODUCT_STEP_FIELD_SHIFT 8u
#define KESSHO_PRODUCT_STEP_FIELD_MASK (15u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_TRIGGER (0u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_PROBABILITY (1u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_RATCHET (2u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_TRIG_CONDITION (3u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_MIDI_NOTE (4u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_EXPRESSION (5u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_MORPH (6u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_DISTANCE (7u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_SUBLANE_CONFIG (8u << KESSHO_PRODUCT_STEP_FIELD_SHIFT)
#define KESSHO_PRODUCT_STEP_FIELD_ID_MASK 15u
#define KESSHO_PRODUCT_SUBLANE_DIRECTION_FORWARD 0u
#define KESSHO_PRODUCT_SUBLANE_DIRECTION_REVERSE 1u
#define KESSHO_PRODUCT_SUBLANE_DIRECTION_PINGPONG 2u
#define KESSHO_PRODUCT_DICE_FIELD_TRIGGER (1u << 0)
#define KESSHO_PRODUCT_DICE_FIELD_PROBABILITY (1u << 1)
#define KESSHO_PRODUCT_DICE_FIELD_RATCHET (1u << 2)
#define KESSHO_PRODUCT_DICE_FIELD_MIDI_NOTE (1u << 3)
#define KESSHO_PRODUCT_DICE_FIELD_EXPRESSION (1u << 4)
#define KESSHO_PRODUCT_DICE_FIELD_MORPH (1u << 5)
#define KESSHO_PRODUCT_DICE_FIELD_DISTANCE (1u << 6)
#define KESSHO_PRODUCT_DICE_FIELD_SWING (1u << 7)
#define KESSHO_PRODUCT_DICE_FIELD_ALL \
  (KESSHO_PRODUCT_DICE_FIELD_TRIGGER | KESSHO_PRODUCT_DICE_FIELD_PROBABILITY | \
   KESSHO_PRODUCT_DICE_FIELD_RATCHET | KESSHO_PRODUCT_DICE_FIELD_MIDI_NOTE | \
   KESSHO_PRODUCT_DICE_FIELD_EXPRESSION | KESSHO_PRODUCT_DICE_FIELD_MORPH | \
   KESSHO_PRODUCT_DICE_FIELD_DISTANCE)
#define KESSHO_PRODUCT_EVOLVE_METHOD_ROTATE_DRIFT (1u << 8)
#define KESSHO_PRODUCT_EVOLVE_METHOD_SWING_DRIFT (1u << 9)
#define KESSHO_PRODUCT_EVOLVE_METHOD_PROB_DRIFT (1u << 10)
#define KESSHO_PRODUCT_EVOLVE_METHOD_GHOST_NOTES (1u << 11)
#define KESSHO_PRODUCT_EVOLVE_METHOD_RATCHET_SPRAY (1u << 12)
#define KESSHO_PRODUCT_EVOLVE_METHOD_HIT_DRIFT (1u << 13)
#define KESSHO_PRODUCT_EVOLVE_METHOD_PITCH_WALK (1u << 14)
#define KESSHO_PRODUCT_EVOLVE_METHOD_VALUE_DRIFT (1u << 15)
#define KESSHO_PRODUCT_EVOLVE_METHOD_VALUE_SCRAMBLE (1u << 16)
#define KESSHO_PRODUCT_EVOLVE_METHOD_VALUE_WIDEN (1u << 17)
#define KESSHO_PRODUCT_EVOLVE_METHOD_SUBLANE_LENGTH_DRIFT (1u << 18)
#define KESSHO_PRODUCT_EVOLVE_METHOD_SUBLANE_DIRECTION_FLIP (1u << 19)
#define KESSHO_PRODUCT_EVOLVE_METHOD_TRIGGER_TOGGLE (1u << 20)
#define KESSHO_PRODUCT_EVOLVE_MANUAL_COMMIT (1u << 28)
#define KESSHO_PRODUCT_EVOLVE_MUTATION_STRICT (1u << 29)
#define KESSHO_PRODUCT_EVOLVE_RNG_STREAM (1u << 30)
#define KESSHO_PRODUCT_EVOLVE_MODE_PARITY (1u << 31)
#define KESSHO_PRODUCT_EVOLVE_TENSION_PARAM_SCALE 1000u
#define KESSHO_PRODUCT_ANCHOR_WALKER_ACTION_GESTURE_TAP 1u
#define KESSHO_PRODUCT_ANCHOR_WALKER_ACTION_GESTURE_DOWN 2u
#define KESSHO_PRODUCT_ANCHOR_WALKER_ACTION_GESTURE_UP 3u
#define KESSHO_PRODUCT_ANCHOR_WALKER_ACTION_RESET_CURSOR 4u
#define KESSHO_PRODUCT_ANCHOR_WALKER_ACTION_SET_MANUAL_ANCHOR 5u
#define KESSHO_PRODUCT_ANCHOR_WALKER_BOUNDARY_NONE 0u
#define KESSHO_PRODUCT_ANCHOR_WALKER_BOUNDARY_FOLD_TOP 1u
#define KESSHO_PRODUCT_ANCHOR_WALKER_BOUNDARY_FOLD_BOTTOM 2u
#define KESSHO_PRODUCT_ANCHOR_WALKER_BOUNDARY_WRAP_TOP 3u
#define KESSHO_PRODUCT_ANCHOR_WALKER_BOUNDARY_WRAP_BOTTOM 4u
#define KESSHO_PRODUCT_ANCHOR_WALKER_BOUNDARY_CLAMP_TOP 5u
#define KESSHO_PRODUCT_ANCHOR_WALKER_BOUNDARY_CLAMP_BOTTOM 6u

typedef struct KesshoProductEvent {
  uint32_t sample_offset;
  uint32_t event_kind;
  uint32_t target_id;
  uint32_t index;
  uint32_t param_id;
  float value;
  float value2;
  float value3;
  float value4;
  uint32_t flags;
} KesshoProductEvent;

typedef struct KesshoSequencerEvent {
  uint32_t sample_offset;
  uint16_t source_id;
  uint16_t lane_id;
  uint16_t step_id;
  uint16_t event_kind;
  float frequency_hz;
  float midi_note;
  float velocity;
  float hold_seconds;
  float morph;
  float distance;
  float expression;
  float send_reverb;
  float send_delay_a;
  float send_delay_b;
  float send_granular;
  uint32_t flags;
} KesshoSequencerEvent;
