import type { CSSProperties } from 'react';

export const appStyles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '10px',
  } as CSSProperties,
  header: {
    textAlign: 'center' as const,
    marginBottom: '20px',
  } as CSSProperties,
  title: {
    fontSize: '2rem',
    fontWeight: 'bold',
    background: 'linear-gradient(90deg, #a5c4d4, #e8f4f8, #a5c4d4)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: '10px',
    textShadow: '0 0 30px rgba(165, 196, 212, 0.3)',
  } as CSSProperties,
  subtitle: {
    color: '#7a9aaf',
    fontSize: '0.9rem',
  } as CSSProperties,
  controls: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'center',
    marginBottom: '30px',
    paddingTop: 'calc(12px + env(safe-area-inset-top))',
    flexWrap: 'wrap' as const,
  } as CSSProperties,
  button: {
    padding: '10px 20px',
    fontSize: '0.9rem',
    fontWeight: 'bold',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  } as CSSProperties,
  iconButton: {
    padding: '8px',
    fontSize: '1.5rem',
    fontWeight: 'bold',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    background: 'transparent',
    color: 'rgba(255,255,255,0.7)',
    transition: 'all 0.2s',
    textShadow: '0 2px 8px rgba(0,0,0,0.5)',
    width: '44px',
    height: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative' as const,
  } as CSSProperties,
  badge: {
    position: 'absolute' as const,
    top: '-5px',
    right: '-5px',
    background: '#e74c3c',
    color: '#fff',
    fontSize: '0.65rem',
    fontWeight: 'bold',
    borderRadius: '50%',
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } as CSSProperties,
  startButton: {
    color: '#FFFFFF',
  } as CSSProperties,
  stopButton: {
    color: '#ED5A24',
  } as CSSProperties,
  recordButton: {
    color: '#FF4444',
  } as CSSProperties,
  recordArmedButton: {
    color: '#FF4444',
    border: '2px solid #FF4444',
    animation: 'pulse 2s ease-in-out infinite',
  } as CSSProperties,
  recordingButton: {
    color: '#FF4444',
    animation: 'pulse 1s ease-in-out infinite',
  } as CSSProperties,
  visualizerButton: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: '0.92rem',
    lineHeight: 1,
  } as CSSProperties,
  visualizerButtonActive: {
    color: 'rgba(255,255,255,0.88)',
    background: 'rgba(255, 255, 255, 0.08)',
    border: '1px solid rgba(255, 255, 255, 0.18)',
    boxShadow: '0 0 14px rgba(255, 255, 255, 0.08)',
  } as CSSProperties,
  journeyOverrideOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 10000,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: 'calc(76px + env(safe-area-inset-top)) 14px 14px',
    background: 'rgba(0, 0, 0, 0.48)',
    boxSizing: 'border-box',
  } as CSSProperties,
  journeyOverrideDialog: {
    width: 'min(360px, 100%)',
    borderRadius: '8px',
    border: '1px solid rgba(232, 220, 196, 0.28)',
    background: 'rgba(20, 20, 35, 0.92)',
    boxShadow: '0 18px 52px rgba(0,0,0,0.42), inset 0 1px 0 rgba(255,255,255,0.08)',
    padding: '16px',
    color: '#f4ede4',
  } as CSSProperties,
  journeyOverrideHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  } as CSSProperties,
  journeyOverrideIcon: {
    width: '30px',
    height: '30px',
    borderRadius: '7px',
    display: 'grid',
    placeItems: 'center',
    background: 'rgba(184,224,255,0.12)',
    color: '#B8E0FF',
    fontSize: '1.05rem',
    flexShrink: 0,
  } as CSSProperties,
  journeyOverrideTitle: {
    color: '#B8E0FF',
    fontSize: '0.9rem',
    fontWeight: 800,
    letterSpacing: 0,
  } as CSSProperties,
  journeyOverrideBody: {
    color: 'rgba(244,237,228,0.76)',
    fontSize: '0.82rem',
    lineHeight: 1.45,
    marginBottom: '14px',
  } as CSSProperties,
  journeyOverrideStrong: {
    color: '#f4ede4',
    fontWeight: 800,
  } as CSSProperties,
  journeyOverrideActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  } as CSSProperties,
  journeyOverrideSecondaryButton: {
    height: '34px',
    padding: '0 12px',
    borderRadius: '6px',
    border: '1px solid rgba(255,255,255,0.14)',
    background: 'rgba(255,255,255,0.06)',
    color: '#f4ede4',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontWeight: 700,
  } as CSSProperties,
  journeyOverridePrimaryButton: {
    height: '34px',
    padding: '0 12px',
    borderRadius: '6px',
    border: '1px solid rgba(184,224,255,0.38)',
    background: 'rgba(184,224,255,0.18)',
    color: '#B8E0FF',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontWeight: 800,
  } as CSSProperties,
  macAudioStatus: {
    position: 'fixed',
    left: '14px',
    bottom: 'calc(14px + env(safe-area-inset-bottom))',
    zIndex: 1300,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    maxWidth: 'min(520px, calc(100vw - 28px))',
    padding: '8px 10px',
    border: '1px solid rgba(255, 255, 255, 0.12)',
    borderRadius: '8px',
    background: 'rgba(6, 10, 14, 0.82)',
    boxShadow: '0 10px 24px rgba(0, 0, 0, 0.22)',
    backdropFilter: 'blur(12px)',
  } as CSSProperties,
  backgroundAudioStatus: {
    position: 'fixed',
    right: '14px',
    bottom: 'calc(14px + env(safe-area-inset-bottom))',
    zIndex: 1300,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    maxWidth: 'min(620px, calc(100vw - 28px))',
    padding: '8px 10px',
    border: '1px solid rgba(184, 224, 255, 0.16)',
    borderRadius: '8px',
    background: 'rgba(6, 10, 14, 0.82)',
    boxShadow: '0 10px 24px rgba(0, 0, 0, 0.22)',
    backdropFilter: 'blur(12px)',
  } as CSSProperties,
  macAudioStatusText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'rgba(255, 255, 255, 0.72)',
    fontSize: '0.72rem',
    fontWeight: 700,
  } as CSSProperties,
  macAudioStatusButton: {
    flex: '0 0 auto',
    minHeight: '26px',
    padding: '5px 9px',
    border: '1px solid rgba(255, 255, 255, 0.16)',
    borderRadius: '7px',
    background: 'rgba(255, 255, 255, 0.06)',
    color: 'rgba(255, 255, 255, 0.68)',
    cursor: 'pointer',
    fontSize: '0.68rem',
    fontWeight: 800,
    lineHeight: 1,
  } as CSSProperties,
  macAudioStatusButtonActive: {
    borderColor: 'rgba(94, 234, 212, 0.45)',
    background: 'rgba(20, 184, 166, 0.18)',
    color: '#99f6e4',
  } as CSSProperties,
  statusButtonDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  } as CSSProperties,
  snowflakeControls: {
    position: 'fixed' as const,
    bottom: '30px',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: '20px',
    zIndex: 1000,
  } as CSSProperties,
  simpleButton: {
    color: 'rgba(255,255,255,0.7)',
  } as CSSProperties,
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(280px, 100%), 1fr))',
    gap: '15px',
    marginBottom: '30px',
  } as CSSProperties,
  panel: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '15px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
    maxWidth: '100%',
  } as CSSProperties,
  panelTitle: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    marginBottom: '15px',
    color: '#a5c4d4',
  } as CSSProperties,
  sliderGroup: {
    marginBottom: '12px',
  } as CSSProperties,
  sliderLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '5px',
    fontSize: '0.85rem',
    minWidth: 0,
    gap: '4px',
  } as CSSProperties,
  select: {
    width: '100%',
    padding: '8px',
    borderRadius: '6px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    background: 'rgba(0, 0, 0, 0.3)',
    color: 'white',
    fontSize: '0.9rem',
    colorScheme: 'dark',
  } as CSSProperties,
  tabBar: {
    display: 'flex',
    justifyContent: 'center',
    gap: '4px',
    padding: '8px 16px',
    background: 'rgba(18, 17, 15, 0.6)',
    borderRadius: '12px',
    marginBottom: '16px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
  } as CSSProperties,
  tab: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '4px',
    padding: '8px 16px',
    background: 'transparent',
    border: '1px solid transparent',
    borderRadius: '8px',
    color: '#666',
    fontSize: '0.75rem',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    minWidth: '60px',
  } as CSSProperties,
  tabActive: {
    background: 'rgba(247, 250, 252, 0.09)',
    color: '#F7FAFC',
    border: '1px solid rgba(247, 250, 252, 0.24)',
    boxShadow: '0 0 14px rgba(247, 250, 252, 0.08)',
  } as CSSProperties,
  tabIcon: {
    fontSize: '1.2rem',
    lineHeight: 1,
  } as CSSProperties,
  debugPanel: {
    background: 'rgba(15, 25, 40, 0.4)',
    borderRadius: '12px',
    padding: '20px',
    border: '1px solid rgba(100, 150, 200, 0.3)',
    fontFamily: 'monospace',
    fontSize: '0.85rem',
    overflow: 'hidden',
    maxWidth: '100%',
  } as CSSProperties,
  debugRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '8px',
    gap: '8px',
    flexWrap: 'wrap' as const,
  } as CSSProperties,
  debugLabel: {
    color: '#9ca3af',
    flexShrink: 0,
  } as CSSProperties,
  debugValue: {
    color: '#a5c4d4',
    fontWeight: 'bold',
    wordBreak: 'break-all' as const,
    minWidth: 0,
  } as CSSProperties,
  copied: {
    color: '#2ecc71',
    fontSize: '0.85rem',
    marginTop: '10px',
    textAlign: 'center' as const,
  } as CSSProperties,
};
