#pragma once

#include <cstdint>

#include "KesshoProductParamIds.h"

namespace kessho::product::internal {

static_assert(
    KESSHO_PRODUCT_PARAM_FX_DYNAMICS_MOD_NOISE_ALIAS_ID -
            KESSHO_PRODUCT_PARAM_FX_DYNAMICS_MOD_SLOW_WOW_ID + 1u ==
        kDynamicsModSourceCount * kDynamicsModTargetCount,
    "Dynamics modulation matrix Product Core param IDs must remain contiguous");

enum DynamicsCharacterParamIndex : uint32_t {
  kDynActive = 0,
  kDynAllpassActive = 1,
  kDynDry = 2,
  kDynWet = 3,
  kDynDegradeMix = 4,
  kDynDegradeAlias = 5,
  kDynDegradeGeneration = 6,
  kDynDegradeCorrosion = 7,
  kDynDegradeWear = 8,
  kDynNoiseGain = 9,
  kDynJitterDepth = 10,
  kDynRandomDriftFilterHz = 11,
  kDynRandomDriftDepth = 12,
  kDynBaseDelay = 13,
  kDynSpreadDelay = 14,
  kDynRandomDrift = 15,
  kDynRandomHoldRateHz = 16,
  kDynRandomHoldLag = 17,
  kDynRandomDelayDepth = 18,
  kDynRandomSpreadDelayDepth = 19,
  kDynRandomFilterDepth = 20,
  kDynRandomSpreadFilterDepth = 21,
  kDynDepth = 22,
  kDynRate = 23,
  kDynShallow = 24,
  kDynAbyss = 25,
  kDynStereo = 26,
  kDynDamage = 27,
  kDynMainPan = 28,
  kDynSpreadPan = 29,
  kDynMainDelayGain = 30,
  kDynSpreadDelayGain = 31,
  kDynWowFrequency = 32,
  kDynFlutterFrequency = 33,
  kDynFlutterRandomDepth = 34,
  kDynWowDepth = 35,
  kDynFlutterDepth = 36,
  kDynHighpassHz = 37,
  kDynHighpassQ = 38,
  kDynAllpassAFrequency = 39,
  kDynAllpassAQ = 40,
  kDynAllpassBFrequency = 41,
  kDynAllpassBQ = 42,
  kDynHeadBumpFrequency = 43,
  kDynHeadBumpQ = 44,
  kDynHeadBumpGain = 45,
  kDynDropoutFilterHz = 46,
  kDynDropoutDepth = 47,
  kDynDropoutGain = 48,
  kDynEnvFilterHz = 49,
  kDynEnvToLowpassGain = 50,
  kDynEnvToResonanceGain = 51,
  kDynEnvToWetGain = 52,
  kDynLowpassHz = 53,
  kDynLowpassQ = 54,
  kDynLowpassStage2Hz = 55,
  kDynLowpassStage2Q = 56,
  kDynCompressorThreshold = 57,
  kDynCompressorKnee = 58,
  kDynCompressorRatio = 59,
  kDynCompressorAttack = 60,
  kDynCompressorRelease = 61,
  kDynCompressorMakeup = 62,
  kDynSaturation = 63,
  kDynCorrosion = 64,
  kDynMasterSatActive = 65,
  kDynMasterSatMode = 66,
  kDynMasterSatDrive = 67,
  kDynMasterSatTone = 68,
  kDynMasterSatBias = 69,
  kDynEndCompActive = 70,
  kDynEndCompThreshold = 71,
  kDynEndCompKnee = 72,
  kDynEndCompRatio = 73,
  kDynEndCompAttack = 74,
  kDynEndCompRelease = 75,
  kDynEndCompMakeup = 76,
  kDynEndCompMix = 77,
  kDynEndCompDetectorHpHz = 78,
  kDynEndCompDetectorTilt = 79,
  kDynEndCompAutoMakeup = 80,
  kDynEndCompProgramRelease = 81,
};

} // namespace kessho::product::internal
