import type { CoreProductSnapshot } from './coreProductSnapshotTypes';

type HarmonySnapshotWriter = {
  u32(value: number): void;
  i32(value: number): void;
  f32(value: number): void;
  fixedUtf8(value: string, bytes: number): void;
};

export function encodeCoreProductHarmonySnapshot(
  harmony: CoreProductSnapshot['harmony'],
  writer: HarmonySnapshotWriter,
): void {
  const { u32, i32, f32, fixedUtf8 } = writer;
  f32(harmony.rootMidi);
  u32(harmony.scaleId);
  f32(harmony.tension);
  u32(harmony.chordMode);
  u32(harmony.voicingMode);
  u32(harmony.controlMode);
  u32(harmony.controlStrength);
  u32(harmony.activeSource);
  i32(harmony.activeSlotId);
  i32(harmony.activeStepIndex);
  u32(harmony.manualControlAvailable ? 1 : 0);
  u32(harmony.notePoolCount);
  for (let index = 0; index < 8; index += 1) f32(harmony.notePoolMidi[index] ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotNoteCount?.[index] ?? 0);
  for (let index = 0; index < 64; index += 1) f32(harmony.harmonySlotMidi?.[index] ?? 0);
  f32(harmony.bassMidi);
  u32(harmony.nextNotePoolCount);
  for (let index = 0; index < 8; index += 1) f32(harmony.nextNotePoolMidi[index] ?? 0);
  u32(harmony.nextSource);
  i32(harmony.nextStepIndex);
  f32(harmony.chordIntervalSeconds);
  fixedUtf8(harmony.seedMaterial, 128);
  u32(harmony.nextPhraseIndex);
  u32(Math.floor(harmony.nextPhraseIndex / 0x1_0000_0000));
  u32(harmony.nextProgressionPhraseIndex);
  u32(Math.floor(harmony.nextProgressionPhraseIndex / 0x1_0000_0000));
  f32(harmony.phraseLengthSeconds);
  f32(harmony.progressionPhraseSeconds);
  f32(harmony.voicingSpread);
  f32(harmony.detuneCents);
  u32(harmony.scaleMode);
  u32(harmony.phrasesUntilChange);
  i32(harmony.currentDegree);
  u32(harmony.progressionEnabled ? 1 : 0);
  for (let index = 0; index < 8; index += 1) i32(harmony.progressionPattern[index] ?? 0);
  u32(harmony.progressionStepEnabledMask);
  u32(harmony.progressionSteps);
  u32(harmony.progressionStep);
  u32(harmony.progressionPhraseMultiplier);
  u32(harmony.progressionPhraseCounter);
  u32(harmony.tensionArcType);
  u32(harmony.tensionArcPhrasesRemaining);
  u32(harmony.cofEnabled ? 1 : 0);
  i32(harmony.cofCurrentStep);
  u32(harmony.cofPhraseCounter);
  i32(harmony.cofHomeRoot);
  u32(harmony.cofDriftRate);
  u32(harmony.cofDriftDirection);
  u32(harmony.cofDriftRange);
  u32(harmony.canonicalProgressionVersion ?? 1);
  u32(harmony.canonicalProgressionEnabled ? 1 : 0);
  u32(harmony.canonicalProgressionEventCount ?? 1);
  u32(harmony.canonicalProgressionCurrentEvent ?? 0);
  u32(harmony.canonicalProgressionBarsPerPhrase ?? 4);
  for (let index = 0; index < 64; index += 1) u32(harmony.canonicalProgressionSource?.[index] ?? 0);
  for (let index = 0; index < 64; index += 1) u32(harmony.canonicalProgressionSlotId?.[index] ?? 0);
  for (let index = 0; index < 64; index += 1) u32(harmony.canonicalProgressionDurationUnit?.[index] ?? 1);
  for (let index = 0; index < 64; index += 1) u32(harmony.canonicalProgressionDurationValue?.[index] ?? 1);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotPlaybackBehavior?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentPresent?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentQuality?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentRootMode?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) i32(harmony.harmonySlotIntentDegree?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) f32(harmony.harmonySlotIntentRootNote?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) i32(harmony.harmonySlotIntentInversion?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) f32(harmony.harmonySlotIntentSpread?.[index] ?? 0.5);
  for (let index = 0; index < 8; index += 1) i32(harmony.harmonySlotIntentOctave?.[index] ?? 4);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentBassMode?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) f32(harmony.harmonySlotIntentBassNote?.[index] ?? -1);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentStrength?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentSource?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentExtensionMask?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotIntentAlterationMask?.[index] ?? 0);
  for (let index = 0; index < 8; index += 1) f32(harmony.harmonySlotCapturedRootMidi?.[index] ?? 60);
  for (let index = 0; index < 8; index += 1) u32(harmony.harmonySlotCapturedScaleId?.[index] ?? 1);
  u32(harmony.liveGestureRevision ?? 0); u32(harmony.liveGestureScope ?? 0); u32(harmony.liveGestureTarget ?? 0); u32(harmony.liveGesturePhase ?? 0);
  u32(harmony.liveGesturePlaybackBehavior ?? 0); u32(harmony.liveGestureIntentPresent ?? 0); u32(harmony.liveGestureIntentQuality ?? 0); u32(harmony.liveGestureIntentRootMode ?? 0); i32(harmony.liveGestureIntentDegree ?? 0);
  f32(harmony.liveGestureIntentRootNote ?? 0); i32(harmony.liveGestureIntentInversion ?? 0); f32(harmony.liveGestureIntentSpread ?? 0.5); i32(harmony.liveGestureIntentOctave ?? 4);
  u32(harmony.liveGestureIntentBassMode ?? 0); f32(harmony.liveGestureIntentBassNote ?? -1); u32(harmony.liveGestureIntentExtensionMask ?? 0); u32(harmony.liveGestureIntentAlterationMask ?? 0);
  f32(harmony.liveGestureCapturedRootMidi ?? 60); u32(harmony.liveGestureCapturedScaleId ?? 1); u32(harmony.liveGestureNoteCount ?? 0);
  for (let index = 0; index < 8; index += 1) f32(harmony.liveGestureNotes?.[index] ?? 0);
  const liveExpires = Math.max(0, Math.floor(harmony.liveGestureExpiresAtFrame ?? 0)); u32(liveExpires); u32(Math.floor(liveExpires / 0x1_0000_0000));
  u32(harmony.takeoverAnchorCount ?? 0);
  for (let index = 0; index < 12; index += 1) f32(harmony.takeoverAnchorSource?.[index] ?? 0);
  for (let index = 0; index < 12; index += 1) f32(harmony.takeoverAnchorTarget?.[index] ?? 0);
  for (let index = 0; index < 12; index += 1) f32(harmony.takeoverAnchorWeight?.[index] ?? 0);
  f32(harmony.takeoverTargetRootMidi ?? 60); u32(harmony.takeoverTargetScaleId ?? 1); f32(harmony.takeoverProgress ?? 0);
  u32(harmony.morphEndpointCount ?? 0);
  for (let index = 0; index < 2; index += 1) f32(harmony.morphEndpointRootMidi?.[index] ?? 60);
  for (let index = 0; index < 2; index += 1) u32(harmony.morphEndpointScaleId?.[index] ?? 1);
  for (let index = 0; index < 2; index += 1) f32(harmony.morphEndpointTension?.[index] ?? 0.35);
  u32(harmony.morphPlanRevision ?? 0); f32(harmony.morphPlanPhase ?? 0);
  for (let index = 0; index < 8; index += 1) u32(harmony.morphPlanSlotPlaybackBehavior?.[index] ?? 0);
  u32(harmony.morphCommonPairCount ?? 0); for (let index = 0; index < 8; index += 1) f32(harmony.morphCommonPairSource?.[index] ?? 0); for (let index = 0; index < 8; index += 1) f32(harmony.morphCommonPairTarget?.[index] ?? 0);
  u32(harmony.morphVoicePairCount ?? 0); for (let index = 0; index < 8; index += 1) f32(harmony.morphVoicePairSource?.[index] ?? 0); for (let index = 0; index < 8; index += 1) f32(harmony.morphVoicePairTarget?.[index] ?? 0);
  u32(harmony.morphUnmatchedACount ?? 0); for (let index = 0; index < 8; index += 1) f32(harmony.morphUnmatchedA?.[index] ?? 0);
  u32(harmony.morphUnmatchedBCount ?? 0); for (let index = 0; index < 8; index += 1) f32(harmony.morphUnmatchedB?.[index] ?? 0);
  u32(harmony.morphCofRootPathCount ?? 0); for (let index = 0; index < 13; index += 1) f32(harmony.morphCofRootPath?.[index] ?? 0);
  u32(harmony.morphScaleHandoverFrom ?? 1); u32(harmony.morphScaleHandoverTo ?? 1); f32(harmony.morphScaleHandoverAt ?? 0.5);
}
