/**
 * Drum Voice Presets
 * 
 * 64+ presets for the 6 drum voices, spanning:
 * - Ikeda-style minimalist data sounds
 * - ASMR ear candy textures
 * - Ambient/textural percussion
 * 
 * Each preset defines all parameters for a single voice.
 * The morph system interpolates between any two presets.
 */

export type DrumVoiceType = 'sub' | 'kick' | 'click' | 'beepHi' | 'beepLo' | 'noise';

export interface DrumVoicePreset {
  name: string;
  voice: DrumVoiceType;
  params: Record<string, number | string>;
  tags: string[];
}

// ═══════════════════════════════════════════════════════════════════════════
// SUB PRESETS (10)
// ═══════════════════════════════════════════════════════════════════════════

export const SUB_PRESETS: DrumVoicePreset[] = [
  {
    name: 'Classic Sub',
    voice: 'sub',
    tags: ['ikeda', 'minimal', 'default'],
    params: {
      drumSubFreq: 50,
      drumSubDecay: 150,
      drumSubLevel: 0.8,
      drumSubTone: 0.1,
      drumSubShape: 0,
      drumSubPitchEnv: 0,
      drumSubPitchDecay: 50,
      drumSubDrive: 0,
      drumSubSub: 0,
    },
  },
  {
    name: 'Deep Thump',
    voice: 'sub',
    tags: ['ambient', 'deep', 'room'],
    params: {
      drumSubFreq: 35,
      drumSubDecay: 800,
      drumSubLevel: 0.9,
      drumSubTone: 0.3,
      drumSubShape: 0.2,
      drumSubPitchEnv: 12,
      drumSubPitchDecay: 80,
      drumSubDrive: 0.4,
      drumSubSub: 0.3,
    },
  },
  {
    name: 'Bubble Up',
    voice: 'sub',
    tags: ['asmr', 'water', 'texture'],
    params: {
      drumSubFreq: 60,
      drumSubDecay: 300,
      drumSubLevel: 0.7,
      drumSubTone: 0.05,
      drumSubShape: 0,
      drumSubPitchEnv: -24,  // Pitch rises
      drumSubPitchDecay: 150,
      drumSubDrive: 0,
      drumSubSub: 0,
    },
  },
  {
    name: 'Warm Pulse',
    voice: 'sub',
    tags: ['analog', 'warm', 'ambient'],
    params: {
      drumSubFreq: 45,
      drumSubDecay: 400,
      drumSubLevel: 0.75,
      drumSubTone: 0.4,
      drumSubShape: 0.5,  // Triangle
      drumSubPitchEnv: 6,
      drumSubPitchDecay: 100,
      drumSubDrive: 0.3,
      drumSubSub: 0.5,
    },
  },
  {
    name: 'Data Pulse',
    voice: 'sub',
    tags: ['ikeda', 'digital', 'minimal'],
    params: {
      drumSubFreq: 55,
      drumSubDecay: 80,
      drumSubLevel: 0.85,
      drumSubTone: 0,
      drumSubShape: 0,
      drumSubPitchEnv: 0,
      drumSubPitchDecay: 20,
      drumSubDrive: 0,
      drumSubSub: 0,
    },
  },
  {
    name: 'Subterranean',
    voice: 'sub',
    tags: ['deep', 'ambient', 'drone'],
    params: {
      drumSubFreq: 30,
      drumSubDecay: 2000,
      drumSubLevel: 0.9,
      drumSubTone: 0.2,
      drumSubShape: 0.1,
      drumSubPitchEnv: 4,
      drumSubPitchDecay: 200,
      drumSubDrive: 0.2,
      drumSubSub: 0.6,
    },
  },
  {
    name: 'Soft Touch',
    voice: 'sub',
    tags: ['asmr', 'gentle', 'texture'],
    params: {
      drumSubFreq: 65,
      drumSubDecay: 60,
      drumSubLevel: 0.4,
      drumSubTone: 0.05,
      drumSubShape: 0,
      drumSubPitchEnv: 2,
      drumSubPitchDecay: 30,
      drumSubDrive: 0,
      drumSubSub: 0,
    },
  },
  {
    name: 'Pressure Wave',
    voice: 'sub',
    tags: ['physical', 'impact', 'ambient'],
    params: {
      drumSubFreq: 40,
      drumSubDecay: 500,
      drumSubLevel: 0.95,
      drumSubTone: 0.15,
      drumSubShape: 0.3,
      drumSubPitchEnv: 36,  // Big pitch drop
      drumSubPitchDecay: 60,
      drumSubDrive: 0.5,
      drumSubSub: 0.4,
    },
  },
  {
    name: 'Sine Ping',
    voice: 'sub',
    tags: ['clean', 'minimal', 'pure'],
    params: {
      drumSubFreq: 80,
      drumSubDecay: 200,
      drumSubLevel: 0.6,
      drumSubTone: 0,
      drumSubShape: 0,
      drumSubPitchEnv: 0,
      drumSubPitchDecay: 50,
      drumSubDrive: 0,
      drumSubSub: 0,
    },
  },
  {
    name: 'Rumble',
    voice: 'sub',
    tags: ['texture', 'distorted', 'ambient'],
    params: {
      drumSubFreq: 38,
      drumSubDecay: 600,
      drumSubLevel: 0.85,
      drumSubTone: 0.6,
      drumSubShape: 0.9,  // Almost saw
      drumSubPitchEnv: 8,
      drumSubPitchDecay: 120,
      drumSubDrive: 0.7,
      drumSubSub: 0.3,
    },
  },
  // Organic presets
  {
    name: 'Heartbeat Pulse',
    voice: 'sub',
    tags: ['organic', 'body', 'pulse', 'natural'],
    params: {
      drumSubFreq: 42,
      drumSubDecay: 450,
      drumSubLevel: 0.7,
      drumSubTone: 0.05,
      drumSubShape: 0,
      drumSubPitchEnv: 6,
      drumSubPitchDecay: 80,
      drumSubDrive: 0,
      drumSubSub: 0.3,
    },
  },
  {
    name: 'Wooden Resonance',
    voice: 'sub',
    tags: ['organic', 'wood', 'hollow', 'natural'],
    params: {
      drumSubFreq: 70,
      drumSubDecay: 250,
      drumSubLevel: 0.65,
      drumSubTone: 0.15,
      drumSubShape: 0.2,
      drumSubPitchEnv: 10,
      drumSubPitchDecay: 40,
      drumSubDrive: 0.1,
      drumSubSub: 0,
    },
  },
  {
    name: 'Earth Rumble',
    voice: 'sub',
    tags: ['organic', 'thunder', 'nature', 'deep'],
    params: {
      drumSubFreq: 35,
      drumSubDecay: 1500,
      drumSubLevel: 0.75,
      drumSubTone: 0.1,
      drumSubShape: 0.1,
      drumSubPitchEnv: 12,
      drumSubPitchDecay: 200,
      drumSubDrive: 0.15,
      drumSubSub: 0.5,
    },
  },
  // Ambient presets
  {
    name: 'Deep Space',
    voice: 'sub',
    tags: ['ambient', 'space', 'drone', 'atmospheric'],
    params: {
      drumSubFreq: 32,
      drumSubDecay: 2000,
      drumSubLevel: 0.6,
      drumSubTone: 0.1,
      drumSubShape: 0,
      drumSubPitchEnv: 8,
      drumSubPitchDecay: 300,
      drumSubDrive: 0,
      drumSubSub: 0.4,
    },
  },
  {
    name: 'Velvet Thump',
    voice: 'sub',
    tags: ['ambient', 'soft', 'pillowy', 'gentle'],
    params: {
      drumSubFreq: 50,
      drumSubDecay: 400,
      drumSubLevel: 0.5,
      drumSubTone: 0,
      drumSubShape: 0,
      drumSubPitchEnv: 4,
      drumSubPitchDecay: 60,
      drumSubDrive: 0,
      drumSubSub: 0,
    },
  },
  {
    name: 'Tidal Pull',
    voice: 'sub',
    tags: ['ambient', 'ocean', 'slow', 'deep'],
    params: {
      drumSubFreq: 38,
      drumSubDecay: 1200,
      drumSubLevel: 0.55,
      drumSubTone: 0.05,
      drumSubShape: 0.05,
      drumSubPitchEnv: 10,
      drumSubPitchDecay: 250,
      drumSubDrive: 0.1,
      drumSubSub: 0.35,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// KICK PRESETS (10)
// ═══════════════════════════════════════════════════════════════════════════

export const KICK_PRESETS: DrumVoicePreset[] = [
  {
    name: 'Ikeda Kick',
    voice: 'kick',
    tags: ['ikeda', 'digital', 'sharp'],
    params: {
      drumKickFreq: 55,
      drumKickPitchEnv: 24,
      drumKickPitchDecay: 30,
      drumKickDecay: 200,
      drumKickLevel: 0.7,
      drumKickClick: 0.3,
      drumKickBody: 0.3,
      drumKickPunch: 0.8,
      drumKickTail: 0,
      drumKickTone: 0,
    },
  },
  {
    name: 'Ambient Boom',
    voice: 'kick',
    tags: ['ambient', 'spacious', 'deep'],
    params: {
      drumKickFreq: 45,
      drumKickPitchEnv: 18,
      drumKickPitchDecay: 80,
      drumKickDecay: 1500,
      drumKickLevel: 0.75,
      drumKickClick: 0.1,
      drumKickBody: 1.0,
      drumKickPunch: 0.2,
      drumKickTail: 0.7,
      drumKickTone: 0.2,
    },
  },
  {
    name: 'Soft Tap',
    voice: 'kick',
    tags: ['asmr', 'gentle', 'finger'],
    params: {
      drumKickFreq: 80,
      drumKickPitchEnv: 6,
      drumKickPitchDecay: 20,
      drumKickDecay: 80,
      drumKickLevel: 0.35,
      drumKickClick: 0,
      drumKickBody: 0.6,
      drumKickPunch: 0.1,
      drumKickTail: 0,
      drumKickTone: 0,
    },
  },
  {
    name: 'Tight Punch',
    voice: 'kick',
    tags: ['punchy', 'tight', 'electronic'],
    params: {
      drumKickFreq: 60,
      drumKickPitchEnv: 36,
      drumKickPitchDecay: 15,
      drumKickDecay: 120,
      drumKickLevel: 0.85,
      drumKickClick: 0.5,
      drumKickBody: 0.2,
      drumKickPunch: 1.0,
      drumKickTail: 0,
      drumKickTone: 0.1,
    },
  },
  {
    name: '808 Deep',
    voice: 'kick',
    tags: ['808', 'deep', 'classic'],
    params: {
      drumKickFreq: 40,
      drumKickPitchEnv: 12,
      drumKickPitchDecay: 50,
      drumKickDecay: 800,
      drumKickLevel: 0.9,
      drumKickClick: 0.2,
      drumKickBody: 0.8,
      drumKickPunch: 0.5,
      drumKickTail: 0.3,
      drumKickTone: 0.1,
    },
  },
  {
    name: 'Paper Thud',
    voice: 'kick',
    tags: ['asmr', 'muted', 'soft'],
    params: {
      drumKickFreq: 70,
      drumKickPitchEnv: 8,
      drumKickPitchDecay: 25,
      drumKickDecay: 60,
      drumKickLevel: 0.5,
      drumKickClick: 0,
      drumKickBody: 0.4,
      drumKickPunch: 0.2,
      drumKickTail: 0,
      drumKickTone: 0,
    },
  },
  {
    name: 'Room Kick',
    voice: 'kick',
    tags: ['natural', 'room', 'ambient'],
    params: {
      drumKickFreq: 55,
      drumKickPitchEnv: 20,
      drumKickPitchDecay: 40,
      drumKickDecay: 400,
      drumKickLevel: 0.7,
      drumKickClick: 0.25,
      drumKickBody: 0.7,
      drumKickPunch: 0.5,
      drumKickTail: 0.5,
      drumKickTone: 0.15,
    },
  },
  {
    name: 'Click Kick',
    voice: 'kick',
    tags: ['clicky', 'attack', 'electronic'],
    params: {
      drumKickFreq: 65,
      drumKickPitchEnv: 30,
      drumKickPitchDecay: 10,
      drumKickDecay: 150,
      drumKickLevel: 0.7,
      drumKickClick: 0.9,
      drumKickBody: 0.3,
      drumKickPunch: 0.9,
      drumKickTail: 0,
      drumKickTone: 0.2,
    },
  },
  {
    name: 'Pillow',
    voice: 'kick',
    tags: ['asmr', 'soft', 'gentle'],
    params: {
      drumKickFreq: 50,
      drumKickPitchEnv: 4,
      drumKickPitchDecay: 60,
      drumKickDecay: 300,
      drumKickLevel: 0.4,
      drumKickClick: 0,
      drumKickBody: 0.9,
      drumKickPunch: 0,
      drumKickTail: 0.2,
      drumKickTone: 0,
    },
  },
  {
    name: 'Heartbeat',
    voice: 'kick',
    tags: ['organic', 'pulse', 'ambient'],
    params: {
      drumKickFreq: 48,
      drumKickPitchEnv: 10,
      drumKickPitchDecay: 100,
      drumKickDecay: 500,
      drumKickLevel: 0.65,
      drumKickClick: 0.1,
      drumKickBody: 0.85,
      drumKickPunch: 0.3,
      drumKickTail: 0.4,
      drumKickTone: 0.05,
    },
  },
  // Organic presets
  {
    name: 'Djembe',
    voice: 'kick',
    tags: ['organic', 'hand drum', 'african', 'natural'],
    params: {
      drumKickFreq: 70,
      drumKickPitchEnv: 14,
      drumKickPitchDecay: 35,
      drumKickDecay: 250,
      drumKickLevel: 0.7,
      drumKickClick: 0.15,
      drumKickBody: 0.9,
      drumKickPunch: 0.4,
      drumKickTail: 0.35,
      drumKickTone: 0.1,
    },
  },
  {
    name: 'Frame Drum',
    voice: 'kick',
    tags: ['organic', 'hand drum', 'ethnic', 'natural'],
    params: {
      drumKickFreq: 45,
      drumKickPitchEnv: 8,
      drumKickPitchDecay: 60,
      drumKickDecay: 350,
      drumKickLevel: 0.6,
      drumKickClick: 0.05,
      drumKickBody: 0.95,
      drumKickPunch: 0.15,
      drumKickTail: 0.5,
      drumKickTone: 0.05,
    },
  },
  {
    name: 'Cajon',
    voice: 'kick',
    tags: ['organic', 'wood', 'percussion', 'natural'],
    params: {
      drumKickFreq: 65,
      drumKickPitchEnv: 12,
      drumKickPitchDecay: 25,
      drumKickDecay: 180,
      drumKickLevel: 0.7,
      drumKickClick: 0.4,
      drumKickBody: 0.7,
      drumKickPunch: 0.5,
      drumKickTail: 0.2,
      drumKickTone: 0.15,
    },
  },
  {
    name: 'Stomped Earth',
    voice: 'kick',
    tags: ['organic', 'foot', 'ground', 'natural'],
    params: {
      drumKickFreq: 50,
      drumKickPitchEnv: 6,
      drumKickPitchDecay: 50,
      drumKickDecay: 300,
      drumKickLevel: 0.6,
      drumKickClick: 0.05,
      drumKickBody: 0.85,
      drumKickPunch: 0.2,
      drumKickTail: 0.6,
      drumKickTone: 0.05,
    },
  },
  // Ambient presets
  {
    name: 'Distant Thunder',
    voice: 'kick',
    tags: ['ambient', 'storm', 'atmospheric', 'deep'],
    params: {
      drumKickFreq: 40,
      drumKickPitchEnv: 10,
      drumKickPitchDecay: 120,
      drumKickDecay: 1200,
      drumKickLevel: 0.55,
      drumKickClick: 0,
      drumKickBody: 0.7,
      drumKickPunch: 0.1,
      drumKickTail: 0.8,
      drumKickTone: 0.1,
    },
  },
  {
    name: 'Ghost Pulse',
    voice: 'kick',
    tags: ['ambient', 'subtle', 'background', 'minimal'],
    params: {
      drumKickFreq: 45,
      drumKickPitchEnv: 6,
      drumKickPitchDecay: 80,
      drumKickDecay: 600,
      drumKickLevel: 0.4,
      drumKickClick: 0,
      drumKickBody: 0.8,
      drumKickPunch: 0.05,
      drumKickTail: 0.5,
      drumKickTone: 0,
    },
  },
  {
    name: 'Slow Bloom',
    voice: 'kick',
    tags: ['ambient', 'swell', 'gradual', 'atmospheric'],
    params: {
      drumKickFreq: 42,
      drumKickPitchEnv: 4,
      drumKickPitchDecay: 150,
      drumKickDecay: 900,
      drumKickLevel: 0.5,
      drumKickClick: 0,
      drumKickBody: 0.9,
      drumKickPunch: 0,
      drumKickTail: 0.7,
      drumKickTone: 0.05,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CLICK PRESETS (12)
// ═══════════════════════════════════════════════════════════════════════════

export const CLICK_PRESETS: DrumVoicePreset[] = [
  {
    name: 'Data Point',
    voice: 'click',
    tags: ['ikeda', 'digital', 'sharp'],
    params: {
      drumClickDecay: 5,
      drumClickFilter: 4000,
      drumClickTone: 0.3,
      drumClickLevel: 0.6,
      drumClickResonance: 0.4,
      drumClickPitch: 2000,
      drumClickPitchEnv: 0,
      drumClickMode: 'impulse',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0,
    },
  },
  {
    name: 'Tick',
    voice: 'click',
    tags: ['clock', 'minimal', 'sharp'],
    params: {
      drumClickDecay: 2,
      drumClickFilter: 6000,
      drumClickTone: 0.1,
      drumClickLevel: 0.5,
      drumClickResonance: 0.2,
      drumClickPitch: 3000,
      drumClickPitchEnv: 0,
      drumClickMode: 'impulse',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0,
    },
  },
  {
    name: 'Blip',
    voice: 'click',
    tags: ['soft', 'digital', 'tonal'],
    params: {
      drumClickDecay: 15,
      drumClickFilter: 2000,
      drumClickTone: 0.5,
      drumClickLevel: 0.55,
      drumClickResonance: 0.5,
      drumClickPitch: 1500,
      drumClickPitchEnv: -6,
      drumClickMode: 'tonal',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0,
    },
  },
  {
    name: 'Crinkle',
    voice: 'click',
    tags: ['asmr', 'texture', 'paper'],
    params: {
      drumClickDecay: 40,
      drumClickFilter: 3000,
      drumClickTone: 0.8,
      drumClickLevel: 0.45,
      drumClickResonance: 0.3,
      drumClickPitch: 2500,
      drumClickPitchEnv: 0,
      drumClickMode: 'granular',
      drumClickGrainCount: 5,
      drumClickGrainSpread: 20,
      drumClickStereoWidth: 0.6,
    },
  },
  {
    name: 'Dust',
    voice: 'click',
    tags: ['vinyl', 'texture', 'sparse'],
    params: {
      drumClickDecay: 3,
      drumClickFilter: 5000,
      drumClickTone: 0.4,
      drumClickLevel: 0.3,
      drumClickResonance: 0.1,
      drumClickPitch: 4000,
      drumClickPitchEnv: 0,
      drumClickMode: 'granular',
      drumClickGrainCount: 2,
      drumClickGrainSpread: 8,
      drumClickStereoWidth: 0.8,
    },
  },
  {
    name: 'Glitch',
    voice: 'click',
    tags: ['digital', 'error', 'electronic'],
    params: {
      drumClickDecay: 8,
      drumClickFilter: 3500,
      drumClickTone: 0.6,
      drumClickLevel: 0.65,
      drumClickResonance: 0.7,
      drumClickPitch: 2800,
      drumClickPitchEnv: 24,
      drumClickMode: 'tonal',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0.3,
    },
  },
  {
    name: 'Tap',
    voice: 'click',
    tags: ['asmr', 'finger', 'gentle'],
    params: {
      drumClickDecay: 12,
      drumClickFilter: 1500,
      drumClickTone: 0.4,
      drumClickLevel: 0.4,
      drumClickResonance: 0.3,
      drumClickPitch: 800,
      drumClickPitchEnv: -4,
      drumClickMode: 'impulse',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0,
    },
  },
  {
    name: 'Spark',
    voice: 'click',
    tags: ['electric', 'bright', 'sharp'],
    params: {
      drumClickDecay: 6,
      drumClickFilter: 8000,
      drumClickTone: 0.2,
      drumClickLevel: 0.55,
      drumClickResonance: 0.8,
      drumClickPitch: 5000,
      drumClickPitchEnv: 12,
      drumClickMode: 'impulse',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0.2,
    },
  },
  {
    name: 'Pop',
    voice: 'click',
    tags: ['bubble', 'soft', 'asmr'],
    params: {
      drumClickDecay: 20,
      drumClickFilter: 2000,
      drumClickTone: 0.7,
      drumClickLevel: 0.5,
      drumClickResonance: 0.6,
      drumClickPitch: 1200,
      drumClickPitchEnv: -12,
      drumClickMode: 'noise',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0,
    },
  },
  {
    name: 'Static',
    voice: 'click',
    tags: ['radio', 'texture', 'noise'],
    params: {
      drumClickDecay: 50,
      drumClickFilter: 4500,
      drumClickTone: 0.9,
      drumClickLevel: 0.35,
      drumClickResonance: 0.2,
      drumClickPitch: 3000,
      drumClickPitchEnv: 0,
      drumClickMode: 'noise',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0.4,
    },
  },
  {
    name: 'Scratch',
    voice: 'click',
    tags: ['vinyl', 'texture', 'dj'],
    params: {
      drumClickDecay: 25,
      drumClickFilter: 3000,
      drumClickTone: 0.6,
      drumClickLevel: 0.5,
      drumClickResonance: 0.4,
      drumClickPitch: 2000,
      drumClickPitchEnv: -18,
      drumClickMode: 'granular',
      drumClickGrainCount: 4,
      drumClickGrainSpread: 15,
      drumClickStereoWidth: 0.5,
    },
  },
  {
    name: 'Micro Hit',
    voice: 'click',
    tags: ['tiny', 'minimal', 'impact'],
    params: {
      drumClickDecay: 1,
      drumClickFilter: 5000,
      drumClickTone: 0.2,
      drumClickLevel: 0.45,
      drumClickResonance: 0.3,
      drumClickPitch: 2500,
      drumClickPitchEnv: 6,
      drumClickMode: 'tonal',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0,
    },
  },
  // Organic presets
  {
    name: 'Raindrop',
    voice: 'click',
    tags: ['organic', 'water', 'nature', 'asmr'],
    params: {
      drumClickDecay: 25,
      drumClickFilter: 1500,
      drumClickTone: 0.6,
      drumClickLevel: 0.45,
      drumClickResonance: 0.5,
      drumClickPitch: 600,
      drumClickPitchEnv: -12,
      drumClickMode: 'tonal',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0,
    },
  },
  {
    name: 'Twig Snap',
    voice: 'click',
    tags: ['organic', 'wood', 'forest', 'natural'],
    params: {
      drumClickDecay: 15,
      drumClickFilter: 4500,
      drumClickTone: 0.7,
      drumClickLevel: 0.5,
      drumClickResonance: 0.2,
      drumClickPitch: 3000,
      drumClickPitchEnv: 8,
      drumClickMode: 'granular',
      drumClickGrainCount: 4,
      drumClickGrainSpread: 12,
      drumClickStereoWidth: 0.5,
    },
  },
  {
    name: 'Stone Tap',
    voice: 'click',
    tags: ['organic', 'rock', 'percussion', 'natural'],
    params: {
      drumClickDecay: 8,
      drumClickFilter: 3500,
      drumClickTone: 0.4,
      drumClickLevel: 0.5,
      drumClickResonance: 0.3,
      drumClickPitch: 3500,
      drumClickPitchEnv: 4,
      drumClickMode: 'impulse',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0.2,
    },
  },
  {
    name: 'Seed Pod',
    voice: 'click',
    tags: ['organic', 'rattle', 'nature', 'texture'],
    params: {
      drumClickDecay: 20,
      drumClickFilter: 3000,
      drumClickTone: 0.5,
      drumClickLevel: 0.4,
      drumClickResonance: 0.25,
      drumClickPitch: 2500,
      drumClickPitchEnv: 0,
      drumClickMode: 'granular',
      drumClickGrainCount: 6,
      drumClickGrainSpread: 8,
      drumClickStereoWidth: 0.4,
    },
  },
  // Ambient presets
  {
    name: 'Dewdrop',
    voice: 'click',
    tags: ['ambient', 'water', 'delicate', 'minimal'],
    params: {
      drumClickDecay: 35,
      drumClickFilter: 1200,
      drumClickTone: 0.5,
      drumClickLevel: 0.3,
      drumClickResonance: 0.6,
      drumClickPitch: 800,
      drumClickPitchEnv: -8,
      drumClickMode: 'tonal',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0.2,
    },
  },
  {
    name: 'Grain Scatter',
    voice: 'click',
    tags: ['ambient', 'texture', 'granular', 'atmospheric'],
    params: {
      drumClickDecay: 60,
      drumClickFilter: 2500,
      drumClickTone: 0.4,
      drumClickLevel: 0.35,
      drumClickResonance: 0.3,
      drumClickPitch: 2000,
      drumClickPitchEnv: 0,
      drumClickMode: 'granular',
      drumClickGrainCount: 6,
      drumClickGrainSpread: 30,
      drumClickStereoWidth: 0.9,
    },
  },
  {
    name: 'Ice Crystal',
    voice: 'click',
    tags: ['ambient', 'frozen', 'bright', 'delicate'],
    params: {
      drumClickDecay: 18,
      drumClickFilter: 6000,
      drumClickTone: 0.3,
      drumClickLevel: 0.4,
      drumClickResonance: 0.7,
      drumClickPitch: 4000,
      drumClickPitchEnv: 6,
      drumClickMode: 'tonal',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0.3,
    },
  },
  {
    name: 'Distant Ping',
    voice: 'click',
    tags: ['ambient', 'faraway', 'subtle', 'minimal'],
    params: {
      drumClickDecay: 40,
      drumClickFilter: 2000,
      drumClickTone: 0.3,
      drumClickLevel: 0.25,
      drumClickResonance: 0.4,
      drumClickPitch: 1500,
      drumClickPitchEnv: -4,
      drumClickMode: 'impulse',
      drumClickGrainCount: 1,
      drumClickGrainSpread: 0,
      drumClickStereoWidth: 0.8,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// BEEP HI PRESETS (10)
// ═══════════════════════════════════════════════════════════════════════════

export const BEEP_HI_PRESETS: DrumVoicePreset[] = [
  {
    name: 'Data Ping',
    voice: 'beepHi',
    tags: ['ikeda', 'digital', 'pure'],
    params: {
      drumBeepHiFreq: 4000,
      drumBeepHiAttack: 1,
      drumBeepHiDecay: 80,
      drumBeepHiLevel: 0.5,
      drumBeepHiTone: 0.2,
      drumBeepHiInharmonic: 0,
      drumBeepHiPartials: 1,
      drumBeepHiShimmer: 0,
      drumBeepHiShimmerRate: 4,
      drumBeepHiBrightness: 0.5,
    },
  },
  {
    name: 'Glass',
    voice: 'beepHi',
    tags: ['bell', 'resonant', 'ambient'],
    params: {
      drumBeepHiFreq: 3200,
      drumBeepHiAttack: 2,
      drumBeepHiDecay: 800,
      drumBeepHiLevel: 0.45,
      drumBeepHiTone: 0.4,
      drumBeepHiInharmonic: 0.3,
      drumBeepHiPartials: 4,
      drumBeepHiShimmer: 0.1,
      drumBeepHiShimmerRate: 3,
      drumBeepHiBrightness: 0.7,
    },
  },
  {
    name: 'Bell',
    voice: 'beepHi',
    tags: ['bell', 'metallic', 'ambient'],
    params: {
      drumBeepHiFreq: 2800,
      drumBeepHiAttack: 1,
      drumBeepHiDecay: 1200,
      drumBeepHiLevel: 0.5,
      drumBeepHiTone: 0.5,
      drumBeepHiInharmonic: 0.5,
      drumBeepHiPartials: 5,
      drumBeepHiShimmer: 0.2,
      drumBeepHiShimmerRate: 2,
      drumBeepHiBrightness: 0.6,
    },
  },
  {
    name: 'Crystal',
    voice: 'beepHi',
    tags: ['bright', 'pure', 'asmr'],
    params: {
      drumBeepHiFreq: 6000,
      drumBeepHiAttack: 0,
      drumBeepHiDecay: 400,
      drumBeepHiLevel: 0.4,
      drumBeepHiTone: 0.1,
      drumBeepHiInharmonic: 0.1,
      drumBeepHiPartials: 3,
      drumBeepHiShimmer: 0.05,
      drumBeepHiShimmerRate: 5,
      drumBeepHiBrightness: 0.9,
    },
  },
  {
    name: 'Shimmer',
    voice: 'beepHi',
    tags: ['evolving', 'ambient', 'texture'],
    params: {
      drumBeepHiFreq: 3500,
      drumBeepHiAttack: 5,
      drumBeepHiDecay: 600,
      drumBeepHiLevel: 0.45,
      drumBeepHiTone: 0.3,
      drumBeepHiInharmonic: 0.2,
      drumBeepHiPartials: 3,
      drumBeepHiShimmer: 0.7,
      drumBeepHiShimmerRate: 6,
      drumBeepHiBrightness: 0.6,
    },
  },
  {
    name: 'Chime',
    voice: 'beepHi',
    tags: ['wind', 'bell', 'ambient'],
    params: {
      drumBeepHiFreq: 4500,
      drumBeepHiAttack: 1,
      drumBeepHiDecay: 1500,
      drumBeepHiLevel: 0.4,
      drumBeepHiTone: 0.35,
      drumBeepHiInharmonic: 0.4,
      drumBeepHiPartials: 6,
      drumBeepHiShimmer: 0.3,
      drumBeepHiShimmerRate: 4,
      drumBeepHiBrightness: 0.65,
    },
  },
  {
    name: 'Metallic',
    voice: 'beepHi',
    tags: ['industrial', 'harsh', 'electronic'],
    params: {
      drumBeepHiFreq: 5000,
      drumBeepHiAttack: 0,
      drumBeepHiDecay: 200,
      drumBeepHiLevel: 0.55,
      drumBeepHiTone: 0.8,
      drumBeepHiInharmonic: 0.6,
      drumBeepHiPartials: 4,
      drumBeepHiShimmer: 0,
      drumBeepHiShimmerRate: 4,
      drumBeepHiBrightness: 0.8,
    },
  },
  {
    name: 'Whistle',
    voice: 'beepHi',
    tags: ['pure', 'high', 'asmr'],
    params: {
      drumBeepHiFreq: 8000,
      drumBeepHiAttack: 20,
      drumBeepHiDecay: 300,
      drumBeepHiLevel: 0.35,
      drumBeepHiTone: 0,
      drumBeepHiInharmonic: 0,
      drumBeepHiPartials: 1,
      drumBeepHiShimmer: 0.1,
      drumBeepHiShimmerRate: 5,
      drumBeepHiBrightness: 0.4,
    },
  },
  {
    name: 'Sparkle',
    voice: 'beepHi',
    tags: ['magical', 'bright', 'texture'],
    params: {
      drumBeepHiFreq: 5500,
      drumBeepHiAttack: 0,
      drumBeepHiDecay: 500,
      drumBeepHiLevel: 0.4,
      drumBeepHiTone: 0.25,
      drumBeepHiInharmonic: 0.25,
      drumBeepHiPartials: 4,
      drumBeepHiShimmer: 0.5,
      drumBeepHiShimmerRate: 8,
      drumBeepHiBrightness: 0.85,
    },
  },
  {
    name: 'Tink',
    voice: 'beepHi',
    tags: ['tiny', 'metal', 'minimal'],
    params: {
      drumBeepHiFreq: 7000,
      drumBeepHiAttack: 0,
      drumBeepHiDecay: 50,
      drumBeepHiLevel: 0.45,
      drumBeepHiTone: 0.15,
      drumBeepHiInharmonic: 0.15,
      drumBeepHiPartials: 2,
      drumBeepHiShimmer: 0,
      drumBeepHiShimmerRate: 4,
      drumBeepHiBrightness: 0.75,
    },
  },
  // Organic presets
  {
    name: 'Wind Chime',
    voice: 'beepHi',
    tags: ['organic', 'metal', 'wind', 'ambient'],
    params: {
      drumBeepHiFreq: 3000,
      drumBeepHiAttack: 2,
      drumBeepHiDecay: 1500,
      drumBeepHiLevel: 0.4,
      drumBeepHiTone: 0.4,
      drumBeepHiInharmonic: 0.45,
      drumBeepHiPartials: 6,
      drumBeepHiShimmer: 0.35,
      drumBeepHiShimmerRate: 3,
      drumBeepHiBrightness: 0.6,
    },
  },
  {
    name: 'Bird Call',
    voice: 'beepHi',
    tags: ['organic', 'nature', 'animal', 'forest'],
    params: {
      drumBeepHiFreq: 6000,
      drumBeepHiAttack: 5,
      drumBeepHiDecay: 150,
      drumBeepHiLevel: 0.4,
      drumBeepHiTone: 0.1,
      drumBeepHiInharmonic: 0.1,
      drumBeepHiPartials: 2,
      drumBeepHiShimmer: 0.6,
      drumBeepHiShimmerRate: 10,
      drumBeepHiBrightness: 0.7,
    },
  },
  {
    name: 'Bamboo Knock',
    voice: 'beepHi',
    tags: ['organic', 'wood', 'percussion', 'natural'],
    params: {
      drumBeepHiFreq: 2400,
      drumBeepHiAttack: 0,
      drumBeepHiDecay: 150,
      drumBeepHiLevel: 0.5,
      drumBeepHiTone: 0.25,
      drumBeepHiInharmonic: 0.3,
      drumBeepHiPartials: 3,
      drumBeepHiShimmer: 0,
      drumBeepHiShimmerRate: 4,
      drumBeepHiBrightness: 0.55,
    },
  },
  {
    name: 'Insect Wing',
    voice: 'beepHi',
    tags: ['organic', 'nature', 'flutter', 'texture'],
    params: {
      drumBeepHiFreq: 5000,
      drumBeepHiAttack: 2,
      drumBeepHiDecay: 80,
      drumBeepHiLevel: 0.35,
      drumBeepHiTone: 0.15,
      drumBeepHiInharmonic: 0.2,
      drumBeepHiPartials: 2,
      drumBeepHiShimmer: 0.8,
      drumBeepHiShimmerRate: 15,
      drumBeepHiBrightness: 0.6,
    },
  },
  // Ambient presets
  {
    name: 'Singing Bowl',
    voice: 'beepHi',
    tags: ['ambient', 'meditation', 'sustain', 'resonant'],
    params: {
      drumBeepHiFreq: 2400,
      drumBeepHiAttack: 5,
      drumBeepHiDecay: 2500,
      drumBeepHiLevel: 0.4,
      drumBeepHiTone: 0.3,
      drumBeepHiInharmonic: 0.4,
      drumBeepHiPartials: 5,
      drumBeepHiShimmer: 0.25,
      drumBeepHiShimmerRate: 2,
      drumBeepHiBrightness: 0.5,
    },
  },
  {
    name: 'Frozen Bells',
    voice: 'beepHi',
    tags: ['ambient', 'cold', 'distant', 'atmospheric'],
    params: {
      drumBeepHiFreq: 4000,
      drumBeepHiAttack: 3,
      drumBeepHiDecay: 1800,
      drumBeepHiLevel: 0.35,
      drumBeepHiTone: 0.2,
      drumBeepHiInharmonic: 0.35,
      drumBeepHiPartials: 4,
      drumBeepHiShimmer: 0.15,
      drumBeepHiShimmerRate: 3,
      drumBeepHiBrightness: 0.65,
    },
  },
  {
    name: 'Glass Harmonica',
    voice: 'beepHi',
    tags: ['ambient', 'ethereal', 'sustain', 'delicate'],
    params: {
      drumBeepHiFreq: 2800,
      drumBeepHiAttack: 10,
      drumBeepHiDecay: 2000,
      drumBeepHiLevel: 0.35,
      drumBeepHiTone: 0.15,
      drumBeepHiInharmonic: 0.25,
      drumBeepHiPartials: 3,
      drumBeepHiShimmer: 0.4,
      drumBeepHiShimmerRate: 4,
      drumBeepHiBrightness: 0.55,
    },
  },
  {
    name: 'Star Glint',
    voice: 'beepHi',
    tags: ['ambient', 'sparkle', 'bright', 'minimal'],
    params: {
      drumBeepHiFreq: 7000,
      drumBeepHiAttack: 0,
      drumBeepHiDecay: 100,
      drumBeepHiLevel: 0.3,
      drumBeepHiTone: 0.1,
      drumBeepHiInharmonic: 0.1,
      drumBeepHiPartials: 2,
      drumBeepHiShimmer: 0.2,
      drumBeepHiShimmerRate: 6,
      drumBeepHiBrightness: 0.9,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// BEEP LO PRESETS (10)
// ═══════════════════════════════════════════════════════════════════════════

export const BEEP_LO_PRESETS: DrumVoicePreset[] = [
  {
    name: 'Blip',
    voice: 'beepLo',
    tags: ['digital', 'minimal', 'default'],
    params: {
      drumBeepLoFreq: 400,
      drumBeepLoAttack: 2,
      drumBeepLoDecay: 100,
      drumBeepLoLevel: 0.5,
      drumBeepLoTone: 0.1,
      drumBeepLoPitchEnv: 0,
      drumBeepLoPitchDecay: 50,
      drumBeepLoBody: 0.3,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Droplet',
    voice: 'beepLo',
    tags: ['water', 'asmr', 'natural'],
    params: {
      drumBeepLoFreq: 600,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 200,
      drumBeepLoLevel: 0.5,
      drumBeepLoTone: 0,
      drumBeepLoPitchEnv: -18,  // Pitch rises
      drumBeepLoPitchDecay: 80,
      drumBeepLoBody: 0.4,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Bubble',
    voice: 'beepLo',
    tags: ['underwater', 'asmr', 'soft'],
    params: {
      drumBeepLoFreq: 350,
      drumBeepLoAttack: 5,
      drumBeepLoDecay: 300,
      drumBeepLoLevel: 0.45,
      drumBeepLoTone: 0.05,
      drumBeepLoPitchEnv: -24,
      drumBeepLoPitchDecay: 150,
      drumBeepLoBody: 0.6,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Pluck',
    voice: 'beepLo',
    tags: ['string', 'acoustic', 'ambient'],
    params: {
      drumBeepLoFreq: 500,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 400,
      drumBeepLoLevel: 0.55,
      drumBeepLoTone: 0.2,
      drumBeepLoPitchEnv: 2,
      drumBeepLoPitchDecay: 30,
      drumBeepLoBody: 0.5,
      drumBeepLoPluck: 0.8,
      drumBeepLoPluckDamp: 0.4,
    },
  },
  {
    name: 'Muted Tap',
    voice: 'beepLo',
    tags: ['soft', 'asmr', 'gentle'],
    params: {
      drumBeepLoFreq: 300,
      drumBeepLoAttack: 1,
      drumBeepLoDecay: 80,
      drumBeepLoLevel: 0.4,
      drumBeepLoTone: 0,
      drumBeepLoPitchEnv: 4,
      drumBeepLoPitchDecay: 20,
      drumBeepLoBody: 0.3,
      drumBeepLoPluck: 0.5,
      drumBeepLoPluckDamp: 0.9,
    },
  },
  {
    name: 'Bloop',
    voice: 'beepLo',
    tags: ['cartoon', 'fun', 'digital'],
    params: {
      drumBeepLoFreq: 450,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 150,
      drumBeepLoLevel: 0.5,
      drumBeepLoTone: 0.15,
      drumBeepLoPitchEnv: 36,
      drumBeepLoPitchDecay: 40,
      drumBeepLoBody: 0.4,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Ping',
    voice: 'beepLo',
    tags: ['sonar', 'pure', 'minimal'],
    params: {
      drumBeepLoFreq: 800,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 500,
      drumBeepLoLevel: 0.45,
      drumBeepLoTone: 0,
      drumBeepLoPitchEnv: 0,
      drumBeepLoPitchDecay: 50,
      drumBeepLoBody: 0.2,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Woody',
    voice: 'beepLo',
    tags: ['wood', 'percussion', 'acoustic'],
    params: {
      drumBeepLoFreq: 550,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 120,
      drumBeepLoLevel: 0.55,
      drumBeepLoTone: 0.3,
      drumBeepLoPitchEnv: 8,
      drumBeepLoPitchDecay: 15,
      drumBeepLoBody: 0.6,
      drumBeepLoPluck: 0.7,
      drumBeepLoPluckDamp: 0.3,
    },
  },
  {
    name: 'Soft Ping',
    voice: 'beepLo',
    tags: ['gentle', 'asmr', 'ambient'],
    params: {
      drumBeepLoFreq: 600,
      drumBeepLoAttack: 10,
      drumBeepLoDecay: 400,
      drumBeepLoLevel: 0.35,
      drumBeepLoTone: 0,
      drumBeepLoPitchEnv: 0,
      drumBeepLoPitchDecay: 50,
      drumBeepLoBody: 0.4,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Chirp',
    voice: 'beepLo',
    tags: ['bird', 'nature', 'texture'],
    params: {
      drumBeepLoFreq: 700,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 60,
      drumBeepLoLevel: 0.45,
      drumBeepLoTone: 0.1,
      drumBeepLoPitchEnv: -30,
      drumBeepLoPitchDecay: 25,
      drumBeepLoBody: 0.3,
      drumBeepLoPluck: 0.2,
      drumBeepLoPluckDamp: 0.4,
    },
  },
  // Organic presets
  {
    name: 'Kalimba',
    voice: 'beepLo',
    tags: ['organic', 'african', 'thumb piano', 'natural'],
    params: {
      drumBeepLoFreq: 500,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 350,
      drumBeepLoLevel: 0.55,
      drumBeepLoTone: 0.15,
      drumBeepLoPitchEnv: 3,
      drumBeepLoPitchDecay: 20,
      drumBeepLoBody: 0.4,
      drumBeepLoPluck: 0.6,
      drumBeepLoPluckDamp: 0.4,
    },
  },
  {
    name: 'Tongue Drum',
    voice: 'beepLo',
    tags: ['organic', 'steel', 'meditation', 'natural'],
    params: {
      drumBeepLoFreq: 450,
      drumBeepLoAttack: 3,
      drumBeepLoDecay: 600,
      drumBeepLoLevel: 0.5,
      drumBeepLoTone: 0.05,
      drumBeepLoPitchEnv: 0,
      drumBeepLoPitchDecay: 50,
      drumBeepLoBody: 0.55,
      drumBeepLoPluck: 0.4,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Hollow Gourd',
    voice: 'beepLo',
    tags: ['organic', 'percussion', 'natural', 'world'],
    params: {
      drumBeepLoFreq: 350,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 80,
      drumBeepLoLevel: 0.5,
      drumBeepLoTone: 0.2,
      drumBeepLoPitchEnv: 6,
      drumBeepLoPitchDecay: 15,
      drumBeepLoBody: 0.7,
      drumBeepLoPluck: 0.5,
      drumBeepLoPluckDamp: 0.6,
    },
  },
  {
    name: 'Frog Croak',
    voice: 'beepLo',
    tags: ['organic', 'animal', 'nature', 'texture'],
    params: {
      drumBeepLoFreq: 300,
      drumBeepLoAttack: 2,
      drumBeepLoDecay: 100,
      drumBeepLoLevel: 0.45,
      drumBeepLoTone: 0.15,
      drumBeepLoPitchEnv: -20,
      drumBeepLoPitchDecay: 40,
      drumBeepLoBody: 0.5,
      drumBeepLoPluck: 0.3,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  // Ambient presets
  {
    name: 'Underwater Ping',
    voice: 'beepLo',
    tags: ['ambient', 'sonar', 'muted', 'deep'],
    params: {
      drumBeepLoFreq: 500,
      drumBeepLoAttack: 5,
      drumBeepLoDecay: 700,
      drumBeepLoLevel: 0.4,
      drumBeepLoTone: 0,
      drumBeepLoPitchEnv: -6,
      drumBeepLoPitchDecay: 100,
      drumBeepLoBody: 0.6,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Cave Drip',
    voice: 'beepLo',
    tags: ['ambient', 'water', 'echo', 'natural'],
    params: {
      drumBeepLoFreq: 700,
      drumBeepLoAttack: 0,
      drumBeepLoDecay: 450,
      drumBeepLoLevel: 0.4,
      drumBeepLoTone: 0.05,
      drumBeepLoPitchEnv: -15,
      drumBeepLoPitchDecay: 60,
      drumBeepLoBody: 0.5,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
  {
    name: 'Soft Mallet',
    voice: 'beepLo',
    tags: ['ambient', 'vibraphone', 'gentle', 'warm'],
    params: {
      drumBeepLoFreq: 600,
      drumBeepLoAttack: 8,
      drumBeepLoDecay: 800,
      drumBeepLoLevel: 0.4,
      drumBeepLoTone: 0,
      drumBeepLoPitchEnv: 0,
      drumBeepLoPitchDecay: 50,
      drumBeepLoBody: 0.5,
      drumBeepLoPluck: 0.2,
      drumBeepLoPluckDamp: 0.7,
    },
  },
  {
    name: 'Hollow Echo',
    voice: 'beepLo',
    tags: ['ambient', 'resonant', 'spacious', 'deep'],
    params: {
      drumBeepLoFreq: 350,
      drumBeepLoAttack: 3,
      drumBeepLoDecay: 500,
      drumBeepLoLevel: 0.4,
      drumBeepLoTone: 0.1,
      drumBeepLoPitchEnv: -8,
      drumBeepLoPitchDecay: 80,
      drumBeepLoBody: 0.7,
      drumBeepLoPluck: 0,
      drumBeepLoPluckDamp: 0.5,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// NOISE PRESETS (12)
// ═══════════════════════════════════════════════════════════════════════════

export const NOISE_PRESETS: DrumVoicePreset[] = [
  {
    name: 'Hi-Hat',
    voice: 'noise',
    tags: ['classic', 'percussion', 'default'],
    params: {
      drumNoiseFilterFreq: 8000,
      drumNoiseFilterQ: 1,
      drumNoiseFilterType: 'highpass',
      drumNoiseDecay: 30,
      drumNoiseLevel: 0.4,
      drumNoiseAttack: 0,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0,
      drumNoiseFilterEnvDecay: 100,
      drumNoiseDensity: 1,
      drumNoiseColorLFO: 0,
    },
  },
  {
    name: 'Breath',
    voice: 'noise',
    tags: ['asmr', 'soft', 'air'],
    params: {
      drumNoiseFilterFreq: 2000,
      drumNoiseFilterQ: 2,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 300,
      drumNoiseLevel: 0.35,
      drumNoiseAttack: 50,
      drumNoiseFormant: 0.2,
      drumNoiseBreath: 0.7,
      drumNoiseFilterEnv: 0.3,
      drumNoiseFilterEnvDecay: 200,
      drumNoiseDensity: 0.8,
      drumNoiseColorLFO: 0.5,
    },
  },
  {
    name: 'Whisper',
    voice: 'noise',
    tags: ['asmr', 'voice', 'texture'],
    params: {
      drumNoiseFilterFreq: 1500,
      drumNoiseFilterQ: 4,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 200,
      drumNoiseLevel: 0.3,
      drumNoiseAttack: 20,
      drumNoiseFormant: 0.6,
      drumNoiseBreath: 0.5,
      drumNoiseFilterEnv: 0.2,
      drumNoiseFilterEnvDecay: 150,
      drumNoiseDensity: 0.7,
      drumNoiseColorLFO: 1,
    },
  },
  {
    name: 'Dust',
    voice: 'noise',
    tags: ['vinyl', 'sparse', 'texture'],
    params: {
      drumNoiseFilterFreq: 5000,
      drumNoiseFilterQ: 0.8,
      drumNoiseFilterType: 'highpass',
      drumNoiseDecay: 10,
      drumNoiseLevel: 0.25,
      drumNoiseAttack: 0,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0,
      drumNoiseFilterEnvDecay: 50,
      drumNoiseDensity: 0.2,
      drumNoiseColorLFO: 0,
    },
  },
  {
    name: 'Texture',
    voice: 'noise',
    tags: ['ambient', 'drone', 'background'],
    params: {
      drumNoiseFilterFreq: 3000,
      drumNoiseFilterQ: 2,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 800,
      drumNoiseLevel: 0.3,
      drumNoiseAttack: 100,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.3,
      drumNoiseFilterEnv: 0,
      drumNoiseFilterEnvDecay: 400,
      drumNoiseDensity: 0.6,
      drumNoiseColorLFO: 0.3,
    },
  },
  {
    name: 'Scrape',
    voice: 'noise',
    tags: ['friction', 'texture', 'industrial'],
    params: {
      drumNoiseFilterFreq: 4000,
      drumNoiseFilterQ: 3,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 150,
      drumNoiseLevel: 0.4,
      drumNoiseAttack: 5,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: -0.6,
      drumNoiseFilterEnvDecay: 100,
      drumNoiseDensity: 0.9,
      drumNoiseColorLFO: 2,
    },
  },
  {
    name: 'Hiss',
    voice: 'noise',
    tags: ['white', 'bright', 'electronic'],
    params: {
      drumNoiseFilterFreq: 10000,
      drumNoiseFilterQ: 0.5,
      drumNoiseFilterType: 'highpass',
      drumNoiseDecay: 100,
      drumNoiseLevel: 0.35,
      drumNoiseAttack: 0,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0,
      drumNoiseFilterEnvDecay: 100,
      drumNoiseDensity: 1,
      drumNoiseColorLFO: 0,
    },
  },
  {
    name: 'Shaker',
    voice: 'noise',
    tags: ['percussion', 'latin', 'rhythm'],
    params: {
      drumNoiseFilterFreq: 6000,
      drumNoiseFilterQ: 1.5,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 80,
      drumNoiseLevel: 0.4,
      drumNoiseAttack: 2,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0.2,
      drumNoiseFilterEnvDecay: 50,
      drumNoiseDensity: 0.85,
      drumNoiseColorLFO: 0,
    },
  },
  {
    name: 'Ocean Spray',
    voice: 'noise',
    tags: ['water', 'ambient', 'nature'],
    params: {
      drumNoiseFilterFreq: 2500,
      drumNoiseFilterQ: 1,
      drumNoiseFilterType: 'lowpass',
      drumNoiseDecay: 1500,
      drumNoiseLevel: 0.3,
      drumNoiseAttack: 200,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.4,
      drumNoiseFilterEnv: 0.4,
      drumNoiseFilterEnvDecay: 600,
      drumNoiseDensity: 0.7,
      drumNoiseColorLFO: 0.2,
    },
  },
  {
    name: 'Steam',
    voice: 'noise',
    tags: ['pressure', 'industrial', 'texture'],
    params: {
      drumNoiseFilterFreq: 3500,
      drumNoiseFilterQ: 2,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 400,
      drumNoiseLevel: 0.4,
      drumNoiseAttack: 10,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.2,
      drumNoiseFilterEnv: 0.7,
      drumNoiseFilterEnvDecay: 200,
      drumNoiseDensity: 0.9,
      drumNoiseColorLFO: 1.5,
    },
  },
  {
    name: 'Rustle',
    voice: 'noise',
    tags: ['leaves', 'nature', 'asmr'],
    params: {
      drumNoiseFilterFreq: 4000,
      drumNoiseFilterQ: 1.5,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 200,
      drumNoiseLevel: 0.3,
      drumNoiseAttack: 30,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.1,
      drumNoiseFilterEnv: 0.1,
      drumNoiseFilterEnvDecay: 150,
      drumNoiseDensity: 0.4,
      drumNoiseColorLFO: 0.8,
    },
  },
  {
    name: 'Static',
    voice: 'noise',
    tags: ['electronic', 'radio', 'texture'],
    params: {
      drumNoiseFilterFreq: 5000,
      drumNoiseFilterQ: 2,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 150,
      drumNoiseLevel: 0.35,
      drumNoiseAttack: 0,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0,
      drumNoiseFilterEnvDecay: 100,
      drumNoiseDensity: 1,
      drumNoiseColorLFO: 4,
    },
  },
  // Organic presets
  {
    name: 'Wind Gust',
    voice: 'noise',
    tags: ['organic', 'wind', 'nature', 'ambient'],
    params: {
      drumNoiseFilterFreq: 2000,
      drumNoiseFilterQ: 1,
      drumNoiseFilterType: 'lowpass',
      drumNoiseDecay: 1000,
      drumNoiseLevel: 0.3,
      drumNoiseAttack: 150,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.6,
      drumNoiseFilterEnv: 0.3,
      drumNoiseFilterEnvDecay: 500,
      drumNoiseDensity: 0.8,
      drumNoiseColorLFO: 0.4,
    },
  },
  {
    name: 'Rain Patter',
    voice: 'noise',
    tags: ['organic', 'water', 'rain', 'nature'],
    params: {
      drumNoiseFilterFreq: 4000,
      drumNoiseFilterQ: 1.5,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 60,
      drumNoiseLevel: 0.35,
      drumNoiseAttack: 2,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.1,
      drumNoiseFilterEnv: 0.15,
      drumNoiseFilterEnvDecay: 40,
      drumNoiseDensity: 0.3,
      drumNoiseColorLFO: 0,
    },
  },
  {
    name: 'Bonfire Crackle',
    voice: 'noise',
    tags: ['organic', 'fire', 'campfire', 'nature'],
    params: {
      drumNoiseFilterFreq: 5500,
      drumNoiseFilterQ: 2,
      drumNoiseFilterType: 'highpass',
      drumNoiseDecay: 40,
      drumNoiseLevel: 0.4,
      drumNoiseAttack: 0,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0.5,
      drumNoiseFilterEnvDecay: 30,
      drumNoiseDensity: 0.2,
      drumNoiseColorLFO: 3,
    },
  },
  {
    name: 'Leaf Crunch',
    voice: 'noise',
    tags: ['organic', 'forest', 'foliage', 'texture'],
    params: {
      drumNoiseFilterFreq: 3500,
      drumNoiseFilterQ: 2.5,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 50,
      drumNoiseLevel: 0.4,
      drumNoiseAttack: 0,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0.3,
      drumNoiseFilterEnvDecay: 30,
      drumNoiseDensity: 0.4,
      drumNoiseColorLFO: 0.5,
    },
  },
  {
    name: 'Sand Shuffle',
    voice: 'noise',
    tags: ['organic', 'beach', 'gravel', 'texture'],
    params: {
      drumNoiseFilterFreq: 3000,
      drumNoiseFilterQ: 1.5,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 200,
      drumNoiseLevel: 0.35,
      drumNoiseAttack: 10,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.15,
      drumNoiseFilterEnv: 0.1,
      drumNoiseFilterEnvDecay: 80,
      drumNoiseDensity: 0.5,
      drumNoiseColorLFO: 0.2,
    },
  },
  // Ambient presets
  {
    name: 'White Mist',
    voice: 'noise',
    tags: ['ambient', 'fog', 'soft', 'atmospheric'],
    params: {
      drumNoiseFilterFreq: 1500,
      drumNoiseFilterQ: 0.8,
      drumNoiseFilterType: 'lowpass',
      drumNoiseDecay: 2000,
      drumNoiseLevel: 0.25,
      drumNoiseAttack: 300,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.4,
      drumNoiseFilterEnv: 0.2,
      drumNoiseFilterEnvDecay: 800,
      drumNoiseDensity: 0.9,
      drumNoiseColorLFO: 0.2,
    },
  },
  {
    name: 'Distant Surf',
    voice: 'noise',
    tags: ['ambient', 'ocean', 'waves', 'nature'],
    params: {
      drumNoiseFilterFreq: 2000,
      drumNoiseFilterQ: 1,
      drumNoiseFilterType: 'lowpass',
      drumNoiseDecay: 2500,
      drumNoiseLevel: 0.25,
      drumNoiseAttack: 400,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.5,
      drumNoiseFilterEnv: 0.35,
      drumNoiseFilterEnvDecay: 1000,
      drumNoiseDensity: 0.75,
      drumNoiseColorLFO: 0.3,
    },
  },
  {
    name: 'Tape Hiss',
    voice: 'noise',
    tags: ['ambient', 'analog', 'warm', 'texture'],
    params: {
      drumNoiseFilterFreq: 6000,
      drumNoiseFilterQ: 0.5,
      drumNoiseFilterType: 'highpass',
      drumNoiseDecay: 500,
      drumNoiseLevel: 0.15,
      drumNoiseAttack: 50,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0,
      drumNoiseFilterEnv: 0,
      drumNoiseFilterEnvDecay: 100,
      drumNoiseDensity: 1,
      drumNoiseColorLFO: 0,
    },
  },
  {
    name: 'Forest Ambience',
    voice: 'noise',
    tags: ['ambient', 'nature', 'background', 'texture'],
    params: {
      drumNoiseFilterFreq: 3000,
      drumNoiseFilterQ: 1.5,
      drumNoiseFilterType: 'bandpass',
      drumNoiseDecay: 1500,
      drumNoiseLevel: 0.25,
      drumNoiseAttack: 200,
      drumNoiseFormant: 0,
      drumNoiseBreath: 0.3,
      drumNoiseFilterEnv: 0.15,
      drumNoiseFilterEnvDecay: 600,
      drumNoiseDensity: 0.5,
      drumNoiseColorLFO: 0.6,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// COMBINED PRESET ACCESS
// ═══════════════════════════════════════════════════════════════════════════

export const DRUM_VOICE_PRESETS: Record<DrumVoiceType, DrumVoicePreset[]> = {
  sub: SUB_PRESETS,
  kick: KICK_PRESETS,
  click: CLICK_PRESETS,
  beepHi: BEEP_HI_PRESETS,
  beepLo: BEEP_LO_PRESETS,
  noise: NOISE_PRESETS,
};

/**
 * Get a preset by name and voice type
 */
export function getPreset(voice: DrumVoiceType, name: string): DrumVoicePreset | undefined {
  return DRUM_VOICE_PRESETS[voice].find(p => p.name === name);
}

/**
 * Get all preset names for a voice type
 */
export function getPresetNames(voice: DrumVoiceType): string[] {
  return DRUM_VOICE_PRESETS[voice].map(p => p.name);
}

/**
 * Get presets by tag
 */
export function getPresetsByTag(voice: DrumVoiceType, tag: string): DrumVoicePreset[] {
  return DRUM_VOICE_PRESETS[voice].filter(p => p.tags.includes(tag));
}
