import type { DynamicsTargets } from './dynamicsModel';

export const DYNAMICS_CHARACTER_PARAM_ORDER = [
  'active',
  'allpassActive',
  'dry',
  'wet',
  'degradeMix',
  'workletAlias',
  'rawDegradeGeneration',
  'rawCorrosion',
  'rawMediaWear',
  'noiseGain',
  'jitterDepth',
  'randomDriftFilterHz',
  'randomDriftDepth',
  'baseDelay',
  'spreadBaseDelay',
  'randomDrift',
  'randomHoldRateHz',
  'randomHoldLag',
  'randomDelayDepth',
  'randomSpreadDelayDepth',
  'randomFilterDepth',
  'randomSpreadFilterDepth',
  'depth',
  'rate',
  'shallowFlavor',
  'abyssFlavor',
  'stereo',
  'damage',
  'mainPan',
  'spreadPan',
  'mainDelayGain',
  'spreadDelayGain',
  'wowFrequency',
  'flutterFrequency',
  'flutterRandomDepth',
  'wowDepth',
  'flutterDepth',
  'highpassHz',
  'highpassQ',
  'allpassAFrequency',
  'allpassAQ',
  'allpassBFrequency',
  'allpassBQ',
  'headBumpFrequency',
  'headBumpQ',
  'headBumpGain',
  'dropoutFilterHz',
  'dropoutDepth',
  'dropoutGain',
  'envFilterHz',
  'envToLowpassGain',
  'envToResonanceGain',
  'envToWetGain',
  'lowpassHz',
  'lowpassQ',
  'lowpassStage2Hz',
  'lowpassStage2Q',
  'compressorThreshold',
  'compressorKnee',
  'compressorRatio',
  'compressorAttack',
  'compressorRelease',
  'compressorMakeup',
  'saturation',
  'corrosion',
  'masterSatActive',
  'masterSatMode',
  'masterSatDrive',
  'masterSatTone',
  'masterSatBias',
  'endCompActive',
  'endCompThreshold',
  'endCompKnee',
  'endCompRatio',
  'endCompAttack',
  'endCompRelease',
  'endCompMakeup',
  'endCompMix',
  'endCompDetectorHpHz',
  'endCompDetectorTilt',
  'endCompAutoMakeup',
  'endCompProgramRelease',
] as const;

export type DynamicsCharacterParamName = (typeof DYNAMICS_CHARACTER_PARAM_ORDER)[number];
export type DynamicsCharacterParams = Record<DynamicsCharacterParamName, number>;

function finiteParam(value: number): number {
  return Number.isFinite(value) ? value : 0;
}

export function toDynamicsCharacterParamObject(targets: DynamicsTargets): DynamicsCharacterParams {
  return {
    active: targets.routing.characterPathActive ? 1 : 0,
    allpassActive: targets.routing.allpassStackActive ? 1 : 0,
    dry: targets.dry,
    wet: targets.wet,
    degradeMix: targets.degradeWetRatio,
    workletAlias: targets.workletAlias,
    rawDegradeGeneration: targets.rawDegradeGeneration,
    rawCorrosion: targets.rawCorrosion,
    rawMediaWear: targets.rawMediaWear,
    noiseGain: targets.noiseGain,
    jitterDepth: targets.jitterDepth,
    randomDriftFilterHz: targets.randomDriftFilterHz,
    randomDriftDepth: targets.randomDriftDepth,
    baseDelay: targets.baseDelay,
    spreadBaseDelay: targets.spreadBaseDelay,
    randomDrift: targets.randomDrift,
    randomHoldRateHz: targets.randomHoldRateHz,
    randomHoldLag: targets.randomHoldLag,
    randomDelayDepth: targets.randomDelayDepth,
    randomSpreadDelayDepth: targets.randomSpreadDelayDepth,
    randomFilterDepth: targets.randomFilterDepth,
    randomSpreadFilterDepth: targets.randomSpreadFilterDepth,
    depth: targets.depth,
    rate: targets.rate,
    shallowFlavor: targets.shallowFlavor,
    abyssFlavor: targets.abyssFlavor,
    stereo: targets.stereo,
    damage: targets.damage,
    mainPan: targets.mainPan,
    spreadPan: targets.spreadPan,
    mainDelayGain: targets.mainDelayGain,
    spreadDelayGain: targets.spreadDelayGain,
    wowFrequency: targets.wowFrequency,
    flutterFrequency: targets.flutterFrequency,
    flutterRandomDepth: targets.flutterRandomDepth,
    wowDepth: targets.wowDepth,
    flutterDepth: targets.flutterDepth,
    highpassHz: targets.highpassHz,
    highpassQ: targets.highpassQ,
    allpassAFrequency: targets.allpassAFrequency,
    allpassAQ: targets.allpassAQ,
    allpassBFrequency: targets.allpassBFrequency,
    allpassBQ: targets.allpassBQ,
    headBumpFrequency: targets.headBumpFrequency,
    headBumpQ: targets.headBumpQ,
    headBumpGain: targets.headBumpGain,
    dropoutFilterHz: targets.dropoutFilterHz,
    dropoutDepth: targets.dropoutDepth,
    dropoutGain: targets.dropoutGain,
    envFilterHz: targets.envFilterHz,
    envToLowpassGain: targets.envToLowpassGain,
    envToResonanceGain: targets.envToResonanceGain,
    envToWetGain: targets.envToWetGain,
    lowpassHz: targets.lowpassHz,
    lowpassQ: targets.lowpassQ,
    lowpassStage2Hz: targets.lowpassStage2Hz,
    lowpassStage2Q: targets.lowpassStage2Q,
    compressorThreshold: targets.compressorThreshold,
    compressorKnee: targets.compressorKnee,
    compressorRatio: targets.compressorRatio,
    compressorAttack: targets.compressorAttack,
    compressorRelease: targets.compressorRelease,
    compressorMakeup: targets.compressorMakeup,
    saturation: targets.saturation,
    corrosion: targets.corrosion,
    masterSatActive: targets.masterSatActive ? 1 : 0,
    masterSatMode: targets.masterSatMode,
    masterSatDrive: targets.masterSatDrive,
    masterSatTone: targets.masterSatTone,
    masterSatBias: targets.masterSatBias,
    endCompActive: targets.routing.endChainActive ? 1 : 0,
    endCompThreshold: targets.endThreshold,
    endCompKnee: targets.endKnee,
    endCompRatio: targets.endRatio,
    endCompAttack: targets.endAttack,
    endCompRelease: targets.endRelease,
    endCompMakeup: targets.endMakeup,
    endCompMix: targets.endWet,
    endCompDetectorHpHz: targets.endDetectorHpHz,
    endCompDetectorTilt: targets.endDetectorTilt,
    endCompAutoMakeup: targets.endAutoMakeup,
    endCompProgramRelease: targets.endProgramRelease,
  };
}

export function toDynamicsCharacterParamArray(targets: DynamicsTargets): number[] {
  const params = toDynamicsCharacterParamObject(targets);
  return DYNAMICS_CHARACTER_PARAM_ORDER.map((name) => finiteParam(params[name]));
}
