export const STEM_RECORD_TRACK_IDS = [
  'pad1',
  'pad2',
  'lead1',
  'lead2',
  'piano',
  'drums',
  'granular',
  'waves',
  'water',
  'insects',
  'nature',
  'delayAOut',
  'delayBOut',
  'reverb',
  'dynamics',
] as const;

export type StemRecordTrackId = typeof STEM_RECORD_TRACK_IDS[number];
export type RecordTrackId = 'mix' | StemRecordTrackId;

export const STEM_RECORD_TRACK_LABELS: Record<StemRecordTrackId, string> = {
  pad1: 'Pad 1',
  pad2: 'Pad 2',
  lead1: 'Lead 1',
  lead2: 'Lead 2',
  piano: 'Piano',
  drums: 'Drums',
  granular: 'Granular',
  waves: 'Waves',
  water: 'Water',
  insects: 'Insects',
  nature: 'Nature',
  delayAOut: 'Delay A',
  delayBOut: 'Delay B',
  reverb: 'Reverb',
  dynamics: 'Texture',
};

export const STEM_RECORD_DEFAULTS: Record<StemRecordTrackId, boolean> = {
  pad1: false,
  pad2: false,
  lead1: false,
  lead2: false,
  piano: false,
  drums: false,
  granular: false,
  waves: false,
  water: false,
  insects: false,
  nature: false,
  delayAOut: false,
  delayBOut: false,
  reverb: false,
  dynamics: false,
};

export const RECORD_TRACK_FILENAME_SUFFIX: Record<RecordTrackId, string> = {
  mix: '',
  pad1: 'pad-1',
  pad2: 'pad-2',
  lead1: 'lead-1',
  lead2: 'lead-2',
  piano: 'piano',
  drums: 'drums',
  granular: 'granular',
  waves: 'waves',
  water: 'water',
  insects: 'insects',
  nature: 'nature',
  delayAOut: 'delay-a',
  delayBOut: 'delay-b',
  reverb: 'reverb',
  dynamics: 'dynamics',
};

export const SOUND_SOURCE_RECORDING_ROLLUPS = {
  pad1: 'pad1',
  pad2: 'pad2',
  lead1: 'lead1',
  lead2: 'lead2',
  piano: 'piano',

  sub: 'drums',
  kick: 'drums',
  click: 'drums',
  beepHi: 'drums',
  beepLo: 'drums',
  noise: 'drums',
  membrane: 'drums',
  drumSub: 'drums',
  drumKick: 'drums',
  drumClick: 'drums',
  drumBeepHi: 'drums',
  drumBeepLo: 'drums',
  drumNoise: 'drums',
  drumMembrane: 'drums',

  granularV1: 'granular',
  granularV2: 'granular',
  granularV3: 'granular',
  granularV4: 'granular',
  granularVoice1: 'granular',
  granularVoice2: 'granular',
  granularVoice3: 'granular',
  granularVoice4: 'granular',

  waves: 'waves',
  hardDrops: 'water',
  waterLayerHardDrops: 'water',
  waterHardDrops: 'water',
  waterLayerWaterDrops: 'water',
  waterDrops: 'water',
  waterLayerBubbling: 'water',
  waterBubbling: 'water',
  waterLayerTurbulence: 'water',
  waterTurbulence: 'water',
  waterLayerChannels: 'water',
  waterChannels: 'water',
  waterLayerSurf: 'water',
  waterSurf: 'water',
  bubbling: 'water',
  turbulence: 'water',
  channels: 'water',
  surf: 'water',
  insects: 'insects',
  insects1: 'insects',
  insects2: 'insects',
  birds: 'nature',
  birds2: 'nature',
  birdsAlps: 'nature',
  birdsFujian: 'nature',
  frogs: 'nature',

  delayA: 'delayAOut',
  delayB: 'delayBOut',
  reverb: 'reverb',
  dynamics: 'dynamics',
} satisfies Record<string, StemRecordTrackId>;
