const statePatch = {
  padEnabled: true,
  synthLevel: 0.5,
  masterVolume: 0.75,
  reverbEnabled: false,
  delayAEnabled: false,
  granularEnabled: false,
  spectralFreezeEnabled: false,
  dynamicsEnabled: false,
  characterEnabled: false,
  sidechainEnabled: false,
  drumEnabled: false,
  waterEnabled: false,
  insectsEnabled: false,
  insects2Enabled: false,
  oceanSampleEnabled: false,
  oceanSampleLevel: 0,
  birdsEnabled: false,
  birdsLevel: 0,
  birds2Enabled: false,
  birds2Level: 0,
  frogsEnabled: false,
  frogsLevel: 0,
  natureLevel: 0,
  earthLevel: 1,
  leadEnabled: false,
  lead2Enabled: false,
  pianoEnabled: false,
  synthChordSequencerEnabled: false,
  synthEuclideanMasterEnabled: false,
};

const delayAStatePatch = {
  ...statePatch,
  delayAEnabled: true,
  delayAMix: 0.5,
  delayAFeedback: 0,
  delayAFilter: 8000,
  delayAPingPong: false,
  delayAModDepth: 0,
  delayADuck: 0,
  delayAWidth: 0.5,
  drumDelayNoteL: '1/32',
  drumDelayNoteR: '1/32',
  pad1DelayASend: 0.7,
};

const delayBStatePatch = {
  ...statePatch,
  granularDelayEnabled: true,
  granularDelayMix: 0.5,
  granularDelayActivity: 1,
  granularDelayRepeats: 0,
  granularDelayTime: '1/32',
  granularDelayFilter: 1,
  granularDelayVibrato: 0,
  granularSpaceMode: 'cascade',
  delayBPattern: 'cascade',
  delayBWarp: 'clean',
  delayBWarpIntensity: 0,
  delayBSpread: 0.5,
  pad1DelayBSend: 0.7,
};

const delayBidirectionalStatePatch = {
  ...delayAStatePatch,
  granularDelayEnabled: true,
  granularDelayMix: 0,
  granularDelayActivity: 1,
  granularDelayRepeats: 0,
  granularDelayTime: '1/32',
  granularDelayFilter: 1,
  granularDelayVibrato: 0,
  granularSpaceMode: 'cascade',
  delayBPattern: 'cascade',
  delayBWarp: 'clean',
  delayBWarpIntensity: 0,
  delayBSpread: 0.5,
  delayAMix: 0,
  pad1DelayBSend: 0.7,
  delayAToBSend: 0.8,
  delayBToASend: 0.8,
  delayACrossFeedFilter: 1,
};

const granularCleanOutputStatePatch = {
  ...statePatch,
  granularEnabled: true,
  granularLevel: 1,
  granularPad1Send: 1,
  granularReverbSend: 0,
  granularFeedback: 0,
  granularFeedbackLPF: 12000,
  granularBufferSeconds: 4,
  granularShape: 'triangle',
  granularV1Enabled: true,
  granularV1Mode: 'clean',
  granularV1Slice: 1,
  granularV1Speed: 1,
  granularV1ScanRate: 1,
  granularV1Reverse: false,
  granularV1Pitch: 0,
  granularV1Attack: 0.003,
  granularV1Decay: 1,
  granularV1Blur: 0,
  granularV1GrainOct: 0,
  granularV1Spray: 0,
  granularV1Density: 64,
  granularV1GrainSize: 300,
  granularV1Pan: 0,
  granularV1Gain: 1,
  granularV1PosLFORate: 0,
  granularV1PosLFODepth: 0,
  granularV1PanLFORate: 0,
  granularV1StereoSpread: 0,
  granularV1ReverseLFORate: 0,
  granularV1WriteFollow: 1,
  granularV1RecordLFORate: 0,
  granularV2Enabled: false,
  granularV3Enabled: false,
  granularV4Enabled: false,
};

const granularTwoVoiceCleanOutputStatePatch = {
  ...granularCleanOutputStatePatch,
  granularLevel: 0.72,
  granularV2Enabled: true,
  granularV2Mode: 'clean',
  granularV2Slice: 5,
  granularV2Speed: 1,
  granularV2ScanRate: 1,
  granularV2Reverse: false,
  granularV2Pitch: 7,
  granularV2Attack: 0.004,
  granularV2Decay: 0.85,
  granularV2Blur: 0,
  granularV2GrainOct: 0,
  granularV2Spray: 0,
  granularV2Density: 48,
  granularV2GrainSize: 260,
  granularV2Pan: 0,
  granularV2Gain: 0.58,
  granularV2PosLFORate: 0,
  granularV2PosLFODepth: 0,
  granularV2PanLFORate: 0,
  granularV2StereoSpread: 0,
  granularV2ReverseLFORate: 0,
  granularV2WriteFollow: 1,
  granularV2RecordLFORate: 0,
};

const granularModulatedCleanOutputStatePatch = {
  ...granularCleanOutputStatePatch,
  granularLevel: 0.66,
  granularV1Slice: 3,
  granularV1Speed: 0.85,
  granularV1ScanRate: 1.35,
  granularV1Pitch: 5,
  granularV1Pan: -0.18,
  granularV1Gain: 0.86,
  granularV1PosLFORate: 0.34,
  granularV1PosLFODepth: 0.28,
  granularV1PanLFORate: 0.24,
  granularV1StereoSpread: 0.42,
  granularV1RecordLFORate: 0.16,
  granularMacroActivity: 0,
  granularMacroTexture: 0,
  granularMacroComplexity: 0,
  granularMacroChaos: 0,
  granularDiffusion: 0,
  granularPresetBehavior: 'pure',
  granularTensionMode: 'bypass',
};

const granularFeedbackOutputStatePatch = {
  ...granularCleanOutputStatePatch,
  granularLevel: 0.58,
  granularFeedback: 0.34,
  granularFeedbackLPF: 5200,
  granularV1Slice: 2,
  granularV1WriteFollow: 0.72,
  granularV1Decay: 1.3,
  granularV1Gain: 0.82,
  granularV1PosLFORate: 0,
  granularV1PosLFODepth: 0,
  granularV1PanLFORate: 0,
  granularV1RecordLFORate: 0,
  granularMacroActivity: 0,
  granularMacroTexture: 0,
  granularMacroComplexity: 0,
  granularMacroChaos: 0,
  granularDiffusion: 0,
  granularPresetBehavior: 'pure',
  granularTensionMode: 'bypass',
};

const granularDelayedFreezeOutputStatePatch = {
  ...granularCleanOutputStatePatch,
  granularLevel: 0.54,
  granularFeedback: 0,
  granularFreeze: false,
  granularV1Slice: 2,
  granularV1WriteFollow: 0.88,
  granularV1Decay: 1.45,
  granularV1Gain: 0.86,
  granularMacroActivity: 0,
  granularMacroTexture: 0,
  granularMacroComplexity: 0,
  granularMacroChaos: 0,
  granularDiffusion: 0,
  granularPresetBehavior: 'pure',
  granularTensionMode: 'bypass',
};

const granularLegacyCloudOutputStatePatch = {
  granularEnabled: true,
  granularPreset: 'legacy_cloud',
  granularPresetBehavior: 'pure',
  granularLevel: 1,
  granularPad1Send: 1,
  pad2Level: 0,
  lead1Level: 0,
  lead2Level: 0,
  pianoLevel: 0,
  drumLevel: 0,
  reverbEnabled: false,
  delayAEnabled: false,
  granularDelayEnabled: false,
  spectralFreezeEnabled: false,
  dynamicsEnabled: false,
  characterEnabled: false,
  sidechainEnabled: false,
  granularV1Mode: 'legacy',
  granularV1Density: 20,
  granularV1GrainSize: 80,
  granularV1Spray: 0.3,
  granularLegacyJitter: 10,
  granularLegacyProbability: 0.8,
  granularLegacyPitchMode: 'harmonic',
  granularLegacyPitchSpread: 2,
  granularLegacyMaxGrains: 64,
  granularLegacyFeedback: 0.1,
  seed: 42,
  seedWindow: 'day',
};

const activeDynamicsStatePatch = {
  ...statePatch,
  dynamicsEnabled: true,
  characterEnabled: true,
  characterMix: 0.45,
  characterMode: 'shallowWater',
  characterAge: 0.25,
  characterDepth: 0.35,
  characterRate: 0.2,
  characterStereo: 0.2,
  endCompEnabled: false,
  degradeEnabled: false,
  dynamicsSaturationEnabled: false,
};

const dynamicsSaturationStatePatch = {
  ...statePatch,
  dynamicsEnabled: true,
  characterEnabled: false,
  degradeEnabled: false,
  dynamicsSaturationEnabled: true,
  dynamicsSaturationMode: 'tube',
  dynamicsSaturationDrive: 0.38,
  dynamicsSaturationTone: 0.62,
  dynamicsSaturationBias: 0.54,
  endCompEnabled: false,
};

const dynamicsEndCompStatePatch = {
  ...statePatch,
  dynamicsEnabled: true,
  characterEnabled: false,
  degradeEnabled: false,
  dynamicsSaturationEnabled: false,
  endCompEnabled: true,
  endCompThreshold: -28,
  endCompKnee: 10,
  endCompRatio: 3,
  endCompAttackMs: 8,
  endCompReleaseMs: 180,
  endCompMakeup: 1.08,
  endCompMix: 0.72,
  endCompDetectorHp: 0.18,
  endCompDetectorTilt: 0.58,
  endCompAutoMakeup: 0.35,
  endCompProgramRelease: 0.4,
};

const dynamicsSatEndCompStatePatch = {
  ...dynamicsEndCompStatePatch,
  dynamicsSaturationEnabled: true,
  dynamicsSaturationMode: 'tape',
  dynamicsSaturationDrive: 0.32,
  dynamicsSaturationTone: 0.58,
  dynamicsSaturationBias: 0.5,
  endCompThreshold: -24,
  endCompRatio: 2.4,
  endCompMix: 0.62,
};

const sidechainStatePatch = {
  ...statePatch,
  sidechainEnabled: true,
  sidechainKeyA: 'kick',
  sidechainKeyB: 'off',
  sidechainKeyAWeight: 1,
  sidechainKeyBWeight: 0,
  sidechainAmount: 1,
  sidechainThreshold: -60,
  sidechainRatio: 20,
  sidechainKnee: 0,
  sidechainAttackMs: 18,
  sidechainHoldMs: 70,
  sidechainReleaseMs: 260,
  sidechainMakeup: 1,
  sidechainMix: 1,
  sidechainCurve: 0.5,
  sidechainPad1Target: 0,
  sidechainPad2Target: 0,
  sidechainLead1Target: 0,
  sidechainLead2Target: 0,
  sidechainPianoTarget: 0,
  sidechainGranularTarget: 0,
  sidechainDelayATarget: 0,
  sidechainDelayBTarget: 0,
  sidechainReverbTarget: 0,
};

const sidechainTargetStatePatch = (targetKey, sourcePatch = {}) => ({
  ...sidechainStatePatch,
  ...sourcePatch,
  sidechainEnabled: true,
  sidechainKeyA: 'kick',
  sidechainKeyB: 'off',
  sidechainKeyAWeight: 1,
  sidechainKeyBWeight: 0,
  sidechainAmount: 1,
  sidechainThreshold: -60,
  sidechainRatio: 20,
  sidechainKnee: 0,
  sidechainAttackMs: 18,
  sidechainHoldMs: 70,
  sidechainReleaseMs: 260,
  sidechainMakeup: 1,
  sidechainMix: 1,
  sidechainCurve: 0.5,
  sidechainPad1Target: targetKey === 'sidechainPad1Target' ? 1 : 0,
  sidechainPad2Target: targetKey === 'sidechainPad2Target' ? 1 : 0,
  sidechainLead1Target: targetKey === 'sidechainLead1Target' ? 1 : 0,
  sidechainLead2Target: targetKey === 'sidechainLead2Target' ? 1 : 0,
  sidechainPianoTarget: targetKey === 'sidechainPianoTarget' ? 1 : 0,
  sidechainGranularTarget: targetKey === 'sidechainGranularTarget' ? 1 : 0,
  sidechainDelayATarget: targetKey === 'sidechainDelayATarget' ? 1 : 0,
  sidechainDelayBTarget: targetKey === 'sidechainDelayBTarget' ? 1 : 0,
  sidechainReverbTarget: targetKey === 'sidechainReverbTarget' ? 1 : 0,
});

const diffusePadStatePatch = {
  ...statePatch,
  padDiffuseSend: 0.7,
};

const diffusePadDistanceStatePatch = {
  ...diffusePadStatePatch,
  padDistance: 0.65,
};

const diffuseModulatedSourceStatePatch = {
  ...statePatch,
  synthLevel: 0.45,
  masterVolume: 0.78,
  padMorph: 0.72,
  padDiffuseSend: 0.55,
  padDistance: 0.35,
  pad2Enabled: true,
  pad2Level: 0.38,
  pad2Morph: 0.64,
  pad2DiffuseSend: 0.45,
  leadEnabled: true,
  lead1Level: 0.32,
  lead1Morph: 0.58,
  lead1DiffuseSend: 0.35,
  lead1Distance: 0.25,
  diffuseEnabled: true,
  diffuseWet: 0.45,
  diffusePreDelay: 0.01,
  diffuseSpread: 0.75,
  diffuseSize: 0.62,
  diffuseTone: 0.58,
  reverbMix: 0.1,
};

const diffuseAllSourceDistanceStatePatch = {
  ...statePatch,
  synthLevel: 0.42,
  masterVolume: 0.78,
  padMorph: 0.68,
  padDiffuseSend: 0.58,
  padDistance: 0.55,
  pad2Enabled: true,
  pad2Level: 0.34,
  pad2Morph: 0.58,
  pad2DiffuseSend: 0.5,
  pad2Distance: 0.48,
  leadEnabled: true,
  lead2Enabled: true,
  lead1Level: 0.28,
  lead1Morph: 0.5,
  lead1DiffuseSend: 0.42,
  lead1Distance: 0.42,
  lead2Level: 0.24,
  lead2Morph: 0.52,
  lead2DiffuseSend: 0.38,
  lead2Distance: 0.5,
  pianoEnabled: true,
  pianoLevel: 0.32,
  pianoDiffuseSend: 0.36,
  pianoDistance: 0.5,
  pianoPostLPF: 14000,
  pianoStereoWidth: 0.85,
  diffuseEnabled: true,
  diffuseWet: 0.42,
  diffusePreDelay: 0.012,
  diffuseSpread: 0.68,
  diffuseSize: 0.6,
  diffuseTone: 0.62,
  reverbMix: 0.1,
};

const spectralFreezePreStatePatch = {
  ...statePatch,
  reverbEnabled: true,
  reverbLevel: 0,
  pad1ReverbSend: 0.45,
  synthReverbSend: 0.45,
  spectralFreezeEnabled: true,
  spectralFreezeActive: false,
  spectralFreezeSlushy: false,
  spectralFreezeMix: 1,
  spectralFreezeSpeed: 0.3,
  spectralFreezeDecay: 1,
  spectralFreezePhaseJitter: 0,
  spectralFreezeRouting: 'pre',
  spectralFreezeReverbCrossfade: 1,
};

const spectralFreezePostStatePatch = {
  ...spectralFreezePreStatePatch,
  spectralFreezeRouting: 'post',
};

const spectralFreezePreAudibleStatePatch = {
  ...spectralFreezePreStatePatch,
  reverbLevel: 0.25,
};

const spectralFreezePostAudibleStatePatch = {
  ...spectralFreezePreAudibleStatePatch,
  spectralFreezeRouting: 'post',
};

const drumSourceSendStatePatch = {
  ...statePatch,
  padEnabled: false,
  drumEnabled: true,
  drumEuclidMasterEnabled: false,
  drumLevel: 0.75,
  drumReverbSend: 0,
  drumDelayASend: 0,
  drumDelayBSend: 0,
  granularDrumSend: 0,
  drumDelayEnabled: false,
};

const lead1SourceSendStatePatch = {
  ...statePatch,
  padEnabled: false,
  leadEnabled: true,
  lead2Enabled: false,
  lead1Level: 0.5,
};

const lead2SourceSendStatePatch = {
  ...statePatch,
  padEnabled: false,
  leadEnabled: false,
  lead2Enabled: true,
  lead2Level: 0.5,
};

const pianoSourceSendStatePatch = {
  ...statePatch,
  padEnabled: false,
  pianoEnabled: true,
  pianoLevel: 0.5,
};

const diffusePad2DistanceStatePatch = {
  ...statePatch,
  padEnabled: false,
  pad2Enabled: true,
  pad2Level: 0.5,
  pad2DiffuseSend: 0.7,
  pad2Distance: 0.65,
};

const diffuseLead1DistanceStatePatch = {
  ...lead1SourceSendStatePatch,
  lead1DiffuseSend: 0.7,
  lead1Distance: 0.65,
};

const diffuseLead2DistanceStatePatch = {
  ...lead2SourceSendStatePatch,
  lead2DiffuseSend: 0.7,
  lead2Distance: 0.65,
};

const diffusePianoDistanceStatePatch = {
  ...pianoSourceSendStatePatch,
  pianoDiffuseSend: 0.7,
  pianoDistance: 0.65,
  pianoPostLPF: 14000,
  pianoStereoWidth: 0.85,
};

const soundscapeNatureParityStatePatch = {
  ...statePatch,
  padEnabled: false,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 1,
  natureReverbSend: 0.4,
  natureDelayASend: 0,
  natureDelayBSend: 0,
  granularNatureSend: 0,
  birds2SliceDuration: 6,
  birds2SliceDensity: 1,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeNatureProductionStatePatch = {
  ...statePatch,
  padEnabled: false,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 0.41,
  natureReverbSend: 0,
  natureDelayASend: 0,
  natureDelayBSend: 0,
  granularNatureSend: 0,
  birds2SliceDuration: 20,
  birds2SliceDensity: 0.48,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeOceanParityStatePatch = {
  ...statePatch,
  padEnabled: false,
  oceanSampleEnabled: true,
  oceanSampleLevel: 0.55,
  earthLevel: 1,
  oceanReverbSend: 0,
  oceanDelayASend: 0,
  oceanDelayBSend: 0,
  granularWavesSend: 0,
  oceanSliceDuration: 6,
  oceanSliceDensity: 1,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeOceanProductionStatePatch = {
  ...statePatch,
  padEnabled: false,
  oceanSampleEnabled: true,
  oceanSampleLevel: 0.55,
  earthLevel: 1,
  oceanReverbSend: 0,
  oceanDelayASend: 0,
  oceanDelayBSend: 0,
  granularWavesSend: 0,
  oceanSliceDuration: 22,
  oceanSliceDensity: 0.38,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeOceanNatureProductionStatePatch = {
  ...soundscapeOceanProductionStatePatch,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 0.41,
  natureReverbSend: 0,
  natureDelayASend: 0,
  natureDelayBSend: 0,
  granularNatureSend: 0,
  birds2SliceDuration: 20,
  birds2SliceDensity: 0.48,
};

const soundscapeWaterParityStatePatch = {
  ...statePatch,
  padEnabled: false,
  waterEnabled: true,
  waterLevel: 0.8,
  earthLevel: 1,
  waterPreset: 7,
  waterMorphA: 7,
  waterMorphB: 7,
  waterMorph: 0,
  waterLayerHardDrops: 0,
  waterLayerWaterDrops: 0,
  waterLayerTurbulence: 0,
  waterLayerBubbling: 0,
  waterLayerSurf: 0,
  waterLayerChannels: 1,
  waterDensityHardSend: 0,
  waterDensityWaterSend: 0,
  waterDensityBubbleSend: 0,
  waterDensityFeedback: 0,
  waterDensityRing: 0,
  waterDensityWet: 0,
  waterReverbSend: 0,
  waterDelayASend: 0,
  waterDelayBSend: 0,
  granularWaterSend: 0,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeWaterInsectsParityStatePatch = {
  ...soundscapeWaterParityStatePatch,
  insectsEnabled: true,
  insects2Enabled: false,
  insectsLevel: 0.55,
  insectsSharedLevel: 1,
  insectsReverbSend: 0,
  insDelayASend: 0,
  insDelayBSend: 0,
  granularInsectsSend: 0,
};

const soundscapeInsectsParityStatePatch = {
  ...statePatch,
  padEnabled: false,
  insectsEnabled: true,
  insects2Enabled: false,
  insectsLevel: 0.7,
  insectsSharedLevel: 1,
  earthLevel: 1,
  insectsReverbSend: 0,
  insDelayASend: 0,
  insDelayBSend: 0,
  granularInsectsSend: 0,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeInsects2ParityStatePatch = {
  ...soundscapeInsectsParityStatePatch,
  insectsEnabled: false,
  insects2Enabled: true,
  insects2Level: 0.5,
};

const reverbLiveWashBloomStatePatch = {
  ...statePatch,
  reverbEnabled: true,
  reverbLevel: 0.35,
  pad1ReverbSend: 0.4,
  synthReverbSend: 0.4,
  reverbType: 'hall',
  reverbQuality: 'balanced',
  reverbDecay: 0.25,
  reverbDiffusion: 0.55,
  reverbShimmer: 0.02,
  predelay: 0,
  reverbChordWash: true,
  reverbResolutionBloom: true,
  phraseLength: 0.25,
  harmonyClockSource: 'localPhrase',
  transportPrimaryClock: 'seconds',
  transportBarsPerPhrase: 1,
  transportBeatsPerBar: 4,
  tension: 0.45,
  seed: 42,
  seedWindow: 'day',
};

const fastSmokeCaseMetadata = new Map([
  ['manual-pad-granular-reverb-send-two-voice-clean', { domains: ['granular'], coverage: 'active-partial' }],
  ['manual-pad-reverb-return-live-wash-bloom-decay', {
    domains: ['reverbMacro'],
    coverage: 'proven-domain-sentinel',
    retryInFast: true,
    retryReason: 'isolated browser launch can overstate the first Product reverb return capture',
  }],
]);

const rawCases = [
  {
    id: 'manual-pad-reverb-input',
    track: 'reverbInput',
    rmsTolerance: 0.15,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      pad1ReverbSend: 0.4,
      synthReverbSend: 0.4,
    },
  },
  {
    id: 'manual-pad-reverb-preconditioner-output',
    track: 'reverbPreconditionerOut',
    rmsTolerance: 0.08,
    peakTolerance: 0.12,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.3,
      pad1ReverbSend: 0.4,
      synthReverbSend: 0.4,
    },
  },
  {
    id: 'manual-pad-reverb-return',
    track: 'reverbReturn',
    durationMs: 1600,
    settleMs: 250,
    noteDurationMs: 1200,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    statePatch: {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.5,
      pad1ReverbSend: 0.45,
      synthReverbSend: 0.45,
    },
  },
  {
    id: 'manual-pad-reverb-return-tension-scale-shimmer',
    track: 'reverbReturn',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.95,
    envelopeGate: true,
    envelopeTimeToleranceMs: 60,
    statePatch: {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.35,
      pad1ReverbSend: 0.4,
      synthReverbSend: 0.4,
      tension: 0.9,
      reverbTensionMode: 'locked',
      reverbTensionValue: 0.9,
      reverbDecay: 0.2,
      reverbDiffusion: 0.2,
      reverbShimmer: 0.1,
      reverbShimmerPitch: 13,
      reverbScaleShimmer: true,
      scaleMode: 'manual',
      manualScale: 'Major (Ionian)',
      reverbType: 'hall',
      reverbQuality: 'balanced',
      predelay: 0,
    },
  },
  {
    id: 'manual-pad-reverb-return-wash-bloom-boost',
    track: 'reverbReturn',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    envelopeTimeToleranceMs: 60,
    statePatch: {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.35,
      pad1ReverbSend: 0.4,
      synthReverbSend: 0.4,
      reverbType: 'hall',
      reverbQuality: 'balanced',
      reverbDecay: 0.25,
      reverbDiffusion: 0.55,
      reverbShimmer: 0.02,
      sonicParityReverbWashBoost: 1,
      sonicParityReverbBloomBoost: 1,
      predelay: 0,
    },
  },
  {
    id: 'manual-pad-reverb-return-live-wash-bloom-decay',
    track: 'reverbReturn',
    durationMs: 1600,
    settleMs: 0,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.75,
    envelopeGate: true,
    envelopeTimeToleranceMs: 120,
    statePatch: reverbLiveWashBloomStatePatch,
    stateEvents: [{ delayMs: 300, patch: { tension: 0.1 } }],
  },
  {
    id: 'manual-pad-reverb-return-mobile-quality',
    track: 'reverbReturn',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    envelopeTimeToleranceMs: 80,
    mobileDevice: true,
    statePatch: {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.35,
      pad1ReverbSend: 0.4,
      synthReverbSend: 0.4,
      reverbType: 'hall',
      reverbQuality: 'ultra',
      reverbDecay: 0.35,
      reverbDiffusion: 0.65,
      reverbShimmer: 0.05,
      predelay: 0,
    },
  },
  {
    id: 'manual-pad1-dry',
    track: 'pad1Dry',
    durationMs: 700,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch,
  },
  {
    id: 'manual-pad1-reverb-send',
    track: 'pad1ReverbSend',
    durationMs: 700,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      pad1ReverbSend: 0.45,
      synthReverbSend: 0.45,
    },
  },
  {
    id: 'manual-pad1-delay-a-send',
    track: 'pad1DelayASend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...delayAStatePatch,
      delayAMix: 0,
      pad1DelayASend: 0.7,
    },
  },
  {
    id: 'manual-pad1-delay-b-send',
    track: 'pad1DelayBSend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...delayBStatePatch,
      granularDelayMix: 0,
      pad1DelayBSend: 0.7,
    },
  },
  {
    id: 'manual-pad1-granular-send',
    track: 'pad1GranularSend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularPad1Send: 0.7,
    },
  },
  {
    id: 'manual-pad1-diffuse-send',
    track: 'pad1DiffuseSend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: diffusePadStatePatch,
  },
  {
    id: 'manual-pad1-diffuse-send-distance',
    track: 'pad1DiffuseSend',
    durationMs: 900,
    settleMs: 250,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: diffusePadDistanceStatePatch,
  },
  {
    id: 'manual-pad-diffuse-input',
    track: 'diffuseInput',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: diffusePadStatePatch,
  },
  {
    id: 'manual-pad-diffuse-output',
    track: 'diffuseOutput',
    durationMs: 1100,
    rmsTolerance: 0.02,
    peakTolerance: 0.01,
    minLagCorrelation: 0.995,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.03,
    envelopePeakRatioTolerance: 0.03,
    statePatch: diffusePadStatePatch,
  },
  {
    id: 'manual-pad-diffuse-output-distance',
    track: 'diffuseOutput',
    durationMs: 1100,
    settleMs: 250,
    rmsTolerance: 0.4,
    peakTolerance: 0.22,
    minLagCorrelation: 0.92,
    envelopeGate: true,
    envelopePeakRatioTolerance: 0.38,
    statePatch: diffusePadDistanceStatePatch,
  },
  {
    id: 'manual-pad-diffuse-reverb-send',
    track: 'diffuseReverbSend',
    durationMs: 1100,
    rmsTolerance: 0.02,
    peakTolerance: 0.01,
    minLagCorrelation: 0.995,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.03,
    envelopePeakRatioTolerance: 0.03,
    statePatch: diffusePadStatePatch,
  },
  {
    id: 'manual-pad-diffuse-reverb-send-distance',
    track: 'diffuseReverbSend',
    durationMs: 1100,
    settleMs: 250,
    rmsTolerance: 0.4,
    peakTolerance: 0.22,
    minLagCorrelation: 0.92,
    envelopeGate: true,
    envelopePeakRatioTolerance: 0.38,
    statePatch: diffusePadDistanceStatePatch,
  },
  {
    id: 'manual-diffuse-output-modulated-source',
    track: 'diffuseOutput',
    durationMs: 1900,
    settleMs: 250,
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.84,
    maxLagMs: 180,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
    statePatch: diffuseModulatedSourceStatePatch,
    manualNotes: [
      'pad1:60:0.75:1300',
      'pad2:64:0.68:1200',
      'lead1:67:0.62:1000',
    ],
  },
  {
    id: 'manual-diffuse-reverb-send-modulated-source',
    track: 'diffuseReverbSend',
    durationMs: 1900,
    settleMs: 250,
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.84,
    maxLagMs: 180,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
    statePatch: {
      ...diffuseModulatedSourceStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
    },
    manualNotes: [
      'pad1:60:0.75:1300',
      'pad2:64:0.68:1200',
      'lead1:67:0.62:1000',
    ],
  },
  {
    id: 'manual-diffuse-output-all-source-distance',
    track: 'diffuseOutput',
    durationMs: 1900,
    settleMs: 250,
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.84,
    maxLagMs: 180,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
    statePatch: diffuseAllSourceDistanceStatePatch,
    manualNotes: [
      'pad1:60:0.72:1350',
      'pad2:64:0.66:1250',
      'lead1:67:0.58:1100',
      'lead2:71:0.54:950',
      'piano:64:0.62:1200',
    ],
  },
  {
    id: 'manual-diffuse-reverb-send-all-source-distance',
    track: 'diffuseReverbSend',
    durationMs: 1900,
    settleMs: 250,
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.84,
    maxLagMs: 180,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
    statePatch: {
      ...diffuseAllSourceDistanceStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
    },
    manualNotes: [
      'pad1:60:0.72:1350',
      'pad2:64:0.66:1250',
      'lead1:67:0.58:1100',
      'lead2:71:0.54:950',
      'piano:64:0.62:1200',
    ],
  },
  {
    id: 'manual-pad2-dry',
    track: 'pad2Dry',
    durationMs: 700,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
    },
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-pad2-reverb-send',
    track: 'pad2ReverbSend',
    durationMs: 700,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
      reverbEnabled: true,
      reverbLevel: 0,
      pad2ReverbSend: 0.45,
    },
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-pad2-delay-a-send',
    track: 'pad2DelayASend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...delayAStatePatch,
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
      delayAMix: 0,
      pad1DelayASend: 0,
      pad2DelayASend: 0.7,
    },
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-pad2-delay-b-send',
    track: 'pad2DelayBSend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...delayBStatePatch,
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
      granularDelayMix: 0,
      pad1DelayBSend: 0,
      pad2DelayBSend: 0.7,
    },
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-pad2-granular-send',
    track: 'pad2GranularSend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
      granularEnabled: true,
      granularLevel: 0,
      granularPad2Send: 0.7,
    },
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-pad2-diffuse-send',
    track: 'pad2DiffuseSend',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
      pad2DiffuseSend: 0.7,
    },
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-pad2-diffuse-send-distance',
    track: 'pad2DiffuseSend',
    durationMs: 900,
    settleMs: 250,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: diffusePad2DistanceStatePatch,
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-lead1-dry',
    track: 'lead1Dry',
    durationMs: 700,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: lead1SourceSendStatePatch,
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-lead1-reverb-send',
    track: 'lead1ReverbSend',
    durationMs: 700,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...lead1SourceSendStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      lead1ReverbSend: 0.45,
    },
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-lead1-delay-a-send',
    track: 'lead1DelayASend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...delayAStatePatch,
      padEnabled: false,
      leadEnabled: true,
      lead2Enabled: false,
      lead1Level: 0.5,
      delayAMix: 0,
      pad1DelayASend: 0,
      lead1DelayASend: 0.7,
    },
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-lead1-delay-b-send',
    track: 'lead1DelayBSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...delayBStatePatch,
      padEnabled: false,
      leadEnabled: true,
      lead2Enabled: false,
      lead1Level: 0.5,
      granularDelayMix: 0,
      pad1DelayBSend: 0,
      lead1DelayBSend: 0.7,
    },
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-lead1-granular-send',
    track: 'lead1GranularSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...lead1SourceSendStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularLead1Send: 0.7,
    },
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-lead1-diffuse-send',
    track: 'lead1DiffuseSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...lead1SourceSendStatePatch,
      lead1DiffuseSend: 0.7,
    },
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-lead1-diffuse-send-distance',
    track: 'lead1DiffuseSend',
    durationMs: 900,
    settleMs: 250,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: diffuseLead1DistanceStatePatch,
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-lead2-dry',
    track: 'lead2Dry',
    durationMs: 700,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: lead2SourceSendStatePatch,
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-lead2-reverb-send',
    track: 'lead2ReverbSend',
    durationMs: 700,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...lead2SourceSendStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      lead2ReverbSend: 0.45,
    },
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-lead2-delay-a-send',
    track: 'lead2DelayASend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...delayAStatePatch,
      padEnabled: false,
      leadEnabled: false,
      lead2Enabled: true,
      lead2Level: 0.5,
      delayAMix: 0,
      pad1DelayASend: 0,
      lead2DelayASend: 0.7,
    },
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-lead2-delay-b-send',
    track: 'lead2DelayBSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...delayBStatePatch,
      padEnabled: false,
      leadEnabled: false,
      lead2Enabled: true,
      lead2Level: 0.5,
      granularDelayMix: 0,
      pad1DelayBSend: 0,
      lead2DelayBSend: 0.7,
    },
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-lead2-granular-send',
    track: 'lead2GranularSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...lead2SourceSendStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularLead2Send: 0.7,
    },
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-lead2-diffuse-send',
    track: 'lead2DiffuseSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: {
      ...lead2SourceSendStatePatch,
      lead2DiffuseSend: 0.7,
    },
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-lead2-diffuse-send-distance',
    track: 'lead2DiffuseSend',
    durationMs: 900,
    settleMs: 250,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: diffuseLead2DistanceStatePatch,
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-piano-dry',
    track: 'pianoDry',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: pianoSourceSendStatePatch,
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'manual-piano-short-dry',
    track: 'pianoDry',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: pianoSourceSendStatePatch,
    manualNotes: ['piano:64:0.75:700'],
  },
  {
    id: 'manual-piano-reverb-send',
    track: 'pianoReverbSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    envelopeTimeToleranceMs: 80,
    statePatch: {
      ...pianoSourceSendStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      pianoReverbSend: 0.45,
    },
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'manual-piano-short-reverb-send',
    track: 'pianoReverbSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    envelopeTimeToleranceMs: 80,
    statePatch: {
      ...pianoSourceSendStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      pianoReverbSend: 0.45,
    },
    manualNotes: ['piano:64:0.75:700'],
  },
  {
    id: 'manual-piano-delay-a-send',
    track: 'pianoDelayASend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayAStatePatch,
      padEnabled: false,
      pianoEnabled: true,
      pianoLevel: 0.5,
      delayAMix: 0,
      pad1DelayASend: 0,
      pianoDelayASend: 0.7,
    },
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'manual-piano-delay-b-send',
    track: 'pianoDelayBSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayBStatePatch,
      padEnabled: false,
      pianoEnabled: true,
      pianoLevel: 0.5,
      granularDelayMix: 0,
      pad1DelayBSend: 0,
      pianoDelayBSend: 0.7,
    },
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'manual-piano-granular-send',
    track: 'pianoGranularSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...pianoSourceSendStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularPianoSend: 0.7,
    },
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'manual-piano-diffuse-send',
    track: 'pianoDiffuseSend',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...pianoSourceSendStatePatch,
      pianoDiffuseSend: 0.7,
    },
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'manual-piano-diffuse-send-distance',
    track: 'pianoDiffuseSend',
    durationMs: 900,
    settleMs: 250,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: diffusePianoDistanceStatePatch,
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'soundscape-nature-dry-deterministic',
    track: 'natureDry',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: soundscapeNatureParityStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-dry-production-texture',
    track: 'natureDry',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    attempts: 8,
    statePatch: soundscapeNatureProductionStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-reverb-send-production-texture',
    track: 'natureReverbSend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    attempts: 8,
    statePatch: {
      ...soundscapeNatureProductionStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      natureReverbSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-reverb-send-deterministic',
    track: 'natureReverbSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.13,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: {
      ...soundscapeNatureParityStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-delay-a-send-deterministic',
    track: 'natureDelayASend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeNatureParityStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      natureReverbSend: 0,
      natureDelayASend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-delay-a-send-production-texture',
    track: 'natureDelayASend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    attempts: 8,
    statePatch: {
      ...soundscapeNatureProductionStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      natureDelayASend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-delay-b-send-deterministic',
    track: 'natureDelayBSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeNatureParityStatePatch,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      natureReverbSend: 0,
      natureDelayBSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-delay-b-send-production-texture',
    track: 'natureDelayBSend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    attempts: 8,
    statePatch: {
      ...soundscapeNatureProductionStatePatch,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      natureDelayBSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-granular-send-deterministic',
    track: 'natureGranularSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeNatureParityStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      natureReverbSend: 0,
      granularNatureSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-granular-send-production-texture',
    track: 'natureGranularSend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    attempts: 8,
    statePatch: {
      ...soundscapeNatureProductionStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      granularNatureSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-dry-deterministic',
    track: 'oceanDry',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: soundscapeOceanParityStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-dry-production-texture',
    track: 'oceanDry',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: soundscapeOceanProductionStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-reverb-send-production-texture',
    track: 'oceanReverbSend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: {
      ...soundscapeOceanProductionStatePatch,
      oceanSampleLevel: 0,
      earthLevel: 0.41,
      reverbEnabled: true,
      reverbLevel: 0,
      oceanReverbSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-reverb-send-deterministic',
    track: 'oceanReverbSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeOceanParityStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      oceanReverbSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-delay-a-send-deterministic',
    track: 'oceanDelayASend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeOceanParityStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      oceanDelayASend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-delay-a-send-production-texture',
    track: 'oceanDelayASend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: {
      ...soundscapeOceanProductionStatePatch,
      oceanSampleLevel: 0,
      earthLevel: 0.41,
      delayAEnabled: true,
      delayAMix: 0,
      oceanDelayASend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-delay-b-send-deterministic',
    track: 'oceanDelayBSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeOceanParityStatePatch,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      oceanDelayBSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-delay-b-send-production-texture',
    track: 'oceanDelayBSend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: {
      ...soundscapeOceanProductionStatePatch,
      oceanSampleLevel: 0,
      earthLevel: 0.41,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      oceanDelayBSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-granular-send-deterministic',
    track: 'oceanGranularSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeOceanParityStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      granularWavesSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-granular-send-production-texture',
    track: 'oceanGranularSend',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.18,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: {
      ...soundscapeOceanProductionStatePatch,
      oceanSampleLevel: 0,
      earthLevel: 0.41,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      granularWavesSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-production-stem',
    track: 'soundscapeStem',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.28,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    attempts: 4,
    statePatch: soundscapeOceanProductionStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-nature-production-stem',
    track: 'soundscapeStem',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.28,
    peakTolerance: 0.3,
    maxLagMs: 80,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    attempts: 8,
    statePatch: soundscapeNatureProductionStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-ocean-nature-production-stem',
    track: 'soundscapeStem',
    durationMs: 2600,
    settleMs: 700,
    rmsTolerance: 0.34,
    peakTolerance: 0.36,
    maxLagMs: 160,
    minLagCorrelation: 0.5,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.7,
    attempts: 4,
    statePatch: soundscapeOceanNatureProductionStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-water-dry-deterministic',
    track: 'waterDry',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: soundscapeWaterParityStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-water-reverb-send-deterministic',
    track: 'waterReverbSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeWaterParityStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      waterReverbSend: 1,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-water-delay-a-send-deterministic',
    track: 'waterDelayASend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeWaterParityStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      waterDelayASend: 1,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-water-delay-b-send-deterministic',
    track: 'waterDelayBSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeWaterParityStatePatch,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      waterDelayBSend: 1,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-water-granular-send-deterministic',
    track: 'waterGranularSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeWaterParityStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      granularWaterSend: 1,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-insects-dry-deterministic',
    track: 'insectsDry',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: soundscapeInsectsParityStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-insects-reverb-send-deterministic',
    track: 'insectsReverbSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeInsectsParityStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      insectsReverbSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-insects-delay-a-send-deterministic',
    track: 'insectsDelayASend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeInsectsParityStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      insDelayASend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-insects-delay-b-send-deterministic',
    track: 'insectsDelayBSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeInsectsParityStatePatch,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      insDelayBSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-insects-granular-send-deterministic',
    track: 'insectsGranularSend',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...soundscapeInsectsParityStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      granularInsectsSend: 0.4,
    },
    manualNotes: false,
  },
  {
    id: 'soundscape-insects2-dry-deterministic',
    track: 'insectsDry',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.2,
    peakTolerance: 0.08,
    maxLagMs: 160,
    minLagCorrelation: 0.98,
    alignmentGate: true,
    statePatch: soundscapeInsects2ParityStatePatch,
    manualNotes: false,
  },
  {
    id: 'soundscape-water-insects-stem-deterministic',
    track: 'soundscapeStem',
    durationMs: 1000,
    settleMs: 1300,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    maxLagMs: 180,
    minLagCorrelation: 0.95,
    alignmentGate: true,
    attempts: 6,
    statePatch: soundscapeWaterInsectsParityStatePatch,
    manualNotes: false,
  },
  {
    id: 'manual-pad-spectral-freeze-input-pre',
    track: 'spectralFreezeInput',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.12,
    minLagCorrelation: 0.99,
    statePatch: spectralFreezePreStatePatch,
  },
  {
    id: 'manual-pad-spectral-freeze-output-pre-live',
    track: 'spectralFreezeOutput',
    durationMs: 1400,
    settleMs: 250,
    noteDurationMs: 1100,
    rmsTolerance: 0.2,
    peakTolerance: 0.16,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    statePatch: spectralFreezePreStatePatch,
  },
  {
    id: 'manual-pad-spectral-freeze-pad1-dry-pre-active-event',
    track: 'pad1Dry',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.08,
    peakTolerance: 0.08,
    minLagCorrelation: 0.99,
    envelopeGate: true,
    statePatch: spectralFreezePreAudibleStatePatch,
    stateEvents: [{ delayMs: 300, patch: { spectralFreezeActive: true } }],
  },
  {
    id: 'manual-pad-spectral-freeze-output-pre-active-event',
    track: 'spectralFreezeOutput',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.4,
    envelopePeakRatioTolerance: 0.35,
    statePatch: spectralFreezePreAudibleStatePatch,
    stateEvents: [{ delayMs: 300, patch: { spectralFreezeActive: true } }],
  },
  {
    id: 'manual-pad-spectral-freeze-master-post-active-event',
    track: 'masterPostLimiter',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.4,
    envelopePeakRatioTolerance: 0.35,
    statePatch: spectralFreezePreAudibleStatePatch,
    stateEvents: [{ delayMs: 300, patch: { spectralFreezeActive: true } }],
  },
  {
    id: 'manual-pad-spectral-freeze-master-pre-active-event',
    track: 'masterPreLimiter',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.4,
    envelopePeakRatioTolerance: 0.35,
    statePatch: spectralFreezePreAudibleStatePatch,
    stateEvents: [{ delayMs: 300, patch: { spectralFreezeActive: true } }],
  },
  {
    id: 'manual-pad-spectral-freeze-reverb-return-pre-active-event',
    track: 'reverbReturn',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.4,
    envelopePeakRatioTolerance: 0.35,
    statePatch: spectralFreezePreAudibleStatePatch,
    stateEvents: [{ delayMs: 300, patch: { spectralFreezeActive: true } }],
  },
  {
    id: 'manual-pad-spectral-freeze-input-post',
    track: 'spectralFreezeInput',
    durationMs: 1600,
    settleMs: 250,
    noteDurationMs: 1200,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    statePatch: spectralFreezePostStatePatch,
  },
  {
    id: 'manual-pad-spectral-freeze-reverb-return-post-live',
    track: 'reverbReturn',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    statePatch: spectralFreezePostAudibleStatePatch,
  },
  {
    id: 'manual-pad-spectral-freeze-output-post-live',
    track: 'spectralFreezeOutput',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    statePatch: spectralFreezePostStatePatch,
  },
  {
    id: 'manual-pad-granular-input',
    track: 'granularInput',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.99,
    statePatch: {
      ...statePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularPad1Send: 0.4,
    },
  },
  {
    id: 'manual-pad-granular-output-clean-direct',
    track: 'granularOutput',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.3,
    peakTolerance: 0.12,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    statePatch: granularCleanOutputStatePatch,
  },
  {
    id: 'manual-pad-granular-output-two-voice-clean',
    track: 'granularOutput',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.35,
    peakTolerance: 0.16,
    minLagCorrelation: 0.86,
    envelopeGate: true,
    statePatch: granularTwoVoiceCleanOutputStatePatch,
  },
  {
    id: 'manual-pad-granular-output-modulated-clean',
    track: 'granularOutput',
    durationMs: 1900,
    settleMs: 250,
    noteDurationMs: 1450,
    rmsTolerance: 0.35,
    peakTolerance: 0.16,
    minLagCorrelation: 0.86,
    envelopeGate: true,
    envelopeTimeToleranceMs: 80,
    statePatch: granularModulatedCleanOutputStatePatch,
  },
  {
    id: 'manual-pad-granular-output-feedback-clean',
    track: 'granularOutput',
    durationMs: 2200,
    settleMs: 250,
    noteDurationMs: 1450,
    rmsTolerance: 0.38,
    peakTolerance: 0.18,
    minLagCorrelation: 0.84,
    envelopeGate: true,
    statePatch: granularFeedbackOutputStatePatch,
  },
  {
    id: 'manual-pad-granular-output-delayed-freeze-clean',
    track: 'granularOutput',
    durationMs: 2300,
    settleMs: 250,
    noteDurationMs: 1700,
    rmsTolerance: 0.36,
    peakTolerance: 0.18,
    minLagCorrelation: 0.84,
    envelopeGate: true,
    envelopeTimeToleranceMs: 100,
    statePatch: granularDelayedFreezeOutputStatePatch,
    stateEvents: [{ delayMs: 520, patch: { granularFreeze: true } }],
  },
  {
    id: 'manual-pad-granular-output-legacy-cloud',
    track: 'granularOutput',
    durationMs: 1500,
    settleMs: 250,
    noteDurationMs: 1100,
    rmsTolerance: 0.3,
    peakTolerance: 0.16,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    statePatch: granularLegacyCloudOutputStatePatch,
  },
  {
    id: 'manual-pad-granular-reverb-send-clean',
    track: 'granularReverbSend',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.35,
    peakTolerance: 0.16,
    minLagCorrelation: 0.88,
    envelopeGate: true,
    statePatch: {
      ...granularCleanOutputStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      granularLevel: 0,
      granularReverbSend: 0.5,
    },
  },
  {
    id: 'manual-pad-granular-reverb-send-two-voice-clean',
    track: 'granularReverbSend',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    attempts: 4,
    rmsTolerance: 0.4,
    peakTolerance: 0.18,
    minLagCorrelation: 0.84,
    envelopeGate: true,
    statePatch: {
      ...granularTwoVoiceCleanOutputStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      granularLevel: 0,
      granularReverbSend: 0.5,
    },
  },
  {
    id: 'manual-pad-granular-to-delay-a-send-clean',
    track: 'granularToDelayASend',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.3,
    peakTolerance: 0.12,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    statePatch: {
      ...granularCleanOutputStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      delayAFeedback: 0,
      granularLevel: 0,
      granularReverbSend: 0,
      granularDelayASend: 1,
    },
  },
  {
    id: 'manual-pad-granular-to-delay-b-send-clean',
    track: 'granularToDelayBSend',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.3,
    peakTolerance: 0.12,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    statePatch: {
      ...granularCleanOutputStatePatch,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      granularDelayActivity: 0.1,
      granularDelayRepeats: 0,
      granularDelayTime: '1/32',
      granularLevel: 0,
      granularReverbSend: 0,
      granularDelayBSend: 1,
    },
  },
  {
    id: 'manual-pad-delay-a-output',
    track: 'delayAOut',
    durationMs: 900,
    rmsTolerance: 0.05,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: delayAStatePatch,
  },
  {
    id: 'manual-pad-delay-a-reverb-send',
    track: 'delayAReverbSend',
    durationMs: 900,
    rmsTolerance: 0.05,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayAStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      delayAMix: 0,
      delayAReverbSend: 0.5,
    },
  },
  {
    id: 'manual-pad-delay-a-reverb-send-default',
    track: 'delayAReverbSend',
    durationMs: 900,
    rmsTolerance: 0.05,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayAStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      delayAMix: 0,
    },
  },
  {
    id: 'manual-pad-delay-a-to-delay-b-send',
    track: 'delayAToDelayBSend',
    durationMs: 900,
    rmsTolerance: 0.18,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayAStatePatch,
      delayAMix: 0,
      delayAToBSend: 0.5,
      delayACrossFeedFilter: 1,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      granularDelayActivity: 0.1,
      granularDelayRepeats: 0,
      granularDelayTime: '1/32',
    },
  },
  {
    id: 'manual-pad-delay-a-to-granular-send',
    track: 'delayAToGranularSend',
    durationMs: 900,
    rmsTolerance: 0.05,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayAStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      granularDelayASend: 0,
      granularDelayBSend: 0,
      delayAMix: 0,
      delayAGranularSend: 0.5,
    },
  },
  {
    id: 'manual-pad-delay-b-input',
    track: 'delayBInput',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: delayBStatePatch,
  },
  {
    id: 'manual-pad-delay-b-output',
    track: 'delayBOut',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    statePatch: delayBStatePatch,
  },
  {
    id: 'manual-pad-delay-b-reverb-send',
    track: 'delayBReverbSend',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayBStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      granularDelayMix: 0,
      granularDelayReverbSend: 0.5,
    },
  },
  {
    id: 'manual-pad-delay-b-to-delay-a-send',
    track: 'delayBToDelayASend',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayBStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      delayAFeedback: 0,
      granularDelayMix: 0,
      delayBToASend: 0.5,
    },
  },
  {
    id: 'manual-pad-delay-b-to-granular-send',
    track: 'delayBToGranularSend',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: {
      ...delayBStatePatch,
      granularDelayMix: 0,
      delayBGranularSend: 0.5,
    },
  },
  {
    id: 'manual-pad-delay-bidirectional-a-to-b-safe-send',
    track: 'delayAToDelayBSend',
    durationMs: 1100,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    statePatch: delayBidirectionalStatePatch,
  },
  {
    id: 'manual-pad-delay-bidirectional-b-to-a-safe-send',
    track: 'delayBToDelayASend',
    durationMs: 1100,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.66,
    envelopePeakRatioTolerance: 0.5,
    statePatch: delayBidirectionalStatePatch,
  },
  {
    id: 'manual-pad-master-pre-limiter',
    track: 'masterPreLimiter',
    rmsTolerance: 0.02,
    peakTolerance: 0.02,
    minLagCorrelation: 0.98,
  },
  {
    id: 'manual-pad-master-post-limiter',
    track: 'masterPostLimiter',
    rmsTolerance: 0.35,
    peakTolerance: 0.06,
    minLagCorrelation: 0.9,
  },
  {
    id: 'manual-pad-dynamics-input-active-character',
    track: 'dynamicsInput',
    durationMs: 700,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.98,
    statePatch: activeDynamicsStatePatch,
  },
  {
    id: 'manual-pad-dynamics-output-active-character',
    track: 'dynamicsOutput',
    durationMs: 700,
    rmsTolerance: 0.02,
    peakTolerance: 0.02,
    minLagCorrelation: 0.99,
    statePatch: activeDynamicsStatePatch,
  },
  {
    id: 'manual-pad-dynamics-input-saturation',
    track: 'dynamicsInput',
    durationMs: 700,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.98,
    statePatch: dynamicsSaturationStatePatch,
  },
  {
    id: 'manual-pad-dynamics-output-saturation',
    track: 'dynamicsOutput',
    durationMs: 700,
    attempts: 10,
    rmsTolerance: 0.04,
    peakTolerance: 0.04,
    minLagCorrelation: 0.98,
    statePatch: dynamicsSaturationStatePatch,
  },
  {
    id: 'manual-pad-dynamics-input-end-comp',
    track: 'dynamicsInput',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.98,
    statePatch: dynamicsEndCompStatePatch,
  },
  {
    id: 'manual-pad-dynamics-output-end-comp',
    track: 'dynamicsOutput',
    durationMs: 900,
    rmsTolerance: 0.06,
    peakTolerance: 0.08,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.2,
    envelopePeakRatioTolerance: 0.25,
    statePatch: dynamicsEndCompStatePatch,
  },
  {
    id: 'manual-pad-dynamics-output-sat-end-comp',
    track: 'dynamicsOutput',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.1,
    minLagCorrelation: 0.95,
    envelopeGate: true,
    envelopeRmsRatioTolerance: 0.24,
    envelopePeakRatioTolerance: 0.3,
    statePatch: dynamicsSatEndCompStatePatch,
  },
  {
    id: 'manual-pad-sidechain-pad1-input',
    track: 'sidechainPad1Input',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.04,
    minLagCorrelation: 0.98,
    statePatch: sidechainTargetStatePatch('sidechainPad1Target'),
  },
  {
    id: 'manual-pad-sidechain-pad1-output',
    track: 'sidechainPad1Output',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    minLagCorrelation: 0.94,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainPad1Target'),
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-pad1-gain-trace',
    track: 'sidechainPad1GainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainPad1Target'),
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-pad2-input',
    track: 'sidechainPad2Input',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.04,
    minLagCorrelation: 0.98,
    statePatch: sidechainTargetStatePatch('sidechainPad2Target', {
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
    }),
    manualNotes: ['pad2:64:0.75:700'],
  },
  {
    id: 'manual-pad-sidechain-pad2-output',
    track: 'sidechainPad2Output',
    durationMs: 900,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    minLagCorrelation: 0.94,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainPad2Target', {
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
    }),
    manualNotes: ['pad2:64:0.75:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-pad2-gain-trace',
    track: 'sidechainPad2GainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainPad2Target', {
      padEnabled: false,
      pad2Enabled: true,
      pad2Level: 0.5,
    }),
    manualNotes: ['pad2:64:0.75:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-lead1-input',
    track: 'sidechainLead1Input',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: sidechainTargetStatePatch('sidechainLead1Target', lead1SourceSendStatePatch),
    manualNotes: ['lead1:64:0.75:700'],
  },
  {
    id: 'manual-pad-sidechain-lead1-output',
    track: 'sidechainLead1Output',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.12,
    minLagCorrelation: 0.94,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainLead1Target', lead1SourceSendStatePatch),
    manualNotes: ['lead1:64:0.75:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-lead1-gain-trace',
    track: 'sidechainLead1GainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainLead1Target', lead1SourceSendStatePatch),
    manualNotes: ['lead1:64:0.75:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-lead2-input',
    track: 'sidechainLead2Input',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    statePatch: sidechainTargetStatePatch('sidechainLead2Target', lead2SourceSendStatePatch),
    manualNotes: ['lead2:67:0.75:700'],
  },
  {
    id: 'manual-pad-sidechain-lead2-output',
    track: 'sidechainLead2Output',
    durationMs: 900,
    rmsTolerance: 0.16,
    peakTolerance: 0.12,
    minLagCorrelation: 0.94,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainLead2Target', lead2SourceSendStatePatch),
    manualNotes: ['lead2:67:0.75:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-lead2-gain-trace',
    track: 'sidechainLead2GainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainLead2Target', lead2SourceSendStatePatch),
    manualNotes: ['lead2:67:0.75:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-piano-input',
    track: 'sidechainPianoInput',
    durationMs: 900,
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainPianoTarget', pianoSourceSendStatePatch),
    manualNotes: ['piano:64:0.74:700'],
  },
  {
    id: 'manual-pad-sidechain-piano-output',
    track: 'sidechainPianoOutput',
    durationMs: 900,
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.9,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainPianoTarget', pianoSourceSendStatePatch),
    manualNotes: ['piano:64:0.74:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-piano-gain-trace',
    track: 'sidechainPianoGainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainPianoTarget', pianoSourceSendStatePatch),
    manualNotes: ['piano:64:0.74:700'],
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-granular-input',
    track: 'sidechainGranularInput',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.35,
    peakTolerance: 0.16,
    minLagCorrelation: 0.86,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainGranularTarget', granularCleanOutputStatePatch),
  },
  {
    id: 'manual-pad-sidechain-granular-output',
    track: 'sidechainGranularOutput',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    rmsTolerance: 0.35,
    peakTolerance: 0.18,
    minLagCorrelation: 0.84,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainGranularTarget', granularCleanOutputStatePatch),
    manualDrums: ['kick:1:350'],
  },
  {
    id: 'manual-pad-sidechain-granular-gain-trace',
    track: 'sidechainGranularGainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainGranularTarget', granularCleanOutputStatePatch),
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-delay-a-input',
    track: 'sidechainDelayAInput',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.05,
    minLagCorrelation: 0.98,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainDelayATarget', delayAStatePatch),
  },
  {
    id: 'manual-pad-sidechain-delay-a-output',
    track: 'sidechainDelayAOutput',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.06,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopePeakRatioTolerance: 0.66,
    statePatch: sidechainTargetStatePatch('sidechainDelayATarget', delayAStatePatch),
    manualDrums: ['kick:1:150'],
  },
  {
    id: 'manual-pad-sidechain-delay-a-gain-trace',
    track: 'sidechainDelayAGainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainDelayATarget', delayAStatePatch),
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-delay-b-input',
    track: 'sidechainDelayBInput',
    durationMs: 900,
    rmsTolerance: 0.1,
    peakTolerance: 0.06,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainDelayBTarget', delayBStatePatch),
  },
  {
    id: 'manual-pad-sidechain-delay-b-output',
    track: 'sidechainDelayBOutput',
    durationMs: 900,
    rmsTolerance: 0.1,
    peakTolerance: 0.08,
    minLagCorrelation: 0.94,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainDelayBTarget', delayBStatePatch),
    manualDrums: ['kick:1:150'],
  },
  {
    id: 'manual-pad-sidechain-delay-b-gain-trace',
    track: 'sidechainDelayBGainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainDelayBTarget', delayBStatePatch),
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-pad-sidechain-reverb-input',
    track: 'sidechainReverbInput',
    durationMs: 1600,
    noteDurationMs: 1200,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainReverbTarget', {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.35,
      pad1ReverbSend: 0.6,
    }),
  },
  {
    id: 'manual-pad-sidechain-reverb-output',
    track: 'sidechainReverbOutput',
    durationMs: 1600,
    noteDurationMs: 1200,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
    envelopeGate: true,
    statePatch: sidechainTargetStatePatch('sidechainReverbTarget', {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.35,
      pad1ReverbSend: 0.6,
    }),
    manualDrums: ['kick:1:150'],
  },
  {
    id: 'manual-pad-sidechain-reverb-gain-trace',
    track: 'sidechainReverbGainTrace',
    durationMs: 900,
    rmsTolerance: 0.08,
    peakTolerance: 0.03,
    minLagCorrelation: 0.96,
    envelopeGate: true,
    envelopeWindowMs: 250,
    envelopeRmsRatioTolerance: 0.08,
    envelopePeakRatioTolerance: 0.35,
    statePatch: sidechainTargetStatePatch('sidechainReverbTarget', {
      ...statePatch,
      reverbEnabled: true,
      reverbLevel: 0.35,
      pad1ReverbSend: 0.6,
    }),
    manualDrums: ['kick:1:25'],
  },
  {
    id: 'manual-drum-dry',
    track: 'drumDry',
    durationMs: 900,
    rmsTolerance: 0.02,
    peakTolerance: 0.02,
    minLagCorrelation: 0.995,
    envelopeGate: true,
    statePatch: drumSourceSendStatePatch,
    manualNotes: false,
    manualDrums: ['kick:0.8:0'],
  },
  {
    id: 'manual-drum-reverb-send',
    track: 'drumReverbSend',
    durationMs: 900,
    rmsTolerance: 0.02,
    peakTolerance: 0.02,
    minLagCorrelation: 0.995,
    envelopeGate: true,
    statePatch: {
      ...drumSourceSendStatePatch,
      reverbEnabled: true,
      reverbLevel: 0,
      drumReverbSend: 0.6,
    },
    manualNotes: false,
    manualDrums: ['kick:0.8:0'],
  },
  {
    id: 'manual-drum-delay-a-send',
    track: 'drumDelayASend',
    durationMs: 900,
    rmsTolerance: 0.02,
    peakTolerance: 0.02,
    minLagCorrelation: 0.995,
    envelopeGate: true,
    statePatch: {
      ...drumSourceSendStatePatch,
      delayAEnabled: true,
      delayAMix: 0,
      delayAFeedback: 0,
      drumDelayASend: 0.5,
    },
    manualNotes: false,
    manualDrums: ['kick:0.8:0'],
  },
  {
    id: 'manual-drum-delay-b-send',
    track: 'drumDelayBSend',
    durationMs: 900,
    rmsTolerance: 0.02,
    peakTolerance: 0.02,
    minLagCorrelation: 0.995,
    envelopeGate: true,
    statePatch: {
      ...drumSourceSendStatePatch,
      granularDelayEnabled: true,
      granularDelayMix: 0,
      granularDelayActivity: 0.1,
      granularDelayRepeats: 0,
      granularDelayTime: '1/32',
      drumDelayBSend: 0.5,
    },
    manualNotes: false,
    manualDrums: ['kick:0.8:0'],
  },
  {
    id: 'manual-drum-granular-send',
    track: 'drumGranularSend',
    durationMs: 900,
    rmsTolerance: 0.02,
    peakTolerance: 0.02,
    minLagCorrelation: 0.995,
    envelopeGate: true,
    statePatch: {
      ...drumSourceSendStatePatch,
      granularEnabled: true,
      granularLevel: 0,
      granularReverbSend: 0,
      granularDrumSend: 0.5,
    },
    manualNotes: false,
    manualDrums: ['kick:0.8:0'],
  },
];

const rawCaseIds = new Set(rawCases.map((caseDef) => caseDef.id));
const missingFastMetadataCaseIds = [...fastSmokeCaseMetadata.keys()].filter((caseId) => !rawCaseIds.has(caseId));
if (missingFastMetadataCaseIds.length > 0) {
  throw new Error(`Fast smoke metadata references unknown case(s): ${missingFastMetadataCaseIds.join(', ')}`);
}

const cases = rawCases.map((caseDef) => {
  const metadata = fastSmokeCaseMetadata.get(caseDef.id);
  if (!metadata) return { ...caseDef, metadata: { tier: 'full' } };
  return {
    ...caseDef,
    metadata: {
      tier: 'fast',
      retryInFast: false,
      ...metadata,
    },
  };
});

export { cases as smokeCases, statePatch as defaultSmokeStatePatch };
