const baseState = {
  padEnabled: true,
  synthLevel: 0.5,
  masterVolume: 0.75,
  reverbEnabled: false,
  delayAEnabled: false,
  granularEnabled: false,
  spectralFreezeEnabled: false,
  dynamicsEnabled: false,
  driftEnabled: false,
  sidechainEnabled: false,
  drumEnabled: false,
  waterEnabled: false,
  insectsEnabled: false,
  insects2Enabled: false,
  oceanSampleEnabled: false,
  oceanSampleLevel: 0,
  birdsEnabled: false,
  birdsLevel: 0,
  birds2Enabled: false,
  birds2Level: 0,
  frogsEnabled: false,
  frogsLevel: 0,
  natureLevel: 0,
  earthLevel: 1,
  leadEnabled: false,
  lead2Enabled: false,
  pianoEnabled: false,
  synthChordSequencerEnabled: false,
  synthEuclideanMasterEnabled: false,
};

const granularCleanState = {
  ...baseState,
  granularEnabled: true,
  granularLevel: 0.6,
  granularPad1Send: 0.8,
  granularReverbSend: 0,
  granularFeedback: 0,
  granularFeedbackLPF: 12000,
  granularBufferSeconds: 4,
  granularShape: 'triangle',
  granularV1Enabled: true,
  granularV1Mode: 'clean',
  granularV1Slice: 1,
  granularV1Speed: 1,
  granularV1ScanRate: 1,
  granularV1Reverse: false,
  granularV1Pitch: 0,
  granularV1Attack: 0.003,
  granularV1Decay: 1,
  granularV1Blur: 0,
  granularV1GrainOct: 0,
  granularV1Spray: 0,
  granularV1Density: 64,
  granularV1GrainSize: 300,
  granularV1Pan: 0,
  granularV1Gain: 1,
  granularV1PosLFORate: 0,
  granularV1PosLFODepth: 0,
  granularV1PanLFORate: 0,
  granularV1StereoSpread: 0,
  granularV1ReverseLFORate: 0,
  granularV1WriteFollow: 1,
  granularV1RecordLFORate: 0,
  granularV2Enabled: false,
  granularV3Enabled: false,
  granularV4Enabled: false,
};

const granularTwoVoiceCleanState = {
  ...granularCleanState,
  granularLevel: 0.5,
  granularV2Enabled: true,
  granularV2Mode: 'clean',
  granularV2Slice: 5,
  granularV2Speed: 1,
  granularV2ScanRate: 1,
  granularV2Reverse: false,
  granularV2Pitch: 7,
  granularV2Attack: 0.004,
  granularV2Decay: 0.85,
  granularV2Blur: 0,
  granularV2GrainOct: 0,
  granularV2Spray: 0,
  granularV2Density: 48,
  granularV2GrainSize: 260,
  granularV2Pan: 0,
  granularV2Gain: 0.58,
  granularV2PosLFORate: 0,
  granularV2PosLFODepth: 0,
  granularV2PanLFORate: 0,
  granularV2StereoSpread: 0,
  granularV2ReverseLFORate: 0,
  granularV2WriteFollow: 1,
  granularV2RecordLFORate: 0,
};

const granularModulatedCleanState = {
  ...granularCleanState,
  granularLevel: 0.46,
  granularV1Slice: 3,
  granularV1Speed: 0.85,
  granularV1ScanRate: 1.35,
  granularV1Pitch: 5,
  granularV1Pan: -0.18,
  granularV1Gain: 0.86,
  granularV1PosLFORate: 0.34,
  granularV1PosLFODepth: 0.28,
  granularV1PanLFORate: 0.24,
  granularV1StereoSpread: 0.42,
  granularV1RecordLFORate: 0.16,
  granularMacroActivity: 0,
  granularMacroTexture: 0,
  granularMacroComplexity: 0,
  granularMacroChaos: 0,
  granularDiffusion: 0,
  granularPresetBehavior: 'pure',
  granularTensionMode: 'bypass',
};

const granularFeedbackState = {
  ...granularCleanState,
  granularLevel: 0.42,
  granularFeedback: 0.34,
  granularFeedbackLPF: 5200,
  granularV1Slice: 2,
  granularV1WriteFollow: 0.72,
  granularV1Decay: 1.3,
  granularV1Gain: 0.82,
  granularV1PosLFORate: 0,
  granularV1PosLFODepth: 0,
  granularV1PanLFORate: 0,
  granularV1RecordLFORate: 0,
  granularMacroActivity: 0,
  granularMacroTexture: 0,
  granularMacroComplexity: 0,
  granularMacroChaos: 0,
  granularDiffusion: 0,
  granularPresetBehavior: 'pure',
  granularTensionMode: 'bypass',
};

const granularDelayedFreezeState = {
  ...granularCleanState,
  granularLevel: 0.4,
  granularFeedback: 0,
  granularFreeze: false,
  granularV1Slice: 2,
  granularV1WriteFollow: 0.88,
  granularV1Decay: 1.45,
  granularV1Gain: 0.86,
  granularMacroActivity: 0,
  granularMacroTexture: 0,
  granularMacroComplexity: 0,
  granularMacroChaos: 0,
  granularDiffusion: 0,
  granularPresetBehavior: 'pure',
  granularTensionMode: 'bypass',
};

const granularLegacyCloudState = {
  granularEnabled: true,
  granularPreset: 'legacy_cloud',
  granularPresetBehavior: 'pure',
  granularLevel: 1,
  granularPad1Send: 1,
  pad2Level: 0,
  lead1Level: 0,
  lead2Level: 0,
  pianoLevel: 0,
  drumLevel: 0,
  reverbEnabled: false,
  delayAEnabled: false,
  granularDelayEnabled: false,
  spectralFreezeEnabled: false,
  dynamicsEnabled: false,
  driftEnabled: false,
  sidechainEnabled: false,
  granularV1Mode: 'legacy',
  granularV1Density: 20,
  granularV1GrainSize: 80,
  granularV1Spray: 0.3,
  granularLegacyJitter: 10,
  granularLegacyProbability: 0.8,
  granularLegacyPitchMode: 'harmonic',
  granularLegacyPitchSpread: 2,
  granularLegacyMaxGrains: 64,
  granularLegacyFeedback: 0.1,
  seed: 42,
  seedWindow: 'day',
};

const spectralFreezeLiveState = {
  ...baseState,
  reverbEnabled: true,
  reverbLevel: 0.25,
  pad1ReverbSend: 0.45,
  synthReverbSend: 0.45,
  spectralFreezeEnabled: true,
  spectralFreezeActive: false,
  spectralFreezeSlushy: false,
  spectralFreezeMix: 1,
  spectralFreezeSpeed: 0.3,
  spectralFreezeDecay: 1,
  spectralFreezePhaseJitter: 0,
  spectralFreezeRouting: 'pre',
  spectralFreezeReverbCrossfade: 1,
};

const spectralFreezeLivePostState = {
  ...spectralFreezeLiveState,
  spectralFreezeRouting: 'post',
};

const padDistanceDiffuseState = {
  ...baseState,
  padDiffuseSend: 0.7,
  padDistance: 0.65,
};

const pad2DiffuseState = {
  ...baseState,
  padEnabled: false,
  pad2Enabled: true,
  pad2Level: 0.5,
  pad2DiffuseSend: 0.7,
};

const diffuseModulatedSourceState = {
  ...baseState,
  synthLevel: 0.45,
  masterVolume: 0.78,
  padMorph: 0.72,
  padDiffuseSend: 0.55,
  padDistance: 0.35,
  pad2Enabled: true,
  pad2Level: 0.38,
  pad2Morph: 0.64,
  pad2DiffuseSend: 0.45,
  leadEnabled: true,
  lead1Level: 0.32,
  lead1Morph: 0.58,
  lead1DiffuseSend: 0.35,
  lead1Distance: 0.25,
  diffuseEnabled: true,
  diffuseWet: 0.45,
  diffusePreDelay: 0.01,
  diffuseSpread: 0.75,
  diffuseSize: 0.62,
  diffuseTone: 0.58,
  reverbMix: 0.1,
};

const diffuseAllSourceDistanceState = {
  ...baseState,
  synthLevel: 0.42,
  masterVolume: 0.78,
  padMorph: 0.68,
  padDiffuseSend: 0.58,
  padDistance: 0.55,
  pad2Enabled: true,
  pad2Level: 0.34,
  pad2Morph: 0.58,
  pad2DiffuseSend: 0.5,
  pad2Distance: 0.48,
  leadEnabled: true,
  lead2Enabled: true,
  lead1Level: 0.28,
  lead1Morph: 0.5,
  lead1DiffuseSend: 0.42,
  lead1Distance: 0.42,
  lead2Level: 0.24,
  lead2Morph: 0.52,
  lead2DiffuseSend: 0.38,
  lead2Distance: 0.5,
  pianoEnabled: true,
  pianoLevel: 0.32,
  pianoDiffuseSend: 0.36,
  pianoDistance: 0.5,
  pianoPostLPF: 14000,
  pianoStereoWidth: 0.85,
  diffuseEnabled: true,
  diffuseWet: 0.42,
  diffusePreDelay: 0.012,
  diffuseSpread: 0.68,
  diffuseSize: 0.6,
  diffuseTone: 0.62,
  reverbMix: 0.1,
};

const delaySceneState = {
  ...baseState,
  delayAEnabled: true,
  delayAMix: 0.35,
  delayAFeedback: 0.2,
  delayAFilter: 8000,
  delayAPingPong: false,
  delayAModDepth: 0,
  delayADuck: 0,
  delayAWidth: 0.5,
  drumDelayNoteL: '1/32',
  drumDelayNoteR: '1/32',
  pad1DelayASend: 0.5,
  granularDelayEnabled: true,
  granularDelayMix: 0.2,
  granularDelayActivity: 1,
  granularDelayRepeats: 0.2,
  granularDelayTime: '1/32',
  granularDelayFilter: 1,
  granularDelayVibrato: 0,
  granularSpaceMode: 'cascade',
  delayBPattern: 'cascade',
  delayBWarp: 'clean',
  delayBWarpIntensity: 0,
  delayBSpread: 0.5,
  pad1DelayBSend: 0.4,
  delayAToBSend: 0.3,
  delayBToASend: 0.2,
  delayACrossFeedFilter: 1,
};

const delayALongFeedbackState = {
  ...baseState,
  delayAEnabled: true,
  delayAMix: 0.42,
  delayAFeedback: 0.48,
  delayAFilter: 7200,
  delayAPingPong: true,
  delayAModDepth: 0,
  delayADuck: 0,
  delayAWidth: 0.62,
  drumDelayNoteL: '1/16',
  drumDelayNoteR: '1/8',
  pad1DelayASend: 0.58,
};

const delayBLongFeedbackState = {
  ...baseState,
  granularDelayEnabled: true,
  granularDelayMix: 0.42,
  granularDelayActivity: 1,
  granularDelayRepeats: 0.46,
  granularDelayTime: '1/16',
  granularDelayFilter: 0.82,
  granularDelayVibrato: 0,
  granularSpaceMode: 'cascade',
  delayBPattern: 'cascade',
  delayBWarp: 'clean',
  delayBWarpIntensity: 0,
  delayBSpread: 0.58,
  pad1DelayBSend: 0.64,
};

const delayAToBOrderState = {
  ...baseState,
  delayAEnabled: true,
  delayAMix: 0.36,
  delayAFeedback: 0.34,
  delayAFilter: 6800,
  delayAPingPong: false,
  delayAModDepth: 0,
  delayADuck: 0,
  delayAWidth: 0.5,
  drumDelayNoteL: '1/32',
  drumDelayNoteR: '1/16',
  pad1DelayASend: 0.58,
  granularDelayEnabled: true,
  granularDelayMix: 0.28,
  granularDelayActivity: 1,
  granularDelayRepeats: 0.32,
  granularDelayTime: '1/16',
  granularDelayFilter: 0.88,
  granularDelayVibrato: 0,
  granularSpaceMode: 'cascade',
  delayBPattern: 'cascade',
  delayBWarp: 'clean',
  delayBWarpIntensity: 0,
  delayBSpread: 0.5,
  pad1DelayBSend: 0,
  delayAToBSend: 0.46,
  delayBToASend: 0,
  delayACrossFeedFilter: 0.9,
};

const delayBToAOrderState = {
  ...baseState,
  delayAEnabled: true,
  delayAMix: 0.26,
  delayAFeedback: 0.28,
  delayAFilter: 6200,
  delayAPingPong: false,
  delayAModDepth: 0,
  delayADuck: 0,
  delayAWidth: 0.5,
  drumDelayNoteL: '1/16',
  drumDelayNoteR: '1/16',
  pad1DelayASend: 0,
  granularDelayEnabled: true,
  granularDelayMix: 0.36,
  granularDelayActivity: 1,
  granularDelayRepeats: 0.36,
  granularDelayTime: '1/32',
  granularDelayFilter: 0.9,
  granularDelayVibrato: 0,
  granularSpaceMode: 'cascade',
  delayBPattern: 'cascade',
  delayBWarp: 'clean',
  delayBWarpIntensity: 0,
  delayBSpread: 0.5,
  pad1DelayBSend: 0.58,
  delayAToBSend: 0,
  delayBToASend: 0.42,
  delayACrossFeedFilter: 0.9,
};

const dynamicsDriftState = {
  ...baseState,
  dynamicsEnabled: true,
  driftEnabled: true,
  driftMix: 0.45,
  driftMode: 'shallowWater',
  driftAge: 0.25,
  driftDepth: 0.35,
  driftRate: 0.2,
  driftStereo: 0.2,
  endCompEnabled: false,
  erosionEnabled: false,
  dynamicsSaturationEnabled: false,
};

const dynamicsSaturationState = {
  ...baseState,
  dynamicsEnabled: true,
  driftEnabled: false,
  erosionEnabled: false,
  dynamicsSaturationEnabled: true,
  dynamicsSaturationMode: 'tube',
  dynamicsSaturationDrive: 0.38,
  dynamicsSaturationTone: 0.62,
  dynamicsSaturationBias: 0.54,
  endCompEnabled: false,
};

const dynamicsEndCompState = {
  ...baseState,
  dynamicsEnabled: true,
  driftEnabled: false,
  erosionEnabled: false,
  dynamicsSaturationEnabled: false,
  endCompEnabled: true,
  endCompThreshold: -28,
  endCompKnee: 10,
  endCompRatio: 3,
  endCompAttackMs: 8,
  endCompReleaseMs: 180,
  endCompMakeup: 1.08,
  endCompMix: 0.72,
  endCompDetectorHp: 0.18,
  endCompDetectorTilt: 0.58,
  endCompAutoMakeup: 0.35,
  endCompProgramRelease: 0.4,
};

const dynamicsSatEndCompState = {
  ...dynamicsEndCompState,
  dynamicsSaturationEnabled: true,
  dynamicsSaturationMode: 'tape',
  dynamicsSaturationDrive: 0.32,
  dynamicsSaturationTone: 0.58,
  dynamicsSaturationBias: 0.5,
  endCompThreshold: -24,
  endCompRatio: 2.4,
  endCompMix: 0.62,
};

const drumKickState = {
  ...baseState,
  padEnabled: false,
  drumEnabled: true,
  drumEuclidMasterEnabled: false,
  drumLevel: 0.75,
  drumReverbSend: 0,
  drumDelayASend: 0,
  drumDelayBSend: 0,
  granularDrumSend: 0,
};

const sourceSendFxBaseState = {
  ...granularCleanState,
  reverbEnabled: true,
  reverbLevel: 0.24,
  reverbPreDelay: 0,
  reverbDecay: 0.32,
  reverbTone: 0.5,
  reverbMod: 0,
  delayAEnabled: true,
  delayAMix: 0.18,
  delayAFeedback: 0,
  delayAFilter: 8000,
  delayAPingPong: false,
  delayAModDepth: 0,
  delayADuck: 0,
  delayAWidth: 0.5,
  drumDelayNoteL: '1/32',
  drumDelayNoteR: '1/32',
  granularDelayEnabled: true,
  granularDelayMix: 0.18,
  granularDelayActivity: 1,
  granularDelayRepeats: 0,
  granularDelayTime: '1/32',
  granularDelayFilter: 1,
  granularDelayVibrato: 0,
  granularSpaceMode: 'cascade',
  delayBPattern: 'cascade',
  delayBWarp: 'clean',
  delayBWarpIntensity: 0,
  delayBSpread: 0.5,
  granularLevel: 0.2,
  granularPad1Send: 0,
  granularPad2Send: 0,
  granularLead1Send: 0,
  granularLead2Send: 0,
  granularPianoSend: 0,
  granularDrumSend: 0,
  pad1ReverbSend: 0,
  pad1DelayASend: 0,
  pad1DelayBSend: 0,
  pad2ReverbSend: 0,
  pad2DelayASend: 0,
  pad2DelayBSend: 0,
  lead1ReverbSend: 0,
  lead1DelayASend: 0,
  lead1DelayBSend: 0,
  lead2ReverbSend: 0,
  lead2DelayASend: 0,
  lead2DelayBSend: 0,
  pianoReverbSend: 0,
  pianoDelayASend: 0,
  pianoDelayBSend: 0,
  drumReverbSend: 0,
  drumDelayASend: 0,
  drumDelayBSend: 0,
};

const pad1SourceSendMasterState = {
  ...sourceSendFxBaseState,
  pad1ReverbSend: 0.34,
  pad1DelayASend: 0.28,
  pad1DelayBSend: 0.24,
  granularPad1Send: 0.24,
};

const pad2SourceSendMasterState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  pad2Enabled: true,
  pad2Level: 0.5,
  pad2ReverbSend: 0.34,
  pad2DelayASend: 0.28,
  pad2DelayBSend: 0.24,
  granularPad2Send: 0.24,
};

const leadSourceSendMasterState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  leadEnabled: true,
  lead2Enabled: false,
  lead1Level: 0.5,
  lead1ReverbSend: 0.34,
  lead1DelayASend: 0.28,
  lead1DelayBSend: 0.24,
  granularLead1Send: 0.24,
};

const lead2SourceSendMasterState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  leadEnabled: false,
  lead2Enabled: true,
  lead2Level: 0.5,
  lead2ReverbSend: 0.34,
  lead2DelayASend: 0.28,
  lead2DelayBSend: 0.24,
  granularLead2Send: 0.24,
};

const pianoSourceSendMasterState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  pianoEnabled: true,
  pianoLevel: 0.5,
  pianoReverbSend: 0.34,
  pianoDelayASend: 0.28,
  pianoDelayBSend: 0.24,
  granularPianoSend: 0.24,
  pianoPostLPF: 14000,
  pianoStereoWidth: 0.85,
};

const drumSourceSendMasterState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  drumEnabled: true,
  drumEuclidMasterEnabled: false,
  drumLevel: 0.75,
  drumReverbSend: 0.34,
  drumDelayASend: 0.28,
  drumDelayBSend: 0.24,
  granularDrumSend: 0.24,
};

const sidechainState = {
  ...baseState,
  sidechainEnabled: true,
  sidechainKeyA: 'kick',
  sidechainKeyB: 'off',
  sidechainKeyAWeight: 1,
  sidechainKeyBWeight: 0,
  sidechainAmount: 1,
  sidechainThreshold: -60,
  sidechainRatio: 20,
  sidechainKnee: 0,
  sidechainAttackMs: 18,
  sidechainHoldMs: 70,
  sidechainReleaseMs: 260,
  sidechainMakeup: 1,
  sidechainMix: 1,
  sidechainCurve: 0.5,
  sidechainPad1Target: 1,
  drumEnabled: true,
  drumEuclidMasterEnabled: false,
  drumLevel: 0.75,
  drumReverbSend: 0,
  drumDelayASend: 0,
  drumDelayBSend: 0,
  granularDrumSend: 0,
};

const reverbTensionScaleState = {
  ...baseState,
  reverbEnabled: true,
  reverbLevel: 0.35,
  pad1ReverbSend: 0.4,
  synthReverbSend: 0.4,
  tension: 0.9,
  reverbTensionMode: 'locked',
  reverbTensionValue: 0.9,
  reverbDecay: 0.2,
  reverbDiffusion: 0.2,
  reverbShimmer: 0.1,
  reverbShimmerPitch: 13,
  reverbScaleShimmer: true,
  scaleMode: 'manual',
  manualScale: 'Major (Ionian)',
  reverbType: 'hall',
  reverbQuality: 'balanced',
  predelay: 0,
};

const reverbWashBloomState = {
  ...baseState,
  reverbEnabled: true,
  reverbLevel: 0.35,
  pad1ReverbSend: 0.4,
  synthReverbSend: 0.4,
  reverbType: 'hall',
  reverbQuality: 'balanced',
  reverbDecay: 0.25,
  reverbDiffusion: 0.55,
  reverbShimmer: 0.02,
  sonicParityReverbWashBoost: 1,
  sonicParityReverbBloomBoost: 1,
  predelay: 0,
};

const reverbLiveWashBloomState = {
  ...baseState,
  reverbEnabled: true,
  reverbLevel: 0.35,
  pad1ReverbSend: 0.4,
  synthReverbSend: 0.4,
  reverbType: 'hall',
  reverbQuality: 'balanced',
  reverbDecay: 0.25,
  reverbDiffusion: 0.55,
  reverbShimmer: 0.02,
  predelay: 0,
  reverbChordWash: true,
  reverbResolutionBloom: true,
  phraseLength: 0.25,
  harmonyClockSource: 'localPhrase',
  transportPrimaryClock: 'seconds',
  transportBarsPerPhrase: 1,
  transportBeatsPerBar: 4,
  tension: 0.45,
  seed: 42,
  seedWindow: 'day',
};

const reverbMobileQualityState = {
  ...baseState,
  reverbEnabled: true,
  reverbLevel: 0.35,
  pad1ReverbSend: 0.4,
  synthReverbSend: 0.4,
  reverbType: 'hall',
  reverbQuality: 'ultra',
  reverbDecay: 0.35,
  reverbDiffusion: 0.65,
  reverbShimmer: 0.05,
  predelay: 0,
};

const reverbProductionWideState = {
  ...baseState,
  reverbEnabled: true,
  reverbLevel: 0.34,
  pad1ReverbSend: 0.42,
  synthReverbSend: 0.42,
  reverbType: 'hall',
  reverbQuality: 'balanced',
  reverbDecay: 0.48,
  reverbDiffusion: 0.72,
  reverbShimmer: 0.08,
  reverbShimmerPitch: 19,
  reverbScaleShimmer: true,
  scaleMode: 'manual',
  manualScale: 'Dorian',
  reverbSize: 3.8,
  damping: 0.34,
  reverbModulation: 0.58,
  predelay: 18,
  width: 0.82,
  reverbSlowModRate: 0.09,
  reverbSlowModDepth: 0.18,
  reverbReverse: 0.08,
  reverbReverseLength: 3.2,
  reverbChorusRate: 0.7,
  reverbChorusDepth: 10,
  reverbModCharacter: 'hybrid',
  reverbDampLow: 0.18,
  reverbDampHigh: 0.42,
  reverbCrossoverFreq: 950,
  reverbInputTone: 0.12,
  reverbShimmerFeedback: 0.08,
  reverbWarp: 0.16,
  reverbCrossFeed: 0.12,
  reverbEarlyReflections: 0.36,
  reverbAirAbsorption: 0.28,
  reverbSaturationMode: 'tape',
  reverbTransientSmooth: 0.12,
  reverbErLpFreq: 3100,
};

const soundscapeOceanState = {
  ...baseState,
  padEnabled: false,
  oceanSampleEnabled: true,
  oceanSampleLevel: 0.55,
  earthLevel: 1,
  oceanReverbSend: 0,
  oceanDelayASend: 0,
  oceanDelayBSend: 0,
  granularWavesSend: 0,
  oceanSliceDuration: 6,
  oceanSliceDensity: 1,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeOceanProductionState = {
  ...baseState,
  padEnabled: false,
  oceanSampleEnabled: true,
  oceanSampleLevel: 0.55,
  earthLevel: 1,
  oceanReverbSend: 0,
  oceanDelayASend: 0,
  oceanDelayBSend: 0,
  granularWavesSend: 0,
  oceanSliceDuration: 22,
  oceanSliceDensity: 0.38,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeNatureState = {
  ...baseState,
  padEnabled: false,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 1,
  natureReverbSend: 0,
  natureDelayASend: 0,
  natureDelayBSend: 0,
  granularNatureSend: 0,
  birds2SliceDuration: 6,
  birds2SliceDensity: 1,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeNatureProductionState = {
  ...baseState,
  padEnabled: false,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 0.41,
  natureReverbSend: 0,
  natureDelayASend: 0,
  natureDelayBSend: 0,
  granularNatureSend: 0,
  birds2SliceDuration: 20,
  birds2SliceDensity: 0.48,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeOceanNatureProductionState = {
  ...soundscapeOceanProductionState,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 0.41,
  natureReverbSend: 0,
  natureDelayASend: 0,
  natureDelayBSend: 0,
  granularNatureSend: 0,
  birds2SliceDuration: 20,
  birds2SliceDensity: 0.48,
};

const soundscapeWaterState = {
  ...baseState,
  padEnabled: false,
  waterEnabled: true,
  waterLevel: 0.8,
  earthLevel: 1,
  waterReverbSend: 0,
  waterDelayASend: 0,
  waterDelayBSend: 0,
  granularWaterSend: 0,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeInsectsState = {
  ...baseState,
  padEnabled: false,
  insectsEnabled: true,
  insects2Enabled: false,
  insectsLevel: 0.7,
  insectsSharedLevel: 1,
  earthLevel: 1,
  insectsReverbSend: 0,
  insDelayASend: 0,
  insDelayBSend: 0,
  granularInsectsSend: 0,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeWaterInsectsState = {
  ...soundscapeWaterState,
  insectsEnabled: true,
  insectsLevel: 0.55,
  insectsSharedLevel: 1,
  insectsReverbSend: 0,
  insDelayASend: 0,
  insDelayBSend: 0,
  granularInsectsSend: 0,
};

const soundscapeWaterSourceSendState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  waterEnabled: true,
  waterLevel: 0.8,
  earthLevel: 1,
  waterReverbSend: 0.34,
  waterDelayASend: 0.28,
  waterDelayBSend: 0.24,
  granularWaterSend: 0.24,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeInsectsSourceSendState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  insectsEnabled: true,
  insects2Enabled: false,
  insectsLevel: 0.7,
  insectsSharedLevel: 1,
  earthLevel: 1,
  insectsReverbSend: 0.34,
  insDelayASend: 0.28,
  insDelayBSend: 0.24,
  granularInsectsSend: 0.24,
  soundscapeParityFixture: true,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeOceanProductionSourceSendState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  oceanSampleEnabled: true,
  oceanSampleLevel: 0,
  earthLevel: 0.41,
  oceanReverbSend: 0.34,
  oceanDelayASend: 0.28,
  oceanDelayBSend: 0.24,
  granularWavesSend: 0.24,
  oceanSliceDuration: 22,
  oceanSliceDensity: 0.38,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeNatureProductionSourceSendState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 0.41,
  natureReverbSend: 0.34,
  natureDelayASend: 0.28,
  natureDelayBSend: 0.24,
  granularNatureSend: 0.24,
  birds2SliceDuration: 20,
  birds2SliceDensity: 0.48,
  seed: 42,
  seedWindow: 'day',
};

const soundscapeOceanNatureProductionSourceSendState = {
  ...sourceSendFxBaseState,
  padEnabled: false,
  oceanSampleEnabled: true,
  oceanSampleLevel: 0,
  birdsEnabled: false,
  birds2Enabled: true,
  frogsEnabled: false,
  birds2Level: 0.55,
  natureLevel: 0.8,
  earthLevel: 0.41,
  oceanReverbSend: 0.34,
  oceanDelayASend: 0.28,
  oceanDelayBSend: 0.24,
  granularWavesSend: 0.24,
  natureReverbSend: 0.34,
  natureDelayASend: 0.28,
  natureDelayBSend: 0.24,
  granularNatureSend: 0.24,
  oceanSliceDuration: 22,
  oceanSliceDensity: 0.38,
  birds2SliceDuration: 20,
  birds2SliceDensity: 0.48,
  seed: 42,
  seedWindow: 'day',
};

const cases = [
  {
    id: 'master-pad-reverb-scene',
    domain: 'reverbMacro',
    durationMs: 1600,
    noteDurationMs: 1200,
    statePatch: { ...baseState, reverbEnabled: true, reverbLevel: 0.35, reverbPreDelay: 0, reverbDecay: 0.35, reverbTone: 0.5, reverbMod: 0 },
    rmsTolerance: 0.08,
    peakTolerance: 0.12,
    minLagCorrelation: 0.95,
  },
  {
    id: 'master-pad-reverb-tension-scale-scene',
    domain: 'reverbMacro',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    statePatch: reverbTensionScaleState,
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.95,
    maxLagMs: 160,
    envelopeTimeToleranceMs: 60,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-pad-reverb-wash-bloom-scene',
    domain: 'reverbMacro',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    statePatch: reverbWashBloomState,
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.92,
    maxLagMs: 160,
    envelopeTimeToleranceMs: 60,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-pad-reverb-live-wash-bloom-decay-scene',
    domain: 'reverbMacro',
    durationMs: 1600,
    settleMs: 0,
    noteDurationMs: 1400,
    statePatch: reverbLiveWashBloomState,
    stateEvents: [{ delayMs: 300, patch: { tension: 0.1 } }],
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.92,
    maxLagMs: 160,
    envelopeTimeToleranceMs: 120,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-pad-reverb-mobile-quality-scene',
    domain: 'reverbMacro',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    statePatch: reverbMobileQualityState,
    mobileDevice: true,
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.92,
    maxLagMs: 160,
    envelopeTimeToleranceMs: 80,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-pad-reverb-production-wide-scene',
    domain: 'reverbMacro',
    durationMs: 2200,
    settleMs: 250,
    noteDurationMs: 1600,
    statePatch: reverbProductionWideState,
    rmsTolerance: 0.15,
    peakTolerance: 0.18,
    minLagCorrelation: 0.9,
    maxLagMs: 180,
    envelopeTimeToleranceMs: 80,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad-granular-clean-scene',
    domain: 'granular',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    statePatch: granularCleanState,
    rmsTolerance: 0.08,
    peakTolerance: 0.12,
    minLagCorrelation: 0.95,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-pad-granular-two-voice-clean-scene',
    domain: 'granular',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    statePatch: granularTwoVoiceCleanState,
    rmsTolerance: 0.1,
    peakTolerance: 0.14,
    minLagCorrelation: 0.92,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad-granular-modulated-clean-scene',
    domain: 'granular',
    durationMs: 1900,
    settleMs: 250,
    noteDurationMs: 1450,
    statePatch: granularModulatedCleanState,
    rmsTolerance: 0.12,
    peakTolerance: 0.16,
    minLagCorrelation: 0.9,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad-granular-feedback-clean-scene',
    domain: 'granular',
    durationMs: 2200,
    settleMs: 250,
    noteDurationMs: 1450,
    statePatch: granularFeedbackState,
    rmsTolerance: 0.14,
    peakTolerance: 0.18,
    minLagCorrelation: 0.88,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.55,
  },
  {
    id: 'master-pad-granular-delayed-freeze-clean-scene',
    domain: 'granular',
    durationMs: 2300,
    settleMs: 250,
    noteDurationMs: 1700,
    statePatch: granularDelayedFreezeState,
    stateEvents: [{ delayMs: 520, patch: { granularFreeze: true } }],
    rmsTolerance: 0.14,
    peakTolerance: 0.18,
    minLagCorrelation: 0.86,
    envelopeTimeToleranceMs: 100,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.55,
  },
  {
    id: 'master-pad-granular-legacy-cloud-scene',
    domain: 'granular',
    durationMs: 1500,
    settleMs: 250,
    noteDurationMs: 1100,
    statePatch: granularLegacyCloudState,
    rmsTolerance: 0.12,
    peakTolerance: 0.16,
    minLagCorrelation: 0.9,
    envelopeRmsRatioTolerance: 0.4,
    envelopePeakRatioTolerance: 0.4,
  },
  {
    id: 'master-pad-spectral-freeze-live-pre-scene',
    domain: 'spectralFreeze',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    statePatch: spectralFreezeLiveState,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
  },
  {
    id: 'master-pad-spectral-freeze-live-post-scene',
    domain: 'spectralFreeze',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1400,
    statePatch: spectralFreezeLivePostState,
    rmsTolerance: 0.5,
    peakTolerance: 0.5,
    minLagCorrelation: 0.85,
  },
  {
    id: 'master-pad-diffuse-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1400,
    noteDurationMs: 1000,
    statePatch: { ...baseState, padDiffuseSend: 0.7 },
    rmsTolerance: 0.08,
    peakTolerance: 0.12,
    minLagCorrelation: 0.95,
  },
  {
    id: 'master-pad-diffuse-distance-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1500,
    noteDurationMs: 1100,
    statePatch: padDistanceDiffuseState,
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.92,
    maxLagMs: 160,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad2-diffuse-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1400,
    statePatch: pad2DiffuseState,
    manualNotes: ['pad2:64:0.75:1000'],
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.94,
    maxLagMs: 140,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-lead1-diffuse-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1400,
    statePatch: {
      ...baseState,
      padEnabled: false,
      leadEnabled: true,
      lead1Level: 0.5,
      lead1DiffuseSend: 0.7,
    },
    manualNotes: ['lead1:67:0.75:1000'],
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.94,
    maxLagMs: 140,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-lead1-diffuse-distance-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1500,
    statePatch: {
      ...baseState,
      padEnabled: false,
      leadEnabled: true,
      lead1Level: 0.5,
      lead1DiffuseSend: 0.7,
      lead1Distance: 0.65,
    },
    manualNotes: ['lead1:67:0.75:1100'],
    rmsTolerance: 0.012,
    peakTolerance: 0.025,
    minLagCorrelation: 0.99,
    maxLagMs: 40,
    envelopeRmsRatioTolerance: 0.3,
    envelopePeakRatioTolerance: 0.3,
  },
  {
    id: 'master-lead2-diffuse-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1400,
    statePatch: {
      ...baseState,
      padEnabled: false,
      lead2Enabled: true,
      lead2Level: 0.5,
      lead2DiffuseSend: 0.7,
    },
    manualNotes: ['lead2:67:0.75:1000'],
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.94,
    maxLagMs: 140,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-lead2-diffuse-distance-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1500,
    statePatch: {
      ...baseState,
      padEnabled: false,
      lead2Enabled: true,
      lead2Level: 0.5,
      lead2DiffuseSend: 0.7,
      lead2Distance: 0.65,
    },
    manualNotes: ['lead2:67:0.75:1100'],
    rmsTolerance: 0.012,
    peakTolerance: 0.025,
    minLagCorrelation: 0.99,
    maxLagMs: 40,
    envelopeRmsRatioTolerance: 0.3,
    envelopePeakRatioTolerance: 0.3,
  },
  {
    id: 'master-piano-diffuse-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1400,
    statePatch: {
      ...baseState,
      padEnabled: false,
      pianoEnabled: true,
      pianoLevel: 0.5,
      pianoDiffuseSend: 0.7,
    },
    manualNotes: ['piano:64:0.74:1000'],
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.9,
    maxLagMs: 160,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-piano-diffuse-distance-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1500,
    statePatch: {
      ...baseState,
      padEnabled: false,
      pianoEnabled: true,
      pianoLevel: 0.5,
      pianoDiffuseSend: 0.7,
      pianoReverbSend: 0.18,
      pianoDistance: 0.65,
      pianoPostLPF: 14000,
      pianoStereoWidth: 0.85,
      masterVolume: 0.8,
      reverbMix: 0.12,
      diffuseEnabled: true,
      diffuseWet: 0.4,
      diffusePreDelay: 0.012,
      diffuseSpread: 0.6,
      diffuseSize: 0.55,
      diffuseTone: 0.7,
    },
    manualNotes: ['piano:64:0.74:1100'],
    rmsTolerance: 0.012,
    peakTolerance: 0.02,
    minLagCorrelation: 0.5,
    maxLagMs: 80,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
  },
  {
    id: 'master-diffuse-modulated-source-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1900,
    settleMs: 250,
    statePatch: diffuseModulatedSourceState,
    manualNotes: [
      'pad1:60:0.75:1300',
      'pad2:64:0.68:1200',
      'lead1:67:0.62:1000',
    ],
    rmsTolerance: 0.16,
    peakTolerance: 0.18,
    minLagCorrelation: 0.88,
    maxLagMs: 180,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
  },
  {
    id: 'master-diffuse-all-source-distance-scene',
    domain: 'diffuseSourceSpatial',
    durationMs: 1900,
    settleMs: 250,
    statePatch: diffuseAllSourceDistanceState,
    manualNotes: [
      'pad1:60:0.72:1350',
      'pad2:64:0.66:1250',
      'lead1:67:0.58:1100',
      'lead2:71:0.54:950',
      'piano:64:0.62:1200',
    ],
    rmsTolerance: 0.16,
    peakTolerance: 0.18,
    minLagCorrelation: 0.88,
    maxLagMs: 180,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
  },
  {
    id: 'master-pad-delay-ab-feedback-scene',
    domain: 'delayAB',
    durationMs: 1600,
    noteDurationMs: 1200,
    statePatch: delaySceneState,
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.94,
    maxLagMs: 140,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-pad-delay-a-long-feedback-scene',
    domain: 'delayAB',
    durationMs: 2400,
    noteDurationMs: 1500,
    statePatch: delayALongFeedbackState,
    rmsTolerance: 0.16,
    peakTolerance: 0.18,
    minLagCorrelation: 0.9,
    maxLagMs: 220,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad-delay-b-long-feedback-scene',
    domain: 'delayAB',
    durationMs: 2400,
    noteDurationMs: 1500,
    statePatch: delayBLongFeedbackState,
    rmsTolerance: 0.16,
    peakTolerance: 0.18,
    minLagCorrelation: 0.9,
    maxLagMs: 220,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad-delay-a-to-b-order-scene',
    domain: 'delayAB',
    durationMs: 2300,
    noteDurationMs: 1400,
    statePatch: delayAToBOrderState,
    rmsTolerance: 0.16,
    peakTolerance: 0.18,
    minLagCorrelation: 0.9,
    maxLagMs: 220,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad-delay-b-to-a-order-scene',
    domain: 'delayAB',
    durationMs: 2300,
    noteDurationMs: 1400,
    statePatch: delayBToAOrderState,
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.88,
    maxLagMs: 240,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.55,
  },
  {
    id: 'master-pad-dynamics-drift-scene',
    domain: 'dynamicsSidechainMaster',
    durationMs: 1400,
    noteDurationMs: 1000,
    statePatch: dynamicsDriftState,
    rmsTolerance: 0.08,
    peakTolerance: 0.12,
    minLagCorrelation: 0.95,
  },
  {
    id: 'master-pad-dynamics-saturation-scene',
    domain: 'dynamicsSidechainMaster',
    durationMs: 1400,
    noteDurationMs: 1000,
    statePatch: dynamicsSaturationState,
    rmsTolerance: 0.08,
    peakTolerance: 0.1,
    minLagCorrelation: 0.95,
  },
  {
    id: 'master-pad-dynamics-end-comp-scene',
    domain: 'dynamicsSidechainMaster',
    durationMs: 1500,
    noteDurationMs: 1100,
    statePatch: dynamicsEndCompState,
    rmsTolerance: 0.12,
    peakTolerance: 0.14,
    minLagCorrelation: 0.92,
    envelopeRmsRatioTolerance: 0.35,
    envelopePeakRatioTolerance: 0.4,
  },
  {
    id: 'master-pad-dynamics-sat-end-comp-scene',
    domain: 'dynamicsSidechainMaster',
    durationMs: 1500,
    noteDurationMs: 1100,
    statePatch: dynamicsSatEndCompState,
    rmsTolerance: 0.14,
    peakTolerance: 0.16,
    minLagCorrelation: 0.9,
    envelopeRmsRatioTolerance: 0.4,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-drum-kick-scene',
    domain: 'drumSourceSends',
    durationMs: 900,
    statePatch: drumKickState,
    manualNotes: false,
    manualDrums: ['kick:0.8:0'],
    rmsTolerance: 0.08,
    peakTolerance: 0.12,
    minLagCorrelation: 0.95,
  },
  {
    id: 'master-pad1-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1800,
    settleMs: 250,
    noteDurationMs: 1200,
    statePatch: pad1SourceSendMasterState,
    rmsTolerance: 0.14,
    peakTolerance: 0.18,
    minLagCorrelation: 0.9,
    maxLagMs: 180,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-pad2-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1800,
    settleMs: 250,
    statePatch: pad2SourceSendMasterState,
    manualNotes: ['pad2:64:0.75:1200'],
    rmsTolerance: 0.14,
    peakTolerance: 0.18,
    minLagCorrelation: 0.9,
    maxLagMs: 180,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-lead1-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1800,
    settleMs: 250,
    statePatch: leadSourceSendMasterState,
    manualNotes: ['lead1:64:0.75:1200'],
    rmsTolerance: 0.16,
    peakTolerance: 0.2,
    minLagCorrelation: 0.88,
    maxLagMs: 200,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.55,
  },
  {
    id: 'master-lead2-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1800,
    settleMs: 250,
    statePatch: lead2SourceSendMasterState,
    manualNotes: ['lead2:64:0.75:1200'],
    rmsTolerance: 0.16,
    peakTolerance: 0.2,
    minLagCorrelation: 0.88,
    maxLagMs: 200,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.55,
  },
  {
    id: 'master-piano-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1800,
    settleMs: 250,
    statePatch: pianoSourceSendMasterState,
    manualNotes: ['piano:64:0.75:1200'],
    rmsTolerance: 0.18,
    peakTolerance: 0.32,
    minLagCorrelation: 0.5,
    maxLagMs: 220,
    envelopeRmsRatioTolerance: 0.75,
    envelopePeakRatioTolerance: 0.85,
  },
  {
    id: 'master-drum-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1600,
    settleMs: 250,
    statePatch: drumSourceSendMasterState,
    manualNotes: false,
    manualDrums: ['kick:0.8:0'],
    rmsTolerance: 0.16,
    peakTolerance: 0.2,
    minLagCorrelation: 0.88,
    maxLagMs: 200,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.55,
  },
  {
    id: 'master-soundscape-water-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1000,
    settleMs: 1300,
    statePatch: soundscapeWaterSourceSendState,
    manualNotes: false,
    rmsTolerance: 0.18,
    peakTolerance: 0.22,
    minLagCorrelation: 0.86,
    maxLagMs: 200,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
  },
  {
    id: 'master-soundscape-insects-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 1000,
    settleMs: 1300,
    statePatch: soundscapeInsectsSourceSendState,
    manualNotes: false,
    rmsTolerance: 0.18,
    peakTolerance: 0.22,
    minLagCorrelation: 0.6,
    maxLagMs: 200,
    envelopeRmsRatioTolerance: 0.6,
    envelopePeakRatioTolerance: 0.6,
  },
  {
    id: 'master-soundscape-ocean-production-texture-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 2600,
    settleMs: 700,
    statePatch: soundscapeOceanProductionSourceSendState,
    manualNotes: false,
    rmsTolerance: 0.32,
    peakTolerance: 0.34,
    minLagCorrelation: 0.86,
    maxLagMs: 160,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-soundscape-nature-production-texture-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 2600,
    settleMs: 700,
    statePatch: soundscapeNatureProductionSourceSendState,
    manualNotes: false,
    rmsTolerance: 0.32,
    peakTolerance: 0.34,
    minLagCorrelation: 0.86,
    maxLagMs: 160,
    attempts: 4,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.65,
  },
  {
    id: 'master-soundscape-ocean-nature-production-texture-source-send-fx-scene',
    domain: 'drumSourceSends',
    durationMs: 2600,
    settleMs: 700,
    statePatch: soundscapeOceanNatureProductionSourceSendState,
    manualNotes: false,
    rmsTolerance: 0.34,
    peakTolerance: 0.36,
    minLagCorrelation: 0.5,
    maxLagMs: 180,
    attempts: 4,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.7,
  },
  {
    id: 'master-pad-sidechain-kick-scene',
    domain: 'dynamicsSidechainMaster',
    durationMs: 1400,
    noteDurationMs: 1000,
    statePatch: sidechainState,
    manualDrums: ['kick:0.9:80'],
    rmsTolerance: 0.18,
    peakTolerance: 0.2,
    minLagCorrelation: 0.9,
    maxLagMs: 140,
    envelopeRmsRatioTolerance: 0.45,
    envelopePeakRatioTolerance: 0.45,
  },
  {
    id: 'master-soundscape-ocean-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 1000,
    settleMs: 1300,
    statePatch: soundscapeOceanState,
    manualNotes: false,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    maxLagMs: 160,
    envelopePeakRatioTolerance: 0.5,
  },
  {
    id: 'master-soundscape-ocean-production-texture-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 2600,
    settleMs: 700,
    statePatch: soundscapeOceanProductionState,
    manualNotes: false,
    rmsTolerance: 0.28,
    peakTolerance: 0.3,
    minLagCorrelation: 0.86,
    maxLagMs: 80,
    attempts: 4,
    envelopeRmsRatioTolerance: 0.5,
    envelopePeakRatioTolerance: 0.65,
  },
  {
    id: 'master-soundscape-nature-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 1000,
    settleMs: 1300,
    statePatch: soundscapeNatureState,
    manualNotes: false,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    maxLagMs: 160,
    envelopePeakRatioTolerance: 0.4,
  },
  {
    id: 'master-soundscape-nature-production-texture-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 2600,
    settleMs: 700,
    statePatch: soundscapeNatureProductionState,
    manualNotes: false,
    rmsTolerance: 0.28,
    peakTolerance: 0.3,
    minLagCorrelation: 0.98,
    maxLagMs: 80,
    alignmentGate: true,
    envelopeGate: false,
    attempts: 8,
  },
  {
    id: 'master-soundscape-ocean-nature-production-texture-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 2600,
    settleMs: 700,
    statePatch: soundscapeOceanNatureProductionState,
    manualNotes: false,
    rmsTolerance: 0.34,
    peakTolerance: 0.36,
    minLagCorrelation: 0.5,
    maxLagMs: 180,
    attempts: 4,
    envelopeRmsRatioTolerance: 0.55,
    envelopePeakRatioTolerance: 0.7,
  },
  {
    id: 'master-soundscape-water-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 1000,
    settleMs: 1300,
    statePatch: soundscapeWaterState,
    manualNotes: false,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    maxLagMs: 180,
  },
  {
    id: 'master-soundscape-insects-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 1000,
    settleMs: 1300,
    statePatch: soundscapeInsectsState,
    manualNotes: false,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    minLagCorrelation: 0.98,
    maxLagMs: 180,
  },
  {
    id: 'master-soundscape-water-insects-dry-scene',
    domain: 'soundscapeLayers',
    durationMs: 1000,
    settleMs: 1300,
    statePatch: soundscapeWaterInsectsState,
    manualNotes: false,
    rmsTolerance: 0.12,
    peakTolerance: 0.08,
    minLagCorrelation: 0.95,
    maxLagMs: 180,
  },
];

export { cases as masterCases, baseState as defaultMasterState };
