import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(new URL('./index.html', import.meta.url).href);
  await page.waitForTimeout(150);
  assert.equal(await page.locator('details[open]').count(), 0);
  assert.equal(await page.locator('#macros input').count(), 10);
  for (const macro of await page.locator('#macros input').all()) assert.ok(await macro.isVisible());
  const engineBox = await page.locator('.engine-column').boundingBox();
  const fieldBox = await page.locator('.workspace-column').boundingBox();
  assert.ok(engineBox.x < fieldBox.x && engineBox.width < fieldBox.width);
  const surface = page.locator('#macros .macro-surface').first();
  const box = await surface.boundingBox();
  await page.mouse.move(box.x + box.width * .2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * .8, box.y + box.height / 2, { steps: 5 });
  await page.mouse.up();
  assert.ok(await page.evaluate(() => state.macros.texture > .7));
  await page.getByRole('slider', { name: 'Texture', exact: true }).focus();
  await page.keyboard.press('Home');
  assert.equal(await page.evaluate(() => state.macros.texture), 0);
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.evaluate(() => state.macros.texture), .01);
  await page.getByRole('slider', { name: 'Texture', exact: true }).fill('70');
  assert.equal(await page.evaluate(() => state.macros.texture), .7);
  assert.ok(await page.evaluate(() => state.voices[0].recipe.grainSizeMs > state.voices[0].base.grainSizeMs));
  await page.getByRole('button', { name: 'Reset macros' }).click();
  assert.ok(await page.evaluate(() => state.voices[0].recipe.grainSizeMs === state.voices[0].base.grainSizeMs));
  await page.getByRole('button', { name: '+ Emitter', exact: true }).click();
  assert.equal(await page.evaluate(() => state.voices[0].granularPlacements.length), 2);
  assert.ok(await page.evaluate(() => perEmitterDensity(state.voices[0]) * 2 === state.voices[0].recipe.density));
  await page.locator('#lanes button').nth(2).click();
  assert.equal(await page.evaluate(() => state.voices[0].granularPlacements[1].sourceX), 2);
  await page.getByRole('combobox', { name: 'Mode', exact: true }).selectOption('clean');
  assert.equal(await page.evaluate(() => state.voices[0].mode), 'clean');
  assert.ok(await page.getByRole('button', { name: '+ Emitter', exact: true }).isDisabled());
  await page.getByRole('combobox', { name: 'Mode', exact: true }).selectOption('granular');
  assert.equal(await page.evaluate(() => state.voices[0].granularPlacements.length), 2);
  await page.locator('#rail .voice').nth(1).focus();
  await page.keyboard.press('Enter');
  await page.waitForTimeout(160);
  assert.match(await page.locator('#inspectorTitle').textContent(), /Voice B/);
  await page.getByRole('button', { name: 'Freeze → new hold', exact: true }).click();
  assert.equal(await page.evaluate(() => sources[0].frozen), false);
  assert.match(await page.locator('#lanes button').nth(1).textContent(), /Captured/);
  const frozenWave = await page.evaluate(() => Array.from(sources[1].wave));
  const liveHead = await page.evaluate(() => sources[0].head);
  await page.waitForTimeout(160);
  assert.notEqual(await page.evaluate(() => sources[0].head), liveHead);
  assert.deepEqual(await page.evaluate(() => Array.from(sources[1].wave)), frozenWave);
  await page.getByRole('button', { name: 'Ⅱ Preview', exact: true }).click();
  const before = await page.evaluate(() => clock);
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => clock), before);
  await page.getByRole('slider', { name: 'Pitch', exact: true }).fill('12');
  await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => state.voices[1].recipe.pitch), 12);
  // Overlapping waveform clicks and double-clicks are inert; selection belongs to the top strip.
  const beforeWaveClick = await page.evaluate(() => JSON.stringify(state.voices));
  const cvBox = await page.locator('#field').boundingBox();
  await page.mouse.click(cvBox.x + 150, cvBox.y + 180);
  await page.mouse.dblclick(cvBox.x + 150, cvBox.y + 180);
  assert.equal(await page.evaluate(() => state.selVoice), 1);
  assert.equal(await page.evaluate(() => JSON.stringify(state.voices)), beforeWaveClick);
  await page.locator('#rail .voice').first().click();
  await page.waitForTimeout(120);
  await page.getByRole('button', { name: 'Select A2', exact: true }).click();
  assert.equal(await page.evaluate(() => state.selPlacement), 1);
  await page.getByRole('combobox', { name: 'Source', exact: true }).selectOption('0');
  await page.getByRole('slider', { name: 'Anchor position', exact: true }).fill('0');
  assert.equal(await page.evaluate(() => yOf(selectedPlacement().timeY)), await page.evaluate(() => F.y));
  assert.equal(await page.evaluate(() => timeLabel(selectedPlacement())), '16.00s ago');
  await page.getByRole('slider', { name: 'Anchor position', exact: true }).fill('1');
  assert.equal(await page.evaluate(() => yOf(selectedPlacement().timeY)), await page.evaluate(() => F.y+F.h));
  const geo = await page.evaluate(() => ({ y:F.y, h:F.h }));
  await page.mouse.move(cvBox.x+48, cvBox.y+geo.y+geo.h);
  await page.mouse.down();
  await page.mouse.move(cvBox.x+48, cvBox.y+geo.y, { steps: 6 });
  await page.mouse.up();
  assert.equal(await page.evaluate(() => selectedPlacement().timeY), 0);
  assert.equal(await page.getByRole('slider', { name: 'Source blend', exact: true }).count(), 0);
  assert.ok((await page.locator('.macro-panel').boundingBox()).height <= 210);
  await page.getByRole('button', { name: '▷ Preview', exact: true }).click();
  await page.waitForFunction(()=>particles.length>0);
  assert.ok(await page.evaluate(() => particles.length > 0));
  assert.ok(await page.evaluate(() => particles.every(g => Number.isInteger(g.sx))));
  assert.ok(await page.evaluate(() => particles.every(g => g.startTy >= g.spawnLow && g.startTy <= g.spawnHigh)));
  await page.getByRole('button', { name: 'Ⅱ Preview', exact: true }).click();
  await page.getByRole('combobox', { name: 'Source', exact: true }).selectOption('1');
  await page.getByRole('slider', { name: 'Anchor position', exact: true }).fill('0.5');
  await page.getByRole('slider', { name: 'Time window', exact: true }).fill('0.4');
  await page.waitForTimeout(80);
  const resizeData = await page.evaluate(() => ({ h:windowHandles()[1], F:{y:F.y,h:F.h}, anchor:selectedPlacement().timeY }));
  const fieldRect = await page.locator('#field').boundingBox();
  await page.mouse.move(fieldRect.x+resizeData.h.x,fieldRect.y+resizeData.h.y);
  await page.mouse.down();
  await page.mouse.move(fieldRect.x+resizeData.h.x,fieldRect.y+resizeData.h.y+25,{steps:5});
  await page.mouse.up();
  assert.equal(await page.evaluate(() => selectedPlacement().timeY),resizeData.anchor);
  assert.ok(await page.evaluate(() => state.voices[0].base.timeSpray>.4));
  assert.ok(await page.evaluate(() => {
    const v=state.voices[0];return windowBounds(v,v.granularPlacements[0]).half===windowBounds(v,v.granularPlacements[1]).half;
  }));
  assert.equal(await page.locator('.inspector #placementControls').count(),1);
  // Raising density changes event rate, not emitter count or duplicate voice recipes.
  await page.getByRole('slider', { name: 'Density', exact: true }).fill('24');
  assert.ok(await page.evaluate(() => perEmitterDensity(state.voices[0]) === 12));
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await page.waitForTimeout(100);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}px`);
  }
  await page.locator('#globalDetails summary').click();
  await page.getByRole('slider', { name: 'Max grains', exact: true }).fill('16');
  assert.equal(await page.evaluate(() => globalState.maxGrains), 16);
  assert.ok(await page.evaluate(() => {
    const v=state.voices[0],g={sx:0,visualX:0,life:.5,pitch:0},r={...v.recipe};
    const low=grainAppearance({...v,recipe:{...r,gain:0,pan:-1,blur:0}},g);
    const high=grainAppearance({...v,recipe:{...r,gain:1,pan:1,blur:1}},g);
    return low.alpha===0&&high.alpha>0&&low.x<high.x&&low.halo<high.halo&&JSON.stringify(grainAppearance(v,{...g,pitch:12}).tint)!==JSON.stringify(grainAppearance(v,{...g,pitch:-12}).tint);
  }));
  assert.equal(await page.locator('#voiceIndicators').count(),0);
  assert.ok((await page.locator('#field').boundingBox()).y < (await page.locator('.inspector').boundingBox()).y);
  await page.setViewportSize({width:1440,height:1000});
  const storedBefore=await page.evaluate(()=>sourceStore.length);
  await page.getByRole('button',{name:'Freeze → new hold',exact:true}).click();
  assert.equal(await page.evaluate(()=>sourceStore.length),storedBefore+1);
  await page.getByRole('button',{name:'Emitter on',exact:true}).click();
  assert.equal(await page.evaluate(()=>selectedPlacement().enabled),false);
  assert.equal(await page.locator('#emitterPicker button').count(),2);
  await page.getByRole('button',{name:'Save as…',exact:true}).click();
  await page.locator('#sceneName').fill('Round trip');
  await page.locator('#sceneNote').fill('Two emitters and stored sources');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  const sceneId=await page.locator('#sceneSelect').inputValue();
  const expected=await page.evaluate(()=>({macros:state.macros,sourceIds:laneIds,base:state.voices[0].base,enabled:selectedPlacement().enabled}));
  await page.locator('#sceneSelect').selectOption('classic_cloud');
  await page.locator('#sceneSelect').selectOption(sceneId);
  assert.deepEqual(await page.evaluate(()=>({macros:state.macros,sourceIds:laneIds,base:state.voices[0].base,enabled:state.voices[0].granularPlacements[1].enabled})),expected);
  assert.equal(await page.locator('#presetModified').textContent(),'');
  await page.reload();
  await page.locator('#sceneSelect').selectOption(sceneId);
  assert.equal(await page.evaluate(()=>state.voices[0].granularPlacements.length),2);
  assert.equal(await page.evaluate(()=>state.voices[0].granularPlacements[1].enabled),false);
  const importData=await page.evaluate(()=>JSON.stringify(sceneSnapshot()));
  await page.locator('#sceneFile').setInputFiles({name:'preview.json',mimeType:'application/json',buffer:Buffer.from(importData)});
  await page.waitForFunction(()=>document.getElementById('sceneStatus').textContent==='Imported and saved locally');
  const importId=await page.locator('#sceneSelect').inputValue();
  await page.locator('#sceneFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});
  await page.waitForFunction(()=>document.getElementById('sceneStatus').textContent.includes('version 1'));
  assert.equal(await page.locator('#sceneSelect').inputValue(),importId);
  assert.ok(await page.evaluate(()=>validPreview(sceneSnapshot())));
  assert.equal(await page.evaluate(()=>validPreview({...sceneSnapshot(),version:99})),false);
  assert.equal(await page.evaluate(()=>validPreview({...sceneSnapshot(),voices:[null,null,null,null]})),false);
  assert.deepEqual(errors, []);
  const touch = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true });
  await touch.goto(new URL('./index.html', import.meta.url).href);
  await touch.locator('#macros .macro-surface').first().evaluate(e=>e.scrollIntoView({block:'center'}));
  const touchBox = await touch.locator('#macros .macro-surface').first().boundingBox();
  await touch.touchscreen.tap(touchBox.x + touchBox.width * .75, touchBox.y + touchBox.height / 2);
  assert.ok(await touch.evaluate(() => state.macros.texture > .6));
  await touch.close();
  console.log('Passed: scene save/load/reload, import validation, stored captures, emitter enablement, window interactions, macros, keyboard/touch, and four viewport sizes.');
} finally {
  await browser.close();
}
